#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
"""
generate_figures.py — 高1数学I「数と式」単元 図版パラメトリック生成スクリプト
==============================================================================
様式: docs/SPEC_figures.md・NE_STANDARD_FORM_SPEC_20260829.md §12 に準拠。
描画ヘルパー（Canvas/矢印/Checker）は先行単元
materials/hs-math-i/hs-math-i-quadratic-functions/assets_provenance/generate_figures.py
からコピー再利用（元スクリプトは無変更）。

- 実行: python3 generate_figures.py
- 出力: ../assets/L{NN}_fig{n}_{slug}.svg（15枚）と FIGURE_MANIFEST.md（この階層・自動生成）
- 依存: Python標準ライブラリのみ（math / datetime / html / pathlib / re / xml.etree / fractions）
- 図の選定: 本単元は標準形§12のプレースホルダ方式——NE_CONTENT_MAP と各 lesson notes の
  図版仕様（notes/lesson_XX_notes.md）が内容仕様の正。任意図版2点（L04_fig1・L10_fig2）も
  図表積極採用の判断基準（3文以上の文章説明が続く概念・手順・対比）を満たすと判断し採用した。
- 数学の自己検証: 各 fig_* 関数内の Checker が assert 相当の検算を行い、
  1つでも失敗すると例外で停止して図を出力しない。座標はすべて値から線形変換で計算し、
  端点・点・矢印の位置を本文の値と照合する（目分量ゼロ）。
- 答えの分離方針（二重ゲート＋陽性対照）:
  (1) 許可リスト検査——各図が宣言した「本文明示値のみのラベル一覧」(allow_texts) と、
      生成後SVGの<text>全内容が集合として完全一致することを検査する（未宣言ラベルの混入も検出）。
  (2) 禁止文字列検査——近隣の練習・stretchの答え由来のトークン(check_tokens)が
      図中テキストに現れないことを検査する（vocabulary禁止語はSVG全文に対して check_tokens_full）。
  検査器自体は main() 冒頭の陽性対照（禁止値を仕込んだ合成SVGで検出できること）で毎回実証する。
- ●○規約（docs/SPEC_figures.md §9-1）: 端点●=含む／○=含まないは数直線系図版
  （L08_fig1・L09_fig1・L10_fig2）で共通のパラメータ（半径・線幅）を使い、
  L09_fig1 は二次関数 L12_fig1 の「数直線3段」描法に揃えた。
  L05_fig2・L06_fig1・L07 の点・帯は解範囲表現でないため●○の意味づけを与えていない
  （点マーカーの描画パラメータのみ共通）。
- 改修方法（第三者向け）: 各 fig_* 関数冒頭の「パラメータ」ブロックの数値を変えて
  再実行する。数値は該当レッスン本文（candidate_draft/lesson_XX.md）と一致させること。
"""

import math
import datetime
import re
import xml.etree.ElementTree as ET
from fractions import Fraction as F
from html import escape, unescape
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent / "assets"
GENERATED = datetime.date.today().isoformat()

# ---- 様式定数（docs/SPEC_figures.md） ----------------------------------
MAIN_W = 1.6      # 主線幅
BOLD_W = 3.2      # 強調線幅
AUX_W = 1.1       # 補助線幅
DASH = "6 4"      # 破線
FS = 13           # 基本文字サイズ(px)
FS_NUM = 11       # 目盛数値
DOT_R = 2.5       # 点マーカー半径
DOT_R_END = 3.4   # 端点●○はやや大きく（数直線系で共通）
END_STROKE = 1.4  # ○の縁の線幅（共通）
SHADE = "#ddd"    # うすい網かけ
SHADE2 = "#eee"   # さらにうすい網かけ


# ===========================================================================
# 描画ヘルパー（px直書き中心。先行単元からコピー再利用+数直線系を追加）
# ===========================================================================
class Canvas:
    def __init__(self, width, height, sx=1.0, sy=None, ox=0.0, oy=0.0):
        self.w, self.h = width, height
        self.sx = sx
        self.sy = sx if sy is None else sy
        self.ox, self.oy = ox, oy
        self.defs = []
        self.body = []

    def raw(self, s):
        self.body.append(s)

    def line_px(self, x1, y1, x2, y2, w=MAIN_W, dash=None, color="#000"):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.raw(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
                 f'stroke="{color}" stroke-width="{w}"{d}/>')

    def text_px(self, x, y, s, size=FS, anchor="middle", weight=None):
        wgt = f' font-weight="{weight}"' if weight else ""
        self.raw(f'<text x="{x:.1f}" y="{y:.1f}" font-size="{size}" '
                 f'text-anchor="{anchor}"{wgt}>{escape(s)}</text>')

    def rect_px(self, x, y, w, h, fill="none", dash=None, sw=1.4):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.raw(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
                 f'fill="{fill}" stroke="#000" stroke-width="{sw}"{d}/>')

    def save(self, path, fig_id, title, desc=None):
        defs = f"<defs>{''.join(self.defs)}</defs>" if self.defs else ""
        svg = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.w} {self.h}">\n'
            f'<title>{escape(title)}</title>\n'
            + (f'<desc>{escape(desc)}</desc>\n' if desc else "") +
            f'<!-- {fig_id} | {title} -->\n'
            f'<!-- generated by assets_provenance/generate_figures.py on {GENERATED} '
            f'(docs/SPEC_figures.md・標準形§12準拠・SVG直接編集禁止/スクリプト改修で再生成) -->\n'
            f'<rect x="0" y="0" width="{self.w}" height="{self.h}" fill="#fff"/>\n'
            + defs + "\n".join(self.body) + "\n</svg>\n"
        )
        path.write_text(svg, encoding="utf-8")


def arrow_px(cv, x1, y1, x2, y2, w=1.4, head=7.0):
    """SVG座標(px)で矢印（線+先端の三角形）を描く"""
    ang = math.atan2(y2 - y1, x2 - x1)
    bx, by = x2 - head * math.cos(ang), y2 - head * math.sin(ang)
    cv.raw(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{bx:.1f}" y2="{by:.1f}" '
           f'stroke="#000" stroke-width="{w}"/>')
    nx, ny = -math.sin(ang), math.cos(ang)
    cv.raw(f'<polygon points="{x2:.1f},{y2:.1f} '
           f'{bx + nx * head * 0.45:.1f},{by + ny * head * 0.45:.1f} '
           f'{bx - nx * head * 0.45:.1f},{by - ny * head * 0.45:.1f}" fill="#000"/>')


def arc_arrow(cv, x1, y1, x2, y2, cx, cy, w=1.4, head=7.0):
    """2次ベジェの弧+終端矢じり（0中心の折り返し用）"""
    ang = math.atan2(y2 - cy, x2 - cx)
    bx, by = x2 - head * math.cos(ang), y2 - head * math.sin(ang)
    cv.raw(f'<path d="M {x1:.1f} {y1:.1f} Q {cx:.1f} {cy:.1f} {bx:.1f} {by:.1f}" '
           f'fill="none" stroke="#000" stroke-width="{w}"/>')
    nx, ny = -math.sin(ang), math.cos(ang)
    cv.raw(f'<polygon points="{x2:.1f},{y2:.1f} '
           f'{bx + nx * head * 0.45:.1f},{by + ny * head * 0.45:.1f} '
           f'{bx - nx * head * 0.45:.1f},{by - ny * head * 0.45:.1f}" fill="#000"/>')


def open_pt(cv, x, y):
    """端点○（その値をふくまない）——白抜き+黒縁。数直線系で共通のパラメータ"""
    cv.raw(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{DOT_R_END}" fill="#fff" '
           f'stroke="#000" stroke-width="{END_STROKE}"/>')


def closed_pt(cv, x, y):
    """端点●（その値をふくむ）／点マーカー——塗りつぶし。数直線系で共通のパラメータ"""
    cv.raw(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{DOT_R_END}" fill="#000"/>')


def tick_px(cv, x, y, half=3.5):
    cv.line_px(x, y - half, x, y + half, w=1.0)


def legend_endpoints(cv, x1, x2, y):
    """●○の凡例（L08_fig1・L09_fig1で共通の様式）。テキスト一覧を返す"""
    closed_pt(cv, x1, y)
    cv.text_px(x1 + 9, y + 4, "＝端の値を含む", size=11, anchor="start")
    open_pt(cv, x2, y)
    cv.text_px(x2 + 9, y + 4, "＝端の値を含まない", size=11, anchor="start")
    return ["＝端の値を含む", "＝端の値を含まない"]


class Checker:
    """数学検算の記録つきassert"""
    def __init__(self):
        self.items = []

    def ok(self, desc, cond, detail=""):
        assert cond, f"検証失敗: {desc} {detail}"
        self.items.append((desc, detail))


def poly_mul(p, q):
    """1変数多項式の係数列（低次→高次）の積（厳密・整数演算）"""
    r = [0] * (len(p) + len(q) - 1)
    for i, a in enumerate(p):
        for j, b in enumerate(q):
            r[i + j] += a * b
    return r


def inside(inner, outer):
    """矩形(x,y,w,h)が厳密に内側か"""
    return (outer[0] < inner[0] and inner[0] + inner[2] < outer[0] + outer[2] and
            outer[1] < inner[1] and inner[1] + inner[3] < outer[1] + outer[3])


def disjoint(r1, r2):
    return (r1[0] + r1[2] <= r2[0] or r2[0] + r2[2] <= r1[0] or
            r1[1] + r1[3] <= r2[1] or r2[1] + r2[3] <= r1[1])


def pt_in(p, r):
    return r[0] < p[0] < r[0] + r[2] and r[1] < p[1] < r[1] + r[3]


def on_edge(p, r, tol=0.5):
    """点pが矩形rの辺上にあるか（矢印端点の座標整合assert用）"""
    x, y = p
    x0, y0, w, h = r
    on_v = (abs(x - x0) <= tol or abs(x - (x0 + w)) <= tol) and y0 - tol <= y <= y0 + h + tol
    on_h = (abs(y - y0) <= tol or abs(y - (y0 + h)) <= tol) and x0 - tol <= x <= x0 + w + tol
    return on_v or on_h


def no_digits(texts, allow_L=False):
    """ラベル群に数字が含まれない（allow_L=TrueならL01等のレッスン番号・丸数字は許す）"""
    for t in texts:
        s = re.sub(r"L\d\d", "", t) if allow_L else t
        if re.search(r"[0-9０-９]", s):
            return False
    return True


# ===========================================================================
# 図1: L01 §5 (a＋b)(c＋d)の面積図——4区画への分配
# 仕様の正: notes/lesson_01_notes.md §2。記号ラベルのみ・数値なし。
# 辺比 a:b=3:2・c:d=5:3 の非対称固定（特定数値例を想起させない）。
# ===========================================================================
def fig_L01_1():
    # --- パラメータ（notes/lesson_01_notes.md §2 と一致させる） ---
    a_px, b_px = 90, 60          # 縦 a:b = 3:2
    c_px, d_px = 150, 90         # 横 c:d = 5:3
    ox, oy = 70, 50

    ck = Checker()
    ck.ok("分配の恒等式 (a＋b)(c＋d)=ac＋ad＋bc＋bd（代表比 a,b,c,d=3,2,5,3 で検算）",
          (3 + 2) * (5 + 3) == 3 * 5 + 3 * 3 + 2 * 5 + 2 * 3, "40=15＋9＋10＋6")
    ck.ok("辺比 a:b=3:2・c:d=5:3（描画単位で固定）",
          a_px * 2 == b_px * 3 and c_px * 3 == d_px * 5,
          f"a={a_px},b={b_px},c={c_px},d={d_px}")
    ck.ok("寸法整合: 縦=a＋b・横=c＋d の区画和が全体と一致",
          a_px + b_px == 150 and c_px + d_px == 240)

    cv = Canvas(360, 250)
    W_all, H_all = c_px + d_px, a_px + b_px
    cv.rect_px(ox, oy, W_all, H_all, sw=1.6)
    cv.line_px(ox + c_px, oy, ox + c_px, oy + H_all, w=1.1)
    cv.line_px(ox, oy + a_px, ox + W_all, oy + a_px, w=1.1)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    T(ox + c_px / 2, oy - 10, "c", size=FS)
    T(ox + c_px + d_px / 2, oy - 10, "d", size=FS)
    T(ox - 12, oy + a_px / 2 + 4, "a", size=FS, anchor="end")
    T(ox - 12, oy + a_px + b_px / 2 + 4, "b", size=FS, anchor="end")
    T(ox + c_px / 2, oy + a_px / 2 + 4, "ac", size=FS)
    T(ox + c_px + d_px / 2, oy + a_px / 2 + 4, "ad", size=FS)
    T(ox + c_px / 2, oy + a_px + b_px / 2 + 4, "bc", size=FS)
    T(ox + c_px + d_px / 2, oy + a_px + b_px / 2 + 4, "bd", size=FS)
    T(ox + W_all / 2, oy + H_all + 32, "(a＋b)(c＋d)＝ac＋ad＋bc＋bd", size=12,
      weight="bold")
    ck.ok("図中ラベルは記号のみで数値を含まない", no_digits(labels))

    return {"file": "L01_fig1_distributive_area_model.svg", "lesson": "L01", "canvas": cv,
            "title": "(a＋b)(c＋d)の面積図——4区画への分配",
            "intent": "縦a＋b・横c＋dの長方形を4区画に分け、積(a＋b)(c＋d)が4つの項ac・ad・bc・bdに分かれる分配を面で見せる（記号のみ・数値なし。a,b,c,d＞0の場合の構造理解図）",
            "src": "lesson_01.md §5（分配法則の段落の直後）",
            "params": "記号ラベルのみ／辺比a:b=3:2・c:d=5:3の非対称固定（特定の数値例を想起させない）",
            "checks": ck.items,
            "check_tokens": ["6", "9", "−3", "−10"],
            "allow_texts": labels}


# ===========================================================================
# 図2: L02 §2 (ax＋b)(cx＋d)の面積図——交差項2つ
# 仕様の正: notes/lesson_02_notes.md §2。主パネル=記号のみ・
# 副パネル=例題1 (2x＋1)(3x＋4)（本文明示値）。区画の長さは比例尺でない模式図。
# ===========================================================================
def fig_L02_1():
    # --- パラメータ（notes/lesson_02_notes.md §2 と一致させる） ---
    a, b, c, d, xv = 2, 1, 3, 4, 5       # 検算用代表値（例題1の係数・x=5）
    mx, my = 60, 66
    axw, bw, cxh, dh = 150, 60, 110, 55  # 主パネル区画（模式比）
    sx0, sy0 = 360, 66
    w2x, w1, h3x, h4 = 110, 45, 100, 50  # 副パネル区画（模式比）

    ck = Checker()
    ck.ok("公式の恒等式: (ax＋b)(cx＋d)=acx²＋(ad＋bc)x＋bd（a,b,c,d=2,1,3,4・x=−5..5全点）",
          all((a * x + b) * (c * x + d) ==
              a * c * x * x + (a * d + b * c) * x + b * d for x in range(-5, 6)))
    ck.ok("4区画の面積の和=展開式の値（代表値x=5: 11×19=209=150＋40＋15＋4）",
          (a * xv + b) * (c * xv + d) == 209 and
          a * c * xv ** 2 + a * d * xv + b * c * xv + b * d == 209)
    ck.ok("xの項は外どうしad=8と内どうしbc=3の2つの積の和（8＋3=11）",
          a * d == 8 and b * c == 3 and a * d + b * c == 11)
    ck.ok("例題1の4区画: 6x²・8x・3x・4（2x·3x／2x·4／1·3x／1·4）",
          (a * c, a * d, b * c, b * d) == (6, 8, 3, 4))
    ck.ok("区画の座標整合: 主パネル 列和=ax＋b・行和=cx＋d／副パネルも同様",
          axw + bw == 210 and cxh + dh == 165 and w2x + w1 == 155 and h3x + h4 == 150)

    cv = Canvas(560, 304)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    # --- 主パネル（記号のみ）: 交差項2区画を網かけ ---
    cv.rect_px(mx, my, axw + bw, cxh + dh, sw=1.6)
    cv.raw(f'<rect x="{mx + axw}" y="{my}" width="{bw}" height="{cxh}" fill="{SHADE2}"/>')
    cv.raw(f'<rect x="{mx}" y="{my + cxh}" width="{axw}" height="{dh}" fill="{SHADE2}"/>')
    cv.rect_px(mx, my, axw + bw, cxh + dh, sw=1.6)
    cv.line_px(mx + axw, my, mx + axw, my + cxh + dh, w=1.1)
    cv.line_px(mx, my + cxh, mx + axw + bw, my + cxh, w=1.1)
    T(mx + axw / 2, my - 10, "ax", size=FS)
    T(mx + axw + bw / 2, my - 10, "b", size=FS)
    T(mx - 10, my + cxh / 2 + 4, "cx", size=FS, anchor="end")
    T(mx - 10, my + cxh + dh / 2 + 4, "d", size=FS, anchor="end")
    T(mx + axw / 2, my + cxh / 2 + 4, "acx²", size=FS)
    T(mx + axw + bw / 2, my + cxh / 2 + 4, "bcx", size=FS)
    T(mx + axw / 2, my + cxh + dh / 2 + 4, "adx", size=FS)
    T(mx + axw + bw / 2, my + cxh + dh / 2 + 4, "bd", size=FS)
    T(mx + (axw + bw) / 2, my + cxh + dh + 24, "xの項は adx と bcx の2つ",
      size=11.5, weight="bold")

    # --- 副パネル（例題1・本文明示値） ---
    cv.rect_px(sx0, sy0, w2x + w1, h3x + h4, sw=1.6)
    cv.line_px(sx0 + w2x, sy0, sx0 + w2x, sy0 + h3x + h4, w=1.1)
    cv.line_px(sx0, sy0 + h3x, sx0 + w2x + w1, sy0 + h3x, w=1.1)
    T(sx0 + w2x / 2, sy0 - 10, "2x", size=FS)
    T(sx0 + w2x + w1 / 2, sy0 - 10, "1", size=FS)
    T(sx0 - 10, sy0 + h3x / 2 + 4, "3x", size=FS, anchor="end")
    T(sx0 - 10, sy0 + h3x + h4 / 2 + 4, "4", size=FS, anchor="end")
    T(sx0 + w2x / 2, sy0 + h3x / 2 + 4, "6x²", size=FS)
    T(sx0 + w2x + w1 / 2, sy0 + h3x / 2 + 4, "3x", size=FS)
    T(sx0 + w2x / 2, sy0 + h3x + h4 / 2 + 4, "8x", size=FS)
    T(sx0 + w2x + w1 / 2, sy0 + h3x + h4 / 2 + 4, "4", size=FS)
    T(sx0 + (w2x + w1) / 2, sy0 + h3x + h4 + 24, "例題1 (2x＋1)(3x＋4)", size=11.5)

    T(280, 292, "(ax＋b)(cx＋d)＝acx²＋(ad＋bc)x＋bd", size=12.5, weight="bold")

    return {"file": "L02_fig1_area_model_cross_terms.svg", "lesson": "L02", "canvas": cv,
            "title": "(ax＋b)(cx＋d)の面積図——交差項2つ",
            "intent": "xの項が外どうしadxと内どうしbcxの2つの積の和になることを面で見せる。a,b,c,d,x＞0の場合の構造理解図——係数が負の場合は面積では表せず、公式（符号ごとの積）で処理する（本文§3）。区画の長さは比例尺でない模式図",
            "src": "lesson_02.md §2（新公式の提示の直後）",
            "params": "主パネル=記号のみ（交差項adx・bcxを網かけ）／副パネル=例題1 (2x＋1)(3x＋4)の区画6x²・8x・3x・4（本文明示値）",
            "checks": ck.items,
            "check_tokens": ["11", "17", "25", "32", "24", "36", "−16", "−17", "12",
                             "10", "(2x＋3)"],
            "allow_texts": labels}


# ===========================================================================
# 図3: L03 §1 展開⇄因数分解の往復図式
# 仕様の正: notes/lesson_03_notes.md §3。使う式は§1本文例のみ・1パネル・
# テキストと矢印のみ。
# ===========================================================================
def fig_L03_1():
    # --- パラメータ（lesson_03.md §1 と一致させる） ---
    sum_coeffs = [6, 5, 1]                   # x²＋5x＋6（低次→高次）
    f1, f2 = [2, 1], [3, 1]                  # (x＋2)・(x＋3)

    ck = Checker()
    ck.ok("係数一致: (x＋2)(x＋3)の展開係数=(6,5,1)=x²＋5x＋6",
          poly_mul(f1, f2) == sum_coeffs)
    ck.ok("往復が同じ等式（因数分解と展開は逆向きの読み）",
          poly_mul(f2, f1) == sum_coeffs)

    cv = Canvas(640, 150)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    cv.rect_px(30, 56, 240, 44, sw=1.4)
    T(150, 82, "和の形　x²＋5x＋6", size=FS, weight="bold")
    cv.rect_px(370, 56, 240, 44, sw=1.4)
    T(490, 82, "積の形　(x＋2)(x＋3)", size=FS, weight="bold")
    arrow_px(cv, 272, 68, 366, 68)
    T(320, 44, "因数分解（積の形に表す）", size=11.5)
    arrow_px(cv, 368, 88, 274, 88)
    T(320, 126, "展開（検算）", size=11.5)

    return {"file": "L03_fig1_expand_factor_roundtrip.svg", "lesson": "L03", "canvas": cv,
            "title": "展開⇄因数分解の往復図式",
            "intent": "同じ等式を右向きに読めば因数分解（積の形に表す）・左向きに読めば展開（検算）——往復の関係を双方向の矢印で見せる",
            "src": "lesson_03.md §1（因数分解の定義段落の直後）",
            "params": "本文例 x²＋5x＋6=(x＋2)(x＋3) のみ／上矢印=因数分解・下矢印=展開（検算）",
            "checks": ck.items,
            "check_tokens": ["x²＋4x＋3", "x²−25", "6x²＋9x", "4a²b−6ab²",
                             "−x²＋10x−25", "x²＋8x＋16", "x²−49", "x²＋9x＋14",
                             "x²−2x−15", "x²−36", "3x²−12x", "6x²＋4x",
                             "−x²＋4x−4", "x²＋7x＋10", "x²−81"],
            "allow_texts": labels}


# ===========================================================================
# 図4: L04 §1 係数の組の探索（任意図版・採用）
# 仕様の正: notes/lesson_04_notes.md §2。本文§1候補表と同一数値のみ。
# 「たすき掛け」の名称は図中・title・descに書かない（check_tokens_fullで機械担保）。
# ===========================================================================
def fig_L04_1():
    # --- パラメータ（lesson_04.md §1 例題1 と一致させる） ---
    target = [2, 7, 3]                       # 3x²＋7x＋2（低次→高次）
    cand1 = ([1, 1], [2, 3])                 # (x＋1)(3x＋2)
    cand2 = ([2, 1], [1, 3])                 # (x＋2)(3x＋1)

    ck = Checker()
    e1 = poly_mul(*cand1)
    e2 = poly_mul(*cand2)
    ck.ok("候補1 (x＋1)(3x＋2)のxの項は5x（7xと不一致→捨てる）",
          e1 == [2, 5, 3] and e1[1] != target[1])
    ck.ok("候補2 (x＋2)(3x＋1)のxの項は7x（一致→採用）",
          e2 == target and e2[1] == 7)
    ck.ok("分解候補の網羅: 3=1×3・2=1×2または2×1（すべて正の組）",
          1 * 3 == 3 and 1 * 2 == 2 and 2 * 1 == 2)

    cv = Canvas(640, 300)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    T(320, 32, "3x²＋7x＋2", size=15, weight="bold")
    arrow_px(cv, 250, 40, 150, 64, w=1.1, head=5.5)
    arrow_px(cv, 390, 40, 480, 64, w=1.1, head=5.5)
    T(150, 84, "x²の係数 3＝1×3", size=11.5)
    T(480, 84, "定数項 2＝1×2 または 2×1", size=11.5)

    cv.rect_px(40, 108, 190, 40, sw=1.4)
    T(135, 132, "(x＋1)(3x＋2)", size=FS)
    arrow_px(cv, 234, 128, 296, 128)
    T(352, 132, "xの項 5x", size=FS)
    T(475, 132, "✗ 7x と合わない", size=FS)

    cv.rect_px(40, 188, 190, 40, sw=1.4)
    T(135, 212, "(x＋2)(3x＋1)", size=FS)
    arrow_px(cv, 234, 208, 296, 208)
    T(352, 212, "xの項 7x", size=FS)
    T(492, 212, "✓ 7x と一致——採用", size=FS, weight="bold")

    T(320, 274, "3x²＋7x＋2＝(x＋2)(3x＋1)", size=13.5, weight="bold")

    return {"file": "L04_fig1_coefficient_pair_search.svg", "lesson": "L04", "canvas": cv,
            "title": "係数の組の探索——xの項で照合",
            "intent": "x²の係数と定数項の分解から候補の組を作り、展開したときのxの項で照合して採否を決める流れを1枚で見せる（本文§1の候補表と同一数値のみ）",
            "src": "lesson_04.md §1 例題1（候補表の直後）",
            "params": "3x²＋7x＋2／候補 (x＋1)(3x＋2)→5x ✗・(x＋2)(3x＋1)→7x ✓",
            "checks": ck.items,
            "check_tokens": ["2x²＋7x＋3", "3x²−10x＋8", "4x²＋4x−3",
                             "6x²＋x−12", "8x²−20x＋12", "x²＋xy＋2y−4"],
            "check_tokens_full": ["たすき掛け"],
            "allow_texts": labels}


# ===========================================================================
# 図5: L05 §3 実数の地図——入れ子の領域図
# 仕様の正: notes/lesson_05_notes.md §2。集合記号（∈∩∪⊂）不使用厳守・
# 例ラベルは本文例題2で分類済みの 5・−2・0.6・−7/3・√3 のみ（√9は罠の性質上入れない）。
# ===========================================================================
def fig_L05_1():
    # --- パラメータ（notes/lesson_05_notes.md §2 と一致させる） ---
    r_real = (20, 36, 600, 268)
    r_rat = (40, 70, 340, 216)
    r_irr = (410, 70, 190, 216)
    r_int = (60, 130, 220, 140)
    r_nat = (80, 190, 120, 70)
    p5, pm2 = (140, 232), (243, 222)         # 5（自然数内）・−2（整数内・自然数外）
    p06, pm73 = (330, 148), (330, 194)       # 0.6・−7/3（有理数内・整数外）
    ps3 = (505, 188)                         # √3（無理数内）

    ck = Checker()
    ck.ok("入れ子の包含: 自然数枠⊂整数枠⊂有理数枠⊂実数枠（矩形座標で検査）",
          inside(r_nat, r_int) and inside(r_int, r_rat) and inside(r_rat, r_real))
    ck.ok("無理数枠は有理数枠と交わらず、実数枠に含まれる",
          disjoint(r_irr, r_rat) and inside(r_irr, r_real))
    ck.ok("例の配置: 5は自然数枠内／−2は整数枠内かつ自然数枠外",
          pt_in(p5, r_nat) and pt_in(pm2, r_int) and not pt_in(pm2, r_nat))
    ck.ok("例の配置: 0.6・−7/3は有理数枠内かつ整数枠外／√3は無理数枠内",
          pt_in(p06, r_rat) and not pt_in(p06, r_int) and
          pt_in(pm73, r_rat) and not pt_in(pm73, r_int) and pt_in(ps3, r_irr))
    ck.ok("例の分類の検算: 0.6=3/5は有理数・−7/3は整数でない・3は平方数でない（√3の根号は外せない）",
          F(6, 10) == F(3, 5) and F(-7, 3).denominator != 1 and
          math.isqrt(3) ** 2 != 3)

    cv = Canvas(640, 320)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    cv.rect_px(*r_real, sw=1.6)
    cv.rect_px(*r_rat, sw=1.3)
    cv.rect_px(*r_irr, sw=1.3)
    cv.rect_px(*r_int, sw=1.1)
    cv.rect_px(*r_nat, sw=1.1)
    T(32, 58, "実数", size=13, anchor="start", weight="bold")
    T(52, 92, "有理数", size=12, anchor="start", weight="bold")
    T(422, 92, "無理数", size=12, anchor="start", weight="bold")
    T(72, 152, "整数", size=12, anchor="start", weight="bold")
    T(92, 212, "自然数", size=12, anchor="start", weight="bold")
    T(p5[0], p5[1] + 4, "5", size=FS)
    T(pm2[0], pm2[1] + 4, "−2", size=FS)
    T(p06[0], p06[1] + 4, "0.6", size=FS)
    T(pm73[0], pm73[1] + 4, "−7/3", size=FS)
    T(ps3[0], ps3[1] + 4, "√3", size=FS)

    return {"file": "L05_fig1_real_number_map.svg", "lesson": "L05", "canvas": cv,
            "title": "実数の地図（入れ子の領域図）",
            "intent": "実数の枠の中に有理数・無理数の2領域、有理数の中に整数、整数の中に自然数の入れ子を描き、既習の数がすべて1枚の地図に載ることを見せる（集合記号は使わず、領域名と例の数のみ）",
            "src": "lesson_05.md §3（実数の定義段落の直後）",
            "params": "例ラベルは本文例題2の 5・−2・0.6・−7/3・√3 のみ（√9は「根号が外せる」罠の性質上入れない）",
            "checks": ck.items,
            "check_tokens": ["√9", "√10", "√36", "−√4", "0.7", "−5/2"],
            "allow_texts": labels}


# ===========================================================================
# 図6: L05 §4 数直線上の√2——挟み込み
# 仕様の正: notes/lesson_05_notes.md §2。表示範囲1.3〜1.6・ラベルは1.4・1.5・√2のみ。
# 端点●○描法は使わない（解範囲図でないため——●○はL07以降で使用）。
# ===========================================================================
def fig_L05_2():
    # --- パラメータ（lesson_05.md §4 と一致させる） ---
    lo, hi = 1.3, 1.6
    s2 = math.sqrt(2)
    X0, SPAN = 70, 480
    x_px = lambda v: X0 + (v - lo) / (hi - lo) * SPAN
    Y = 95

    ck = Checker()
    ck.ok("挟み込み 1.4<√2<1.5（分数の2乗の厳密比較: 196/100<2<225/100）",
          F(14, 10) ** 2 < 2 < F(15, 10) ** 2)
    ck.ok("√2の描画位置が1.4と1.5の目盛りの間に入る",
          x_px(1.4) < x_px(s2) < x_px(1.5),
          f"x(1.4)={x_px(1.4):.1f} < x(√2)={x_px(s2):.1f} < x(1.5)={x_px(1.5):.1f}")
    ck.ok("値→x座標の変換が線形（等間隔目盛り）",
          abs((x_px(1.5) - x_px(1.4)) - (x_px(1.6) - x_px(1.5))) < 1e-9)

    cv = Canvas(620, 150)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    # 挟み込みの帯（1.4〜1.5）
    cv.raw(f'<rect x="{x_px(1.4):.1f}" y="{Y - 24:.1f}" '
           f'width="{x_px(1.5) - x_px(1.4):.1f}" height="24" fill="{SHADE}"/>')
    arrow_px(cv, 58, Y, 566, Y, w=1.2)
    for v in (1.3, 1.4, 1.5, 1.6):
        tick_px(cv, x_px(v), Y, half=5)
    T(x_px(1.4), Y + 22, "1.4", size=FS_NUM)
    T(x_px(1.5), Y + 22, "1.5", size=FS_NUM)
    cv.raw(f'<circle cx="{x_px(s2):.1f}" cy="{Y}" r="3.0" fill="#000"/>')
    cv.line_px(x_px(s2), Y - 26, x_px(s2), Y - 8, w=AUX_W)
    T(x_px(s2), Y - 34, "√2", size=FS, weight="bold")

    return {"file": "L05_fig2_sqrt2_number_line.svg", "lesson": "L05", "canvas": cv,
            "title": "数直線上の√2——挟み込み",
            "intent": "1.4と1.5の目盛りの間の帯の中に√2の点を打ち、√2が数直線上の決まった1点であること（挟み込みでいくらでも狭く追い込めること）を見せる",
            "src": "lesson_05.md §4（挟み込み2行の直後）",
            "params": "表示範囲1.3〜1.6／ラベルは1.4・1.5・√2のみ／点位置=√2（プログラム内でmath.sqrt(2)から線形変換・決定的）／端点●○描法は不使用（解範囲図でないため）",
            "checks": ck.items,
            "check_tokens": ["√7", "−√2", "2.6", "2.7", "2.2", "2.3", "1.41", "1.42"],
            "allow_texts": labels}


# ===========================================================================
# 図7: L06 §4 反例の可視化——√9＋√16 と √(9＋16) の帯
# 仕様の正: notes/lesson_06_notes.md §2。数値ラベルは3・4・7・5・9・16・25のみ
# （本文例題3明示値）。帯のため●○不使用。
# ===========================================================================
def fig_L06_1():
    # --- パラメータ（lesson_06.md §4 例題3 と一致させる） ---
    UNIT = 57
    x_px = lambda v: 90 + v * UNIT
    y_up, y_lo, y_ax = 48, 108, 170
    BH = 22

    ck = Checker()
    ck.ok("左辺の検算: √9＋√16=3＋4=7",
          math.isqrt(9) == 3 and math.isqrt(16) == 4 and 3 + 4 == 7)
    ck.ok("右辺の検算: √(9＋16)=√25=5", 9 + 16 == 25 and math.isqrt(25) == 5)
    ck.ok("反例の成立: 7≠5", 7 != 5)
    ck.ok("帯の描画長=値×単位長（上段3＋4=7目盛り・下段5目盛り・上段が長い）",
          x_px(3) - x_px(0) == 3 * UNIT and x_px(7) - x_px(3) == 4 * UNIT and
          x_px(7) - x_px(0) == 7 * UNIT and x_px(5) - x_px(0) == 5 * UNIT and
          7 * UNIT > 5 * UNIT)

    cv = Canvas(640, 230)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    # 上段: √9の帯＋√16の帯（継ぎ足し）
    cv.rect_px(x_px(0), y_up, 3 * UNIT, BH, fill=SHADE2, sw=1.2)
    cv.rect_px(x_px(3), y_up, 4 * UNIT, BH, fill=SHADE, sw=1.2)
    T(82, y_up + BH / 2 + 4, "√9＋√16", size=12, anchor="end")
    T(x_px(1.5), y_up + BH / 2 + 4, "√9＝3", size=FS_NUM)
    T(x_px(5), y_up + BH / 2 + 4, "√16＝4", size=FS_NUM)
    T(x_px(7) + 8, y_up + BH / 2 + 4, "＝7", size=FS, anchor="start", weight="bold")
    # 下段: √25の帯
    cv.rect_px(x_px(0), y_lo, 5 * UNIT, BH, fill=SHADE, sw=1.2)
    T(82, y_lo + BH / 2 + 4, "√(9＋16)", size=12, anchor="end")
    T(x_px(2.5), y_lo + BH / 2 + 4, "√25＝5", size=FS_NUM)
    T(x_px(5) + 8, y_lo + BH / 2 + 4, "＝5", size=FS, anchor="start", weight="bold")
    # 目盛り軸（0〜8・無ラベル）と右端の対応の破線
    arrow_px(cv, 80, y_ax, 556, y_ax, w=1.2)
    for v in range(0, 9):
        tick_px(cv, x_px(v), y_ax)
    cv.line_px(x_px(7), y_up + BH, x_px(7), y_ax, w=AUX_W, dash=DASH)
    cv.line_px(x_px(5), y_lo + BH, x_px(5), y_ax, w=AUX_W, dash=DASH)
    T(320, 208, "右端がそろわない——√9＋√16 ≠ √(9＋16)", size=FS_NUM, weight="bold")

    return {"file": "L06_fig1_sqrt_sum_counterexample.svg", "lesson": "L06", "canvas": cv,
            "title": "√9＋√16≠√(9＋16)——反例の長さ比較",
            "intent": "√9＋√16=3＋4=7の帯（上段・継ぎ足し）と√(9＋16)=√25=5の帯（下段）を同じ目盛りの上で比べ、右端がそろわないこと（和の√は√の和にならない反例）を長さで見せる",
            "src": "lesson_06.md §4 例題3（解の直後）",
            "params": "数値ラベルは3・4・7・5・9・16・25のみ（本文例題3明示値）／目盛り0〜8は無ラベルの刻み線／帯のため●○不使用",
            "checks": ck.items,
            "check_tokens": ["5√3", "7√2", "8−4√3", "√5−1", "100", "36"],
            "allow_texts": labels}


# ===========================================================================
# 図8: L07 §1 1/√2と√2/2が数直線上の同じ点
# 仕様の正: notes/lesson_07_notes.md §2（注: 図版番号はマップ候補から本文登場順に
# 入れ替え済み——fig1=有理化・fig2=絶対値。notesを正とする）。
# ===========================================================================
def fig_L07_1():
    # --- パラメータ（notes/lesson_07_notes.md §2 と一致させる） ---
    P_VAL = 0.70710678                       # √2/2 の固定小数（決定的）
    X0, SPAN, Y = 70, 480, 110
    x_px = lambda v: X0 + v * SPAN
    P = (x_px(P_VAL), Y)

    ck = Checker()
    ck.ok("点の値の照合: (0.70710678)²=1/2（精度1e−6）",
          abs(P_VAL ** 2 - 0.5) < 1e-6, f"差={abs(P_VAL ** 2 - 0.5):.2e}")
    ck.ok("点の位置が0と1の目盛りの間", x_px(0) < P[0] < x_px(1))
    lead1_end = (P[0] - 4, Y - 6)
    lead2_end = (P[0] + 4, Y + 6)
    ck.ok("引き出し線2本が同一点を指す（両端点とも点Pから同一オフセットで算出）",
          abs((lead1_end[0] + lead2_end[0]) / 2 - P[0]) < 1e-9 and
          abs((lead1_end[1] + lead2_end[1]) / 2 - Y) < 1e-9)

    cv = Canvas(620, 190)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    arrow_px(cv, 58, Y, 566, Y, w=1.2)
    for v in (0, 1):
        tick_px(cv, x_px(v), Y, half=5)
    T(x_px(0), Y + 22, "0", size=FS_NUM)
    T(x_px(1), Y + 22, "1", size=FS_NUM)
    closed_pt(cv, *P)
    T(200, 45, "1/√2", size=FS, weight="bold")
    arrow_px(cv, 213, 52, *lead1_end, w=1.1, head=5.5)
    T(480, 172, "√2/2", size=FS, weight="bold")
    arrow_px(cv, 466, 162, *lead2_end, w=1.1, head=5.5)
    T(P[0] - 16, Y + 28, "同じ1つの点", size=FS_NUM, anchor="end")

    return {"file": "L07_fig1_rationalization_same_point.svg", "lesson": "L07",
            "canvas": cv,
            "title": "1/√2＝√2/2——数直線上の同じ点",
            "intent": "1/√2と√2/2の2つの引き出し線が数直線上の同一の点を指す——有理化は数を動かさない（同じ点の別名を作るだけ）ことの可視化",
            "src": "lesson_07.md §1 末尾（「値は同じ」段落の直後）",
            "params": "0〜1の数直線／点位置0.70710678固定（√2/2）／ラベルは0・1・1/√2・√2/2のみ・小数ラベルなし",
            "checks": ck.items,
            "check_tokens": ["√7/7", "2√5", "√3/2", "√10/2", "√5＋1", "5＋2√6",
                             "√6−2", "√2−1", "0.41", "0.707", "0.75"],
            "allow_texts": labels}


# ===========================================================================
# 図9: L07 §4 |x|=5の2点——原点から左右へ距離5
# 仕様の正: notes/lesson_07_notes.md §2。ラベルは−5・0・5・「距離5」のみ。
# ●の描法パラメータはL08_fig1と共通（closed_pt）。端±8にはラベルを置かない。
# ===========================================================================
def fig_L07_2():
    # --- パラメータ（lesson_07.md §4 例題3(3) と一致させる） ---
    UNIT, Y = 34, 100
    x_px = lambda v: 310 + v * UNIT
    Y_AR = 78

    ck = Checker()
    ck.ok("2点が原点から等距離（±5×単位長）",
          x_px(5) - x_px(0) == 5 * UNIT and x_px(0) - x_px(-5) == 5 * UNIT)
    ck.ok("距離矢印2本の長さが等しい",
          abs(x_px(5) - x_px(0)) == abs(x_px(-5) - x_px(0)))
    ck.ok("|5|=5・|−5|=5（絶対値の検算）", abs(5) == 5 and abs(-5) == 5)

    cv = Canvas(620, 160)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    arrow_px(cv, x_px(-8) - 10, Y, x_px(8) + 14, Y, w=1.2)
    arrow_px(cv, x_px(8) + 10, Y, x_px(-8) - 14, Y, w=1.2)
    for v in range(-8, 9):
        tick_px(cv, x_px(v), Y)
    T(x_px(-5), Y + 22, "−5", size=FS_NUM)
    T(x_px(0), Y + 22, "0", size=FS_NUM)
    T(x_px(5), Y + 22, "5", size=FS_NUM)
    closed_pt(cv, x_px(-5), Y)
    closed_pt(cv, x_px(5), Y)
    # 原点から左右への距離矢印（上段）
    arrow_px(cv, x_px(0), Y_AR, x_px(-5), Y_AR, w=1.3)
    arrow_px(cv, x_px(0), Y_AR, x_px(5), Y_AR, w=1.3)
    cv.line_px(x_px(0), Y_AR, x_px(0), Y - 5, w=AUX_W, dash=DASH)
    cv.line_px(x_px(-5), Y_AR, x_px(-5), Y - 6, w=AUX_W, dash=DASH)
    cv.line_px(x_px(5), Y_AR, x_px(5), Y - 6, w=AUX_W, dash=DASH)
    T(x_px(-2.5), Y_AR - 10, "距離5", size=FS_NUM, weight="bold")
    T(x_px(2.5), Y_AR - 10, "距離5", size=FS_NUM, weight="bold")

    return {"file": "L07_fig2_absolute_value_distance.svg", "lesson": "L07",
            "canvas": cv,
            "title": "|x|＝5——原点から距離5の2点",
            "intent": "原点からの距離が5の数は左右に1つずつ——|x|=5の解が2点あることを距離矢印つき数直線で見せる",
            "src": "lesson_07.md §4 例題3（解答の直後）",
            "params": "数直線−8〜8（1刻み・端±8は無ラベル）／ラベルは−5・0・5・「距離5」のみ／●はL08_fig1と共通の描画パラメータ",
            "checks": ck.items,
            "check_tokens": ["±8", "−8", "8"],
            "allow_texts": labels}


# ===========================================================================
# 図10: L08 §1 不等式の解＝数直線上の範囲（x>3）
# 仕様の正: notes/lesson_08_notes.md §3。図中数値は3と目盛のみ・●○凡例つき。
# 解の範囲の描法は二次関数L12_fig1（数直線3段）と共通の様式。
# ===========================================================================
def fig_L08_1():
    # --- パラメータ（lesson_08.md §1 例題1 と一致させる） ---
    UNIT, Y = 80, 95
    x_px = lambda v: 70 + v * UNIT
    ray_x0 = x_px(3) + DOT_R_END

    ck = Checker()
    ck.ok("○の中心x座標=目盛3の位置", x_px(3) == 70 + 240)
    ck.ok("範囲線の始点=○の右端・終点は数直線の右端の手前（矢印つき）",
          ray_x0 == x_px(3) + DOT_R_END and ray_x0 < 566 < 585)
    ck.ok("境界の検算: x=3で左辺3x−2=7（7>7は不成立——3は解でない）",
          3 * 3 - 2 == 7 and not (7 > 7))
    ck.ok("範囲の中の検算: x=4で10>7・x=3.1で7.3>7（いずれも成立——本文の表と一致）",
          3 * 4 - 2 == 10 > 7 and 3 * 3.1 - 2 > 7)

    cv = Canvas(620, 190)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    arrow_px(cv, 58, Y, 585, Y, w=1.2)
    for v in range(0, 7):
        tick_px(cv, x_px(v), Y)
    T(x_px(3), Y + 22, "3", size=FS_NUM)
    arrow_px(cv, ray_x0, Y, 566, Y, w=BOLD_W, head=9.0)
    open_pt(cv, x_px(3), Y)
    T(x_px(4.5), Y - 18, "x＞3", size=FS, weight="bold")
    labels += legend_endpoints(cv, 150, 350, 155)

    return {"file": "L08_fig1_solution_range_number_line.svg", "lesson": "L08",
            "canvas": cv,
            "title": "不等式の解＝数直線上の範囲（x＞3）",
            "intent": "解x>3を「3に○・右へのびる太線」としてかく——解が値の集まり（数直線上の範囲）であることと、●=含む/○=含まないの規約を1枚で固定する",
            "src": "lesson_08.md §1（●○規約の段落の直後）",
            "params": "数直線0〜6（数値ラベルは3のみ）／3に○・右向き太線＋矢印／●○凡例つき（L09_fig1・二次関数L12_fig1と共通描法）",
            "checks": ck.items,
            "check_tokens": ["4", "−3", "−7"],
            "allow_texts": labels}


# ===========================================================================
# 図11: L08 §2 性質④——2<3の両辺に−1を掛けると−2>−3（0中心の折り返し）
# 仕様の正: notes/lesson_08_notes.md §3。ラベルは2・3・−2・−3・0のみ。
# ===========================================================================
def fig_L08_2():
    # --- パラメータ（lesson_08.md §2 と一致させる） ---
    UNIT, Y = 60, 140
    x_px = lambda v: 310 + v * UNIT

    ck = Checker()
    ck.ok("掛け算の検算: 2×(−1)=−2・3×(−1)=−3", 2 * (-1) == -2 and 3 * (-1) == -3)
    ck.ok("大小の反転: 2<3 だが −2>−3", 2 < 3 and -2 > -3)
    ck.ok("各点の描画x座標=値×スケール（0中心に対称）",
          x_px(2) - x_px(0) == 2 * UNIT and x_px(0) - x_px(-2) == 2 * UNIT and
          x_px(3) - x_px(0) == 3 * UNIT and x_px(0) - x_px(-3) == 3 * UNIT)
    ck.ok("折り返し矢印の端点が両点の座標に一致（2→−2・3→−3）",
          x_px(2) == 310 + 120 and x_px(-2) == 310 - 120 and
          x_px(3) == 310 + 180 and x_px(-3) == 310 - 180)

    cv = Canvas(620, 210)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    arrow_px(cv, x_px(-4) - 10, Y, x_px(4) + 14, Y, w=1.2)
    arrow_px(cv, x_px(4) + 10, Y, x_px(-4) - 14, Y, w=1.2)
    for v in range(-4, 5):
        tick_px(cv, x_px(v), Y)
    for v, lab in ((-3, "−3"), (-2, "−2"), (0, "0"), (2, "2"), (3, "3")):
        T(x_px(v), Y + 22, lab, size=FS_NUM)
    for v in (2, 3, -2, -3):
        cv.raw(f'<circle cx="{x_px(v):.1f}" cy="{Y}" r="3.0" fill="#000"/>')
    # 0を中心の折り返し（弧状矢印）: 2→−2（低い弧）・3→−3（高い弧）
    arc_arrow(cv, x_px(2), Y - 8, x_px(-2), Y - 8, x_px(0), 66, w=1.3)
    arc_arrow(cv, x_px(3), Y - 8, x_px(-3), Y - 8, x_px(0), 30, w=1.3)
    T(310, 196, "0 を中心に折り返すと左右が入れかわる", size=FS_NUM, weight="bold")

    return {"file": "L08_fig2_multiply_negative_reflection.svg", "lesson": "L08",
            "canvas": cv,
            "title": "負の数を掛けると大小が入れかわる（0中心の折り返し）",
            "intent": "2<3の両辺に−1を掛けると−2>−3——0を中心の折り返しで、右にあった3の行き先−3が左へ来る（大小の入れかわり）を弧状矢印で見せる",
            "src": "lesson_08.md §2（2<3→−2>−3の段落の直後）",
            "params": "数直線−4〜4／ラベルは2・3・−2・−3・0のみ／弧状矢印2→−2・3→−3",
            "checks": ck.items,
            "check_tokens": ["12", "−18"],
            "allow_texts": labels}


# ===========================================================================
# 図12: L09 §2 連立不等式の共通部分——数直線3段
# 仕様の正: notes/lesson_09_notes.md §3。二次関数L12_fig1と同型の3段描法・
# 数値ラベルは−1と6のみ（練習の答えの端点−3・3・−2・2・5と分離設計済み）。
# ===========================================================================
def fig_L09_1():
    # --- パラメータ（lesson_09.md §2 例題1 と一致させる） ---
    UNIT = 40
    x_px = lambda v: 214 + (v + 2) * UNIT    # 表示範囲 −2〜7
    rows = [("① x＜6", 56), ("② x≧−1", 118), ("共通部分 −1≦x＜6", 180)]

    ck = Checker()
    ck.ok("①の解の検算: x=6で3x−4=14=x＋8（等号→<は不成立・6は含まない○）／x=5で11<13成立",
          3 * 6 - 4 == 6 + 8 and 3 * 5 - 4 < 5 + 8)
    ck.ok("②の解の検算: x=−1で両辺3（≧の等号成立——−1は含む●）",
          2 * (-1) + 5 == (-1) + 4 == 3)
    ck.ok("共通部分の検算（本文と同じ3点）: 中x=0は両方成立・右外x=7は①不成立・左外x=−2は②不成立",
          (3 * 0 - 4 < 0 + 8 and 2 * 0 + 5 >= 0 + 4) and
          not (3 * 7 - 4 < 7 + 8) and not (2 * (-2) + 5 >= (-2) + 4))
    ck.ok("○の中心x座標=目盛6の位置（上段・下段）／●の中心=目盛−1の位置（中段・下段）",
          x_px(6) == 214 + 320 and x_px(-1) == 214 + 40)
    ck.ok("下段の線分の端点=●（−1）と○（6）の座標", x_px(6) - x_px(-1) == 7 * UNIT)
    ck.ok("3段の同一値の目盛x座標が一致（変換が行に依存しない）",
          all(x_px(v) == 214 + (v + 2) * UNIT for v in range(-2, 8)))

    cv = Canvas(660, 264)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    # 端点の対応を見せる縦の破線（−1・6）——3段を貫く
    for v in (-1, 6):
        cv.line_px(x_px(v), rows[0][1] - 16, x_px(v), rows[2][1] + 6,
                   w=AUX_W, dash=DASH)
    for label, y in rows:
        T(206, y + 4, label, size=12, anchor="end")
        arrow_px(cv, 210, y, 590, y, w=1.2)
        arrow_px(cv, 594, y, 206, y, w=1.2)
        for v in range(-2, 8):
            tick_px(cv, x_px(v), y, half=3)
        # 破線ガイドと重ならないよう左へ逃がす（二次関数L12_fig1と同じ描法）
        T(x_px(-1) - 6, y + 17, "−1", size=FS_NUM, anchor="end")
        T(x_px(6) - 6, y + 17, "6", size=FS_NUM, anchor="end")
    # 上段: x<6（6に○・左向き太線）
    y = rows[0][1]
    arrow_px(cv, x_px(6), y, 228, y, w=BOLD_W, head=9.0)
    open_pt(cv, x_px(6), y)
    # 中段: x≧−1（−1に●・右向き太線）
    y = rows[1][1]
    arrow_px(cv, x_px(-1), y, 572, y, w=BOLD_W, head=9.0)
    closed_pt(cv, x_px(-1), y)
    # 下段: 共通部分 −1≦x<6（−1に●・6に○の線分）
    y = rows[2][1]
    cv.line_px(x_px(-1), y, x_px(6), y, w=BOLD_W)
    closed_pt(cv, x_px(-1), y)
    open_pt(cv, x_px(6), y)
    labels += legend_endpoints(cv, 214, 400, 222)
    T(330, 252, "上のふた段の両方に入る部分が、いちばん下の共通部分", size=FS_NUM,
      weight="bold")

    return {"file": "L09_fig1_system_common_part_number_line.svg", "lesson": "L09",
            "canvas": cv,
            "title": "連立不等式——数直線3段で共通部分をとる",
            "intent": "上段=①の解x<6（○）・中段=②の解x≧−1（●）・下段=共通部分−1≦x<6を縦の破線ガイドでそろえ、上2段の重なりが下段に落ちる対応を見せる（二次関数L12_fig1と同型の3段描法）",
            "src": "lesson_09.md §2 例題1（解と端点確認の直後）",
            "params": "数値ラベルは−1と6のみ（その他の目盛は無ラベル）／破線ガイドx=−1,6／●○はL08_fig1と共通描法・凡例つき",
            "checks": ck.items,
            "check_tokens": ["−3", "−2", "2", "3", "5"],
            "allow_texts": labels}


# ===========================================================================
# 図13: L10 §2 2段階翻訳の流れ図
# 仕様の正: notes/lesson_10_notes.md §3。5ボックス・矢印4本・数値ラベルなし。
# 概念フロー図のため●○規約の対象外。
# ===========================================================================
def fig_L10_1():
    # --- パラメータ（lesson_10.md §2 の箇条書きと一致させる） ---
    boxes = [(20, 55, 130, 44, "事象（文章）"),
             (200, 55, 90, 44, "図・表"),
             (340, 55, 90, 44, "不等式"),
             (480, 55, 190, 44, "解（数直線上の範囲）"),
             (720, 55, 170, 44, "事象に戻して答える")]
    arrow_labels = ["第1段", "第2段", None, "文脈の条件で絞る"]

    ck = Checker()
    gaps = [boxes[i + 1][0] - (boxes[i][0] + boxes[i][2]) for i in range(4)]
    ck.ok("ボックス5個・矢印4本（個数の整合）",
          len(boxes) == 5 and len(arrow_labels) == 4)
    ck.ok("ボックスは重ならず等間隔（間隔50px×4）",
          gaps == [50, 50, 50, 50] and
          all(boxes[i][0] + boxes[i][2] < boxes[i + 1][0] for i in range(4)))
    ck.ok("矢印の端点=隣り合うボックスの辺（始点=左箱の右端・終点=右箱の左端・同じ高さ）",
          all(boxes[i][1] == boxes[0][1] and boxes[i][3] == boxes[0][3]
              for i in range(5)))

    cv = Canvas(910, 150)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    yc = boxes[0][1] + boxes[0][3] / 2
    for (x, y, w, h, lab) in boxes:
        cv.rect_px(x, y, w, h, sw=1.4)
        T(x + w / 2, y + h / 2 + 4.5, lab, size=12, weight="bold")
    for i, alab in enumerate(arrow_labels):
        x1 = boxes[i][0] + boxes[i][2]
        x2 = boxes[i + 1][0]
        arrow_px(cv, x1, yc, x2, yc)
        # 端点座標の整合をここでassert（描いた矢印そのもの）
        assert x1 == boxes[i][0] + boxes[i][2] and x2 == boxes[i + 1][0]
        if alab:
            T((x1 + x2) / 2, 44, alab, size=11)
    ck.ok("矢印4本を隣接ボックス間にのみ描画（描画時の座標assert通過）", True)

    return {"file": "L10_fig1_two_step_translation.svg", "lesson": "L10", "canvas": cv,
            "title": "2段階翻訳の流れ図",
            "intent": "文章から一気に式へ行かず、あいだに図・表を1枚はさむ——事象（文章）→図・表→不等式→解（数直線上の範囲）→事象に戻して答える、の5ステップの流れを見せる",
            "src": "lesson_10.md §2（2段階の箇条書きの直後）",
            "params": "5ボックス・矢印4本／矢印ラベル=第1段・第2段・文脈の条件で絞る／数値ラベルなし（概念フロー図——●○規約の対象外）",
            "checks": ck.items,
            "check_tokens": [],
            "allow_texts": labels}


# ===========================================================================
# 図14: L10 §3 例題2の解x>10の数直線（任意図版・採用）
# 仕様の正: notes/lesson_10_notes.md §3。数値は10・11と目盛のみ・
# 問3の答え（20・21）は載せない。○描法はL08_fig1と共通。
# ===========================================================================
def fig_L10_2():
    # --- パラメータ（lesson_10.md §3 例題2 と一致させる） ---
    UNIT, Y = 80, 100
    x_px = lambda v: 70 + (v - 8) * UNIT     # 表示範囲 8〜14
    ray_x0 = x_px(10) + DOT_R_END

    ck = Checker()
    ck.ok("解の検算: 3x>40−x ⟺ 4x>40 ⟺ x>10（x=11で33>29成立・x=10で30>30不成立）",
          3 * 11 > 40 - 11 and not (3 * 10 > 40 - 10))
    ck.ok("範囲内の最小の自然数=11（10は含まない○）", math.floor(10) + 1 == 11)
    ck.ok("○の中心x座標=目盛10の位置・範囲線の始点=○の右端",
          x_px(10) == 70 + 160 and ray_x0 == x_px(10) + DOT_R_END)
    ck.ok("11の点は○より右・範囲線の内側", x_px(10) < x_px(11) < 566)

    cv = Canvas(620, 170)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    arrow_px(cv, 58, Y, 585, Y, w=1.2)
    for v in range(8, 15):
        tick_px(cv, x_px(v), Y)
    T(x_px(10), Y + 22, "10", size=FS_NUM)
    T(x_px(11), Y + 22, "11", size=FS_NUM)
    arrow_px(cv, ray_x0, Y, 566, Y, w=BOLD_W, head=9.0)
    open_pt(cv, x_px(10), Y)
    closed_pt(cv, x_px(11), Y)
    cv.line_px(x_px(11), Y - 34, x_px(11), Y - 8, w=AUX_W)
    T(x_px(11), Y - 42, "最低票数", size=FS_NUM, weight="bold")
    T(x_px(13), Y - 18, "x＞10", size=FS, weight="bold")

    return {"file": "L10_fig2_election_votes_number_line.svg", "lesson": "L10",
            "canvas": cv,
            "title": "例題2の解x＞10と最低票数11",
            "intent": "不等式の解x>10（10に○・右へのびる範囲）と、その中で最小の自然数11——「解の範囲」から「文脈の答え」を拾う出口の1歩を数直線で見せる",
            "src": "lesson_10.md §3（検算段落の直後）",
            "params": "数直線8〜14（数値ラベルは10・11のみ）／10に○・右向き太線／11に点と「最低票数」ラベル／○はL08_fig1と共通描法",
            "checks": ck.items,
            "check_tokens": ["20", "21", "16/3"],
            "allow_texts": labels}


# ===========================================================================
# 図15: L11 §1 単元マップ
# 仕様の正: notes/lesson_11_notes.md §3。文字ラベルのみで数値なし
# （レッスン番号L01等と丸数字①は可）。枠5個＋矢印端点の座標整合assert。
# ===========================================================================
def fig_L11_1():
    # --- パラメータ（lesson_11.md §1 の3枠組みと一致させる） ---
    b_shiki = (200, 30, 180, 56)
    b_kazu = (40, 190, 180, 56)
    b_futo = (360, 190, 180, 56)
    b_set = (620, 60, 170, 48)
    b_quad = (620, 210, 170, 48)
    all_boxes = [b_shiki, b_kazu, b_futo, b_set, b_quad]
    arrows = [((240, 86), (150, 190)),       # 式→数
              ((220, 208), (360, 208)),      # 数→不等式
              ((360, 232), (220, 232)),      # 不等式→数
              ((350, 86), (460, 190)),       # 式⇄不等式（両向き）
              ((460, 190), (350, 86)),
              ((500, 190), (620, 95)),       # →集合と命題
              ((540, 228), (620, 228)),      # →二次関数
              ((330, 86), (620, 214))]       # 式→二次関数（因数分解を二次方程式へ）
    a_boxes = [(b_shiki, b_kazu), (b_kazu, b_futo), (b_futo, b_kazu),
               (b_shiki, b_futo), (b_futo, b_shiki), (b_futo, b_set),
               (b_futo, b_quad), (b_shiki, b_quad)]

    ck = Checker()
    ck.ok("枠5個が互いに重ならない",
          all(disjoint(all_boxes[i], all_boxes[j])
              for i in range(5) for j in range(i + 1, 5)))
    ck.ok("矢印8本の始点・終点がそれぞれ対応する枠の辺上にある",
          all(on_edge(p1, ba) and on_edge(p2, bb)
              for (p1, p2), (ba, bb) in zip(arrows, a_boxes)))
    ck.ok("後続単元2枠への矢印: 集合と命題へ1本・二次関数へ2本（不等式から・式から）",
          sum(1 for _, bb in a_boxes if bb is b_set) == 1 and
          sum(1 for _, bb in a_boxes if bb is b_quad) == 2)

    cv = Canvas(820, 310)
    labels = []

    def T(x, y, s, **kw):
        labels.append(s)
        cv.text_px(x, y, s, **kw)

    def unit_box(b, main, sub=None, dash=None):
        cv.rect_px(*b, dash=dash)
        cx = b[0] + b[2] / 2
        if sub:
            T(cx, b[1] + 24, main, size=13, weight="bold")
            T(cx, b[1] + 44, sub, size=10)
        else:
            T(cx, b[1] + b[3] / 2 + 4.5, main, size=13, weight="bold")

    unit_box(b_shiki, "式　L01〜L04", "新公式ひとつ＋見方の拡張")
    unit_box(b_kazu, "数　L05〜L07", "実数の地図・有理化")
    unit_box(b_futo, "不等式　L08〜L10", "解く——解＝数直線上の範囲")
    unit_box(b_set, "集合と命題", dash=DASH)
    unit_box(b_quad, "二次関数", dash=DASH)
    T(705, 40, "この先の単元", size=11)

    for (p1, p2) in arrows:
        arrow_px(cv, p1[0], p1[1], p2[0], p2[1], w=1.3)
    T(188, 136, "乗法公式を根号計算へ（L06）", size=10.5, anchor="end")
    T(290, 180, "数直線の上で解を読む（L08）", size=10.5)
    T(290, 262, "性質①が見積りを支える（L11）", size=10.5)
    T(410, 124, "一次方程式との対比（L08）", size=10.5, anchor="start")
    T(612, 196, "因数分解を二次方程式・二次不等式へ（L03）", size=10.5, anchor="end")
    ck.ok("図中ラベルはレッスン番号（L01等）と丸数字以外に数字を含まない",
          no_digits([t.replace("①", "") for t in labels], allow_L=True))

    return {"file": "L11_fig1_unit_map.svg", "lesson": "L11", "canvas": cv,
            "title": "単元マップ——式・数・不等式と次の単元",
            "intent": "式L01〜L04・数L05〜L07・不等式L08〜L10の3枠が素材と道具をやり取りする相互の矢印（乗法公式→根号計算／数直線で解を読む／性質①が見積りを支える／一次方程式との対比）と、後続単元（集合と命題・二次関数）への接続を1枚で見せる。式（因数分解）から二次関数（二次方程式・二次不等式）への接続も矢印で示す",
            "src": "lesson_11.md §1（3枠組みの箇条書きの直後）",
            "params": "文字ラベルのみ・数値なし（レッスン番号L01〜L10と丸数字①のみ）／枠5個・矢印8本（式⇄不等式は両向き2本・式→二次関数を含む）",
            "checks": ck.items,
            "check_tokens": [],
            "allow_texts": labels}


# ===========================================================================
# main: 検査器の陽性対照 → 生成 → SVG技術検査（XML/viewBox/self-contained）
#       → 答え漏れ検査（許可リスト完全一致＋禁止文字列） → FIGURE_MANIFEST.md
# ===========================================================================
FIGS = [fig_L01_1,
        fig_L02_1,
        fig_L03_1,
        fig_L04_1,
        fig_L05_1, fig_L05_2,
        fig_L06_1,
        fig_L07_1, fig_L07_2,
        fig_L08_1, fig_L08_2,
        fig_L09_1,
        fig_L10_1, fig_L10_2,
        fig_L11_1]

TEXT_RE = re.compile(r"<text[^>]*>(.*?)</text>", re.S)


def svg_texts(src):
    """SVG本文から<text>の内容を抽出（エスケープを戻す）"""
    return [unescape(m) for m in TEXT_RE.findall(src)]


def ban_hits(texts, bans):
    """禁止文字列の検出（改行連結——ラベル境界をまたぐ偽陽性を防ぐ）"""
    joined = "\n".join(texts)
    return [b for b in bans if b in joined]


def gate_self_test():
    """答え漏れ検査器の陽性対照——検出できることを毎回実証してから本走査に入る"""
    sample = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">'
              '<text x="1" y="1">21</text><text x="2" y="2">x&lt;6</text></svg>')
    ts = svg_texts(sample)
    assert ts == ["21", "x<6"], f"検査器の抽出が壊れている: {ts}"
    assert ban_hits(ts, ["21"]) == ["21"], "陽性対照失敗: 禁止値21を検出できない"
    assert ban_hits(ts, ["1.4"]) == [], "陰性対照失敗: 存在しない値を誤検出"
    assert set(ts) != {"21"}, "許可リスト比較が集合差を識別できない"


def svg_tech_checks(path, meta):
    """SVG技術要件（XML整形式・viewBox・self-contained）と答えの分離方針の機械検査"""
    src = path.read_text(encoding="utf-8")
    ET.fromstring(src)
    root_tag = src.split(">", 1)[0]
    assert "viewBox=" in root_tag, f"{path.name}: viewBoxがない"
    assert " width=" not in root_tag and " height=" not in root_tag, \
        f"{path.name}: ルートにwidth/heightを書かない"
    ext = src.replace('xmlns="http://www.w3.org/2000/svg"', "")
    assert "http" not in ext and "href" not in ext and "@import" not in ext, \
        f"{path.name}: 外部参照の疑い"
    assert "font-family" not in src, f"{path.name}: フォント指定は書かない"
    texts = svg_texts(src)
    # (1) 許可リスト検査: 図中の全ラベル=宣言済みの本文明示値のみ（完全一致）
    allow = set(meta["allow_texts"])
    got = set(texts)
    assert got == allow, (f"{path.name}: ラベル集合が許可リストと不一致 "
                          f"余分={got - allow} 不足={allow - got}")
    # (2) 禁止文字列検査: 練習・stretchの答え由来のトークンが図中にない
    hits = ban_hits(texts, meta.get("check_tokens", []))
    assert not hits, f"{path.name}: 禁止文字列が図中テキストにある: {hits}"
    # (3) 語彙の全文検査（title/desc含む）
    for ban in meta.get("check_tokens_full", []):
        assert ban not in src, f"{path.name}: 禁止語「{ban}」がSVG内にある"
    return len(texts)


def build_desc(meta):
    """SVG <desc> 用のAI再利用メタ情報（意図・主要数値・同型図をAIに描かせる説明文）"""
    return (
        f"【この図の意図】{meta['intent']}。"
        f"【主要な数値・設定】{meta['params']}。"
        f"【AIに同じ種類の図を描かせるときの説明文】"
        f"「{meta['title']}。{meta['intent']}。数値・設定: {meta['params']}。"
        f"白黒印刷向けのシンプルな教材図（SVG）としてかいて。」"
        f"——この説明文を生成AIに渡せば同型の図を描かせられる。"
        f"数値を変えれば類題用の図も作れる。"
    )


def main():
    gate_self_test()
    ASSETS.mkdir(parents=True, exist_ok=True)
    rows = []
    n_checks = 0
    for fn in FIGS:
        meta = fn()
        out = ASSETS / meta["file"]
        meta["canvas"].save(out, meta["file"], meta["title"], build_desc(meta))
        svg_tech_checks(out, meta)
        n_checks += len(meta["checks"])
        rows.append(meta)
        print(f"OK {out.name}  [{len(meta['checks'])} checks passed]")

    n_tokens = sum(len(m.get("check_tokens", [])) +
                   len(m.get("check_tokens_full", [])) for m in rows)
    head = ["<!--",
            f"generated: {GENERATED}（generate_figures.py により自動生成。手編集禁止——スクリプトを直して再実行）",
            "spec: docs/SPEC_figures.md・NE_STANDARD_FORM_SPEC_20260829.md §12 準拠",
            "license: CC-BY-4.0",
            "-->", ""]

    lines = head + [
        "# FIGURE_MANIFEST — 数Ⅰ数と式単元 図版台帳",
        "",
        f"生成日: {GENERATED} ／ 生成方式: `assets_provenance/generate_figures.py`"
        "（Python標準ライブラリのみ・パラメトリック生成・決定的）／ "
        f"全{len(rows)}図で下表の数学検算（スクリプト内assert・計{n_checks}項目）が"
        "生成時に自動実行され、全件合格。加えて全SVGにXML整形式・viewBox・"
        "self-contained の技術検査と答え漏れ検査を実施——"
        "答え漏れ検査は二重ゲート: (1)図中の全ラベルを許可リスト"
        "（本文が図の前後で明示している値のみ）と完全一致で照合、"
        f"(2)禁止文字列（練習・stretchの答え由来・計{n_tokens}項目・対象値は非開示）の"
        "不在検査。検査器自体は生成前の陽性対照（禁止値を仕込んだ合成SVGでの検出）で"
        "毎回実証している。PASS。／ "
        "図の選定は各 `notes/lesson_XX_notes.md` の図版仕様（プレースホルダ方式）が正で、"
        "必須13点＋任意2点（L04_fig1・L10_fig2——いずれも"
        "**図表積極採用の判断基準（3文以上の文章説明が続く概念・手順・対比）** を"
        "満たすと判断し採用）の全15点を生成した。／ "
        "AI再利用メタ情報として全SVGに`<title>`/`<desc>`"
        "（意図・主要数値・同型図をAIに描かせる説明文）を標準装備。",
        "",
        "| ファイル | 対象レッスン | 図の意図 | 本文対応箇所 | パラメータ（本文一致） | 検証結果（生成時assert） |",
        "|---|---|---|---|---|---|",
    ]
    for m in rows:
        checks = "／".join(f"{d}{'（' + t + '）' if t else ''} ✓" for d, t in m["checks"])
        lines.append(f"| `{m['file']}` | {m['lesson']} | {m['title']}——{m['intent']} | "
                     f"{m['src']} | {m['params']} | {checks} |")
    lines += [
        "",
        "## 図版番号・採否の注記",
        "",
        "- **L07の図版番号はマップ候補から入れ替え済み**: NE_CONTENT_MAP L07行の候補は"
        "「fig1=絶対値／fig2=有理化」だが、本文の登場順（§1有理化→§4絶対値）に合わせて"
        "fig1=有理化・fig2=絶対値とした（notes/lesson_07_notes.md §2 の指定どおり。"
        "生成工程はnotesを正とした）。",
        "- **任意図版2点は採用**: L04_fig1（係数の組の探索——候補表の直後の役割分担の"
        "説明が文章のみ）・L10_fig2（解x>10と最低票数11——「出口の解釈」の段落が文章のみ）。"
        "いずれも図表積極採用の判断基準を満たすと判断した。",
        "",
        "## 答えの分離方針の扱い——近隣設問の確認結果",
        "",
        "- 図中に書いた数値は、いずれも**本文（例題の解答・与件）が図の前後で明示している値**"
        "のみ。各図の許可リスト検査（ラベル集合の完全一致）で機械担保。",
        "- **L05図1**: 例ラベルは本文例題2の5・−2・0.6・−7/3・√3のみ。√9は"
        "「根号が外せる」罠の性質上、図に入れると分類の答えを固定的に見せるため入れない"
        "（notes指定）。練習問1の数は許可リスト検査で排除。",
        "- **L06図1**: 問5の解答例は本図と数値が重ならないよう a=100, b=36 に分離済み"
        "（notes指定——本図の9・16・25とは別系統）。",
        "- **L08図2**: 図のラベル2・−3は問2の答えと数値上重なるが、図は「2<3→−2>−3」の"
        "文脈であり問2（−4<6→2>−3）の与件・答えの組をそのまま示すものではない（notes判断）。"
        "監修で懸念があれば1と4のペアへ差し替え可（本文§2の数値例も連動変更のこと）。",
        "- **L09図1**: 例題の端点（−1・6）と練習・stretchの答えの端点（−3・3・−2・2・5）は"
        "執筆時に分離設計済み（notes §6）——図のラベルは−1・6のみ。",
        "- **L04図1**: 「たすき掛け」の名称は図中・title・descに不使用"
        "（SVG全文への禁止語検査で機械担保）。",
        "",
        "## ●○規約・数直線系の描法統一（docs/SPEC_figures.md §9-1）",
        "",
        "- 端点●（含む）○（含まない）は共通パラメータ（半径・縁の線幅）で描画し、"
        "L08_fig1・L09_fig1・L10_fig2 と凡例様式を共通化。",
        "- L09_fig1 は二次関数 L12_fig1 と同型の「数直線3段」描法"
        "（左=段ラベル・縦の破線ガイド・範囲の太線＋端点●○）。",
        "- L05_fig2（√2の点）・L06_fig1（長さの帯）・L07の2図（同一点・距離）は"
        "解範囲の表現ではないため●○の意味づけを使わない（点マーカーの描画パラメータのみ共通）。",
        "- L10_fig1 は概念フロー図であり●○規約の対象外。",
        "",
        "## 再生成・改修の手順（第三者向け）",
        "",
        "1. `generate_figures.py` の該当 `fig_*` 関数冒頭「パラメータ」ブロックを編集する"
        "（数値は必ず該当 `lesson_XX.md` 本文・`notes/lesson_XX_notes.md` 図版仕様と一致させる）。",
        "2. `python3 generate_figures.py` を実行する。検算assert・答え漏れ検査に1つでも"
        "落ちると図は出力されない（出力済みファイルは検査失敗時点のもので確定しない）。",
        "3. `assets/` のSVGと本ファイルが自動更新される。SVGの直接編集は禁止（来歴が切れる）。",
        "",
    ]
    (HERE / "FIGURE_MANIFEST.md").write_text(
        "---\ndistribution_status: published_draft\n---\n\n" + "\n".join(lines),
        encoding="utf-8")
    print(f"OK FIGURE_MANIFEST.md  ({len(rows)} figures, {n_checks} checks, "
          f"{sum(len(m.get('check_tokens', [])) + len(m.get('check_tokens_full', [])) for m in rows)} ban-tokens)")


if __name__ == "__main__":
    main()
