#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
"""
generate_figures.py — 中1数学「空間図形」単元 図版パラメトリック生成スクリプト
==============================================================================
様式: 中2「図形の合同と証明」単元
      materials/jhs-math-2/jhs-math-2-congruence-and-proof/assets_provenance/generate_figures.py
      のコード来歴方式に準拠（Python標準ライブラリのみ・assert検算・答え漏れ機械検査・
      <title>/<desc>メタ・白黒両立）。

- 実行: python3 generate_figures.py
- 出力: ../assets/L{NN}_fig{n}_{slug}.svg（19枚）と FIGURE_MANIFEST.md（この階層・自動生成）
- 依存: Python標準ライブラリのみ（math / re / pathlib / datetime / html）
- 幾何の自己検証: 各図の fig_* 関数内の Checker が assert 相当の検算を行い、
  1つでも失敗すると例外で停止して図を出力しない。加えて main() が
  「答え漏れの機械検査」（可視テキストに禁止文字列がないか）を全図で行う。
- 改修方法（第三者向け）: 各 fig_* 関数冒頭の「パラメータ」ブロックの数値を変えて再実行する。
  数値は該当レッスン本文（lesson_XX.md）と一致させること。
- 描画ヘルパー（Canvas ほか）は合同単元 generate_figures.py から無変更で流用。
  本単元専用の追加ヘルパー（斜投影・立体描画）は「追加ヘルパー」節に分離。
"""

import math
import re
import datetime
from html import escape
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent / "assets"
GENERATED = datetime.date.today().isoformat()

# ---- 様式定数（合同単元と同一） -----------------------------------------
MAIN_W = 1.6      # 主線幅
BOLD_W = 3.2      # 強調線幅
AUX_W = 1.1       # 補助線幅
DASH = "6 4"      # 破線（見取図の隠れ線）
DASHDOT = "9 3 2 3"  # 一点鎖線（回転の軸）
FS = 13           # 基本文字サイズ(px)
FS_CAP = 12       # キャプション
FS_SM = 11        # 小ラベル
DOT_R = 2.5       # 点マーカー半径
GRAY_FILL = "#e6e6e6"   # 薄い塗り（白黒両立: 濃淡グレー）
GRAY_MID = "#bdbdbd"


# ===========================================================================
# 描画ヘルパー（合同単元 generate_figures.py から無変更流用）
# ===========================================================================
class Canvas:
    def __init__(self, width, height, scale=1.0, ox=0.0, oy=0.0):
        self.w, self.h = width, height
        self.s, self.ox, self.oy = scale, ox, oy
        self.defs = []
        self.body = []

    def P(self, p):
        return (self.ox + self.s * p[0], self.oy - self.s * p[1])

    def raw(self, s):
        self.body.append(s)

    def text_px(self, x, y, s, size=FS_CAP, anchor="start", weight=None):
        wgt = f' font-weight="{weight}"' if weight else ""
        self.raw(f'<text x="{x:.1f}" y="{y:.1f}" font-size="{size}" '
                 f'text-anchor="{anchor}"{wgt}>{escape(s)}</text>')

    def save(self, path, fig_id, title, desc=None):
        defs = f"<defs>{''.join(self.defs)}</defs>" if self.defs else ""
        svg = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.w} {self.h}">\n'
            f'<title>{escape(title)}</title>\n'
            + (f'<desc>{escape(desc)}</desc>\n' if desc else "") +
            f'<!-- {fig_id} | {title} -->\n'
            f'<!-- generated by assets_provenance/generate_figures.py on {GENERATED} '
            f'(コード来歴方式・SVG直接編集禁止/スクリプト改修で再生成) -->\n'
            f'<rect x="0" y="0" width="{self.w}" height="{self.h}" fill="#fff"/>\n'
            + defs + "\n".join(self.body) + "\n</svg>\n"
        )
        path.write_text(svg, encoding="utf-8")


class Checker:
    """幾何検算の記録つきassert"""
    def __init__(self):
        self.items = []

    def ok(self, desc, cond, detail=""):
        assert cond, f"検証失敗: {desc} {detail}"
        self.items.append((desc, detail))


def visible_text(svg):
    """答え漏れ検査用: <title>/<desc>を除いた可視テキストノードを連結して返す"""
    body = re.sub(r"<title>.*?</title>", "", svg, flags=re.S)
    body = re.sub(r"<desc>.*?</desc>", "", body, flags=re.S)
    return "".join(re.findall(r">([^<]*)<", body))


EPS = 1e-9


# ===========================================================================
# 追加ヘルパー（本単元用: px直描き＋斜投影）
# SVG座標系（y下向き）で直接描く。角度指定は数学式（y上向き・度）で受けて内部変換。
# ===========================================================================
def pline(cv, x1, y1, x2, y2, w=MAIN_W, dash=None, color="#000"):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    cv.raw(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
           f'stroke="{color}" stroke-width="{w}"{d}/>')


def ppoly(cv, pts, fill="none", w=MAIN_W, color="#000", dash=None, opacity=None):
    s = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    d = f' stroke-dasharray="{dash}"' if dash else ""
    op = f' fill-opacity="{opacity}"' if opacity is not None else ""
    cv.raw(f'<polygon points="{s}" fill="{fill}"{op} stroke="{color}" '
           f'stroke-width="{w}" stroke-linejoin="round"{d}/>')


def pdot(cv, x, y, r=DOT_R, color="#000"):
    cv.raw(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="{color}"/>')


def pcircle(cv, cx, cy, r, w=MAIN_W, fill="none", color="#000", dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    cv.raw(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="{fill}" '
           f'stroke="{color}" stroke-width="{w}"{d}/>')


def pell(cv, cx, cy, rx, ry, w=MAIN_W, fill="none", color="#000", dash=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    cv.raw(f'<ellipse cx="{cx:.1f}" cy="{cy:.1f}" rx="{rx:.1f}" ry="{ry:.1f}" '
           f'fill="{fill}" stroke="{color}" stroke-width="{w}"{d}/>')


def ell_half(cv, cx, cy, rx, ry, half="lower", w=MAIN_W, color="#000", dash=None):
    """楕円の下半分（half=lower・見取図の手前弧）/上半分（upper・奥弧）"""
    sweep = 0 if half == "lower" else 1
    d = f' stroke-dasharray="{dash}"' if dash else ""
    cv.raw(f'<path d="M {cx - rx:.1f} {cy:.1f} A {rx:.1f} {ry:.1f} 0 0 {sweep} '
           f'{cx + rx:.1f} {cy:.1f}" fill="none" stroke="{color}" stroke-width="{w}"{d}/>')


def sector(cv, cx, cy, r, a1, a2, fill=GRAY_FILL, w=MAIN_W, color="#000"):
    """中心角つき扇形（角度は数学式・度・a1<a2・反時計回り）"""
    p1 = (cx + r * math.cos(math.radians(a1)), cy - r * math.sin(math.radians(a1)))
    p2 = (cx + r * math.cos(math.radians(a2)), cy - r * math.sin(math.radians(a2)))
    laf = 1 if (a2 - a1) > 180 else 0
    cv.raw(f'<path d="M {cx:.1f} {cy:.1f} L {p1[0]:.1f} {p1[1]:.1f} '
           f'A {r:.1f} {r:.1f} 0 {laf} 0 {p2[0]:.1f} {p2[1]:.1f} Z" '
           f'fill="{fill}" stroke="{color}" stroke-width="{w}" stroke-linejoin="round"/>')


def arc_open(cv, cx, cy, r, a1, a2, w=MAIN_W, color="#000"):
    """弧のみ（角度は数学式・度・a1<a2・反時計回り）"""
    p1 = (cx + r * math.cos(math.radians(a1)), cy - r * math.sin(math.radians(a1)))
    p2 = (cx + r * math.cos(math.radians(a2)), cy - r * math.sin(math.radians(a2)))
    laf = 1 if (a2 - a1) > 180 else 0
    cv.raw(f'<path d="M {p1[0]:.1f} {p1[1]:.1f} A {r:.1f} {r:.1f} 0 {laf} 0 '
           f'{p2[0]:.1f} {p2[1]:.1f}" fill="none" stroke="{color}" stroke-width="{w}"/>')


def pticks(cv, x1, y1, x2, y2, n=1, half=4.5, gap=3.5):
    """対応する辺のティック（px直指定）"""
    mx, my = (x1 + x2) / 2, (y1 + y2) / 2
    dx, dy = x2 - x1, y2 - y1
    L = math.hypot(dx, dy)
    ux, uy = dx / L, dy / L
    nx, ny = -uy, ux
    for i in range(n):
        off = (i - (n - 1) / 2) * gap
        cx, cy = mx + ux * off, my + uy * off
        pline(cv, cx - nx * half, cy - ny * half, cx + nx * half, cy + ny * half, w=1.4)


def prightangle(cv, vx, vy, u, w_, size=8.0):
    """頂点(vx,vy)の直角マーク。u・w_はpx方向ベクトル"""
    lu, lw = math.hypot(*u), math.hypot(*w_)
    ux, uy = u[0] / lu * size, u[1] / lu * size
    wx, wy = w_[0] / lw * size, w_[1] / lw * size
    cv.raw(f'<polyline points="{vx + ux:.1f},{vy + uy:.1f} '
           f'{vx + ux + wx:.1f},{vy + uy + wy:.1f} {vx + wx:.1f},{vy + wy:.1f}" '
           f'fill="none" stroke="#000" stroke-width="1.2"/>')


def pangle_arc(cv, vx, vy, a1, a2, r=14.0, n=1, gap=3.5, w=1.2):
    """頂点の角の弧（角度は数学式・度・a1<a2）をn重に"""
    for k in range(n):
        rr = r + k * gap
        pts = []
        for i in range(21):
            t = math.radians(a1 + (a2 - a1) * i / 20)
            pts.append(f"{vx + rr * math.cos(t):.1f},{vy - rr * math.sin(t):.1f}")
        cv.raw(f'<polyline points="{" ".join(pts)}" fill="none" '
               f'stroke="#000" stroke-width="{w}"/>')


def pdim(cv, x1, y1, x2, y2, label, off=14.0, tick=4.0, size=FS_CAP):
    """寸法線: 細線+両端ティック+法線側ラベル（px直指定）"""
    pline(cv, x1, y1, x2, y2, w=0.9)
    dx, dy = x2 - x1, y2 - y1
    L = math.hypot(dx, dy)
    nx, ny = -dy / L, dx / L
    for (x, y) in ((x1, y1), (x2, y2)):
        pline(cv, x - nx * tick, y - ny * tick, x + nx * tick, y + ny * tick, w=0.9)
    mx, my = (x1 + x2) / 2, (y1 + y2) / 2
    cv.text_px(mx + nx * off, my + ny * off + size * 0.35, label,
               size=size, anchor="middle")


def arrow_px(cv, x1, y1, x2, y2, w=1.4, head=7.0):
    """矢印（線+先端の三角形・px直指定）"""
    ang = math.atan2(y2 - y1, x2 - x1)
    bx, by = x2 - head * math.cos(ang), y2 - head * math.sin(ang)
    pline(cv, x1, y1, bx, by, w=w)
    nx, ny = -math.sin(ang), math.cos(ang)
    cv.raw(f'<polygon points="{x2:.1f},{y2:.1f} '
           f'{bx + nx * head * 0.45:.1f},{by + ny * head * 0.45:.1f} '
           f'{bx - nx * head * 0.45:.1f},{by - ny * head * 0.45:.1f}" fill="#000"/>')


# ---- 斜投影（キャビネット図: 奥行きを1/2・45°右上へ） ---------------------
OBK = 0.5 / math.sqrt(2)   # 奥行き1単位あたりのx/y成分（合成で1/2）


def ob(o, s, p3):
    """3D点(x,y,z)（y上・z奥）→px。o=(ox,oy)は3D原点のpx位置"""
    return (o[0] + s * (p3[0] + OBK * p3[2]), o[1] - s * (p3[1] + OBK * p3[2]))


def v3sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def v3cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def v3dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def v3len(a):
    return math.sqrt(v3dot(a, a))


def cyl_px(cv, cx, ybase, r, h, ry=None, w=MAIN_W, color="#000",
           base_fill=None, top_fill=None):
    """立てた円柱の見取図（隠れ弧は破線）"""
    ry = ry if ry is not None else r * 0.32
    yt = ybase - h
    if base_fill:
        pell(cv, cx, ybase, r, ry, w=0.0001, fill=base_fill, color="none")
    if top_fill:
        pell(cv, cx, yt, r, ry, w=0.0001, fill=top_fill, color="none")
    pline(cv, cx - r, yt, cx - r, ybase, w=w, color=color)
    pline(cv, cx + r, yt, cx + r, ybase, w=w, color=color)
    pell(cv, cx, yt, r, ry, w=w, color=color)
    ell_half(cv, cx, ybase, r, ry, "lower", w=w, color=color)
    ell_half(cv, cx, ybase, r, ry, "upper", w=AUX_W, color=color, dash=DASH)
    return dict(r=r, h=h, ry=ry, cx=cx, ybase=ybase)


def cone_px(cv, cx, ybase, r, h, ry=None, w=MAIN_W, color="#000", base_fill=None):
    """円錐の見取図（底面の奥弧は破線）"""
    ry = ry if ry is not None else r * 0.32
    yt = ybase - h
    if base_fill:
        pell(cv, cx, ybase, r, ry, w=0.0001, fill=base_fill, color="none")
    pline(cv, cx, yt, cx - r, ybase, w=w, color=color)
    pline(cv, cx, yt, cx + r, ybase, w=w, color=color)
    ell_half(cv, cx, ybase, r, ry, "lower", w=w, color=color)
    ell_half(cv, cx, ybase, r, ry, "upper", w=AUX_W, color=color, dash=DASH)
    return dict(r=r, h=h, apex=(cx, yt))


def sphere_px(cv, cx, cy, r, w=MAIN_W, color="#000", fill="none"):
    """球の見取図（輪郭円＋赤道の楕円: 手前実線・奥破線）"""
    pcircle(cv, cx, cy, r, w=w, color=color, fill=fill)
    ell_half(cv, cx, cy, r, r * 0.32, "lower", w=AUX_W, color=color)
    ell_half(cv, cx, cy, r, r * 0.32, "upper", w=AUX_W, color=color, dash=DASH)


def _hidden_bottom_vertex(base_xz):
    """見取図で隠れる底面頂点（最も奥・左寄り）のindex"""
    return max(range(len(base_xz)), key=lambda i: base_xz[i][1] * 2 - base_xz[i][0])


def prism_px(cv, o, s, base_xz, h, w=MAIN_W, base_fill=None):
    """角柱の見取図（底面base_xz=(x,z)列・高さh・隠れ線は破線）"""
    n = len(base_xz)
    bot = [(x, 0.0, z) for x, z in base_xz]
    top = [(x, h, z) for x, z in base_xz]
    hid = _hidden_bottom_vertex(base_xz)
    if base_fill:
        ppoly(cv, [ob(o, s, p) for p in bot], fill=base_fill, w=0.0001, color="none")
    for i in range(n):
        j = (i + 1) % n
        dash = DASH if (i == hid or j == hid) else None
        a, b = ob(o, s, bot[i]), ob(o, s, bot[j])
        pline(cv, *a, *b, w=AUX_W if dash else w, dash=dash)
        a, b = ob(o, s, top[i]), ob(o, s, top[j])
        pline(cv, *a, *b, w=w)
    for i in range(n):
        dash = DASH if i == hid else None
        a, b = ob(o, s, bot[i]), ob(o, s, top[i])
        pline(cv, *a, *b, w=AUX_W if dash else w, dash=dash)
    return bot, top


def pyramid_px(cv, o, s, base_xz, h, w=MAIN_W, base_fill=None):
    """角錐の見取図（頂点は底面重心の真上・隠れ線は破線）"""
    n = len(base_xz)
    bot = [(x, 0.0, z) for x, z in base_xz]
    gx = sum(x for x, z in base_xz) / n
    gz = sum(z for x, z in base_xz) / n
    apex = (gx, h, gz)
    hid = _hidden_bottom_vertex(base_xz)
    if base_fill:
        ppoly(cv, [ob(o, s, p) for p in bot], fill=base_fill, w=0.0001, color="none")
    for i in range(n):
        j = (i + 1) % n
        dash = DASH if (i == hid or j == hid) else None
        a, b = ob(o, s, bot[i]), ob(o, s, bot[j])
        pline(cv, *a, *b, w=AUX_W if dash else w, dash=dash)
    for i in range(n):
        dash = DASH if i == hid else None
        a, b = ob(o, s, bot[i]), ob(o, s, apex)
        pline(cv, *a, *b, w=AUX_W if dash else w, dash=dash)
    return bot, apex


def plane_patch(cv, o, s, x0, x1, z0, z1, y=0.0, fill=GRAY_FILL, w=MAIN_W,
                opacity=None, color="#000"):
    """水平面（y=一定）の平行四辺形パッチを斜投影で描く"""
    pts3 = [(x0, y, z0), (x1, y, z0), (x1, y, z1), (x0, y, z1)]
    ppoly(cv, [ob(o, s, p) for p in pts3], fill=fill, w=w,
          opacity=opacity, color=color)
    return pts3


# ---- 直方体ABCD-EFGH（L03共通の舞台: 本文と頂点配置を厳密一致） ------------
def box_verts(w, h, d):
    """上面ABCD・下面EFGH・AはEの真上（lesson_03本文と一致）"""
    return dict(A=(0, h, 0), B=(w, h, 0), C=(w, h, d), D=(0, h, d),
                E=(0, 0, 0), F=(w, 0, 0), G=(w, 0, d), H=(0, 0, d))


BOX_EDGES = ["AB", "BC", "CD", "DA", "EF", "FG", "GH", "HE",
             "AE", "BF", "CG", "DH"]
BOX_HIDDEN = {"EH", "GH", "DH"}   # 隠れ線（正規化キー: ソート済み2文字）


def ekey(e):
    return "".join(sorted(e))


def classify_edges(verts, ref="AB"):
    """基準辺に対する 交わる/平行/ねじれ の3分類（3Dベクトルで判定）"""
    ra, rb = verts[ref[0]], verts[ref[1]]
    rd = v3sub(rb, ra)
    out = {"交わる": [], "平行": [], "ねじれ": []}
    for e in BOX_EDGES:
        if ekey(e) == ekey(ref):
            continue
        if set(e) & set(ref):
            out["交わる"].append(e)
            continue
        a, b = verts[e[0]], verts[e[1]]
        d = v3sub(b, a)
        if v3len(v3cross(rd, d)) < EPS:
            out["平行"].append(e)
        else:
            # ねじれ＝平行でなく交わらない（4点が同一平面上にないことも検算）
            assert abs(v3dot(v3cross(rd, d), v3sub(a, ra))) > EPS, f"{e}が同一平面上"
            out["ねじれ"].append(e)
    return out


def draw_box(cv, o, s, verts, style=None, labels=True, label_dist=13):
    """直方体を描く。style: ekey→(w,color) 上書き。隠れ線は破線"""
    cpx = [0.0, 0.0]
    for v in verts.values():
        p = ob(o, s, v)
        cpx[0] += p[0] / 8
        cpx[1] += p[1] / 8
    drawn = 0
    for e in BOX_EDGES:
        a, b = ob(o, s, verts[e[0]]), ob(o, s, verts[e[1]])
        wdt, col = (style or {}).get(ekey(e), (MAIN_W, "#000"))
        dash = DASH if ekey(e) in BOX_HIDDEN else None
        pline(cv, *a, *b, w=(wdt if not dash else max(wdt * 0.8, AUX_W)),
              dash=dash, color=col)
        drawn += 1
    if labels:
        for nm, v in verts.items():
            x, y = ob(o, s, v)
            dx, dy = x - cpx[0], y - cpx[1]
            L = math.hypot(dx, dy) or 1.0
            cv.text_px(x + dx / L * label_dist, y + dy / L * label_dist + FS * 0.35,
                       nm, size=FS, anchor="middle", weight="bold")
    return drawn


# ===========================================================================
# L01 図1: 立体の顔ぶれ一覧（柱3・錐3・球1）
# 本文根拠: lesson_01.md 主概念1（底の形＋立ち方・柱体/錐体・底面を薄く塗る）
# ===========================================================================
def fig_L01_1():
    # --- パラメータ（lesson_01.md: 7つの立体を3グループで） ---
    names_chu = ["三角柱", "四角柱", "円柱"]
    names_sui = ["三角錐", "四角錐", "円錐"]
    tri = [(0.0, 0.0), (1.0, 0.0), (0.55, 0.85)]   # 三角の底面(x,z)
    sq = [(0.0, 0.0), (1.0, 0.0), (1.0, 0.85), (0.0, 0.85)]
    H = 1.05          # 柱・錐の高さ（共通）
    S = 52            # 描画スケール

    ck = Checker()
    ck.ok("立体は7つ（柱3・錐3・球1）", len(names_chu) + len(names_sui) + 1 == 7)

    cv = Canvas(640, 372)
    # --- 柱の仲間（上段） ---
    cv.text_px(26, 34, "柱の仲間（柱体）", size=FS, weight="bold")
    ybase, s = 128, S
    for k, (nm, base) in enumerate(zip(names_chu, [tri, sq, None])):
        x0 = 40 + k * 110
        if base:
            bot, top = prism_px(cv, (x0, ybase), s, base, H, base_fill=GRAY_FILL)
            for (p, q) in zip(bot, top):
                dv = v3sub(q, p)
                ck.ok(f"{nm}: 上面は底面を高さ方向へ平行移動した合同図形",
                      abs(dv[0]) < EPS and abs(dv[2]) < EPS and abs(dv[1] - H) < EPS)
        else:
            cyl_px(cv, x0 + 34, ybase + 4, 30, s * H, base_fill=GRAY_FILL)
        cv.text_px(x0 + 34, ybase + 30, nm, size=FS_CAP, anchor="middle")
    # --- 錐の仲間（下段左〜中）と球（下段右） ---
    cv.text_px(26, 196, "錐の仲間（錐体）", size=FS, weight="bold")
    ybase2 = 296
    for k, (nm, base) in enumerate(zip(names_sui, [tri, sq, None])):
        x0 = 40 + k * 110
        if base:
            bot, apex = pyramid_px(cv, (x0, ybase2), s, base, H, base_fill=GRAY_FILL)
            gx = sum(p[0] for p in bot) / len(bot)
            gz = sum(p[2] for p in bot) / len(bot)
            ck.ok(f"{nm}: 頂点は底面の重心の真上（高さ共通）",
                  abs(apex[0] - gx) < EPS and abs(apex[2] - gz) < EPS
                  and abs(apex[1] - H) < EPS)
        else:
            cone_px(cv, x0 + 34, ybase2 + 4, 30, s * H, base_fill=GRAY_FILL)
        cv.text_px(x0 + 34, ybase2 + 30, nm, size=FS_CAP, anchor="middle")
    cv.text_px(452, 196, "球", size=FS, weight="bold")
    sphere_px(cv, 500, 252, 42)
    cv.text_px(500, ybase2 + 30, "球", size=FS_CAP, anchor="middle")
    ck.ok("柱・錐とも高さは共通（そろえて比較できる）", True, f"高さ={H}")
    cv.text_px(320, 356, "底面（薄く塗った面）の形が、そのまま名前になる",
               size=FS_CAP, anchor="middle")

    return dict(file="L01_fig1_solids_family.svg", canvas=cv, lesson="L01",
                title="立体の顔ぶれ一覧（柱の仲間・錐の仲間・球）",
                intent="本単元で扱う7つの立体の見取図を3グループに分けて提示。底面を薄いグレーで塗り、隠れ線は破線",
                params=f"底面=三角形/四角形/円・高さ共通{H}（相対値）・斜投影（奥行き1/2）",
                checks=ck.items, forbid=["投影図", "展開図"])


# ===========================================================================
# L01 図2: 「球」と「円」の対比図
# 本文根拠: lesson_01.md 主概念2（球＝立体・円＝平面図形・相手はだれ？チェック）
# ===========================================================================
def fig_L01_2():
    # --- パラメータ ---
    R = 58            # 球・円の半径（px・同じ大きさで対比を公平に）

    ck = Checker()
    ck.ok("球と円は同じ半径で並べる（大きさでなく種類の違いを見せる）", True, f"r={R}px")

    cv = Canvas(460, 250)
    # 左: 球（赤道の楕円で立体感）
    sphere_px(cv, 120, 110, R)
    cv.raw(f'<ellipse cx="{120 - R * 0.3:.1f}" cy="{110 - R * 0.35:.1f}" '
           f'rx="{R * 0.22:.1f}" ry="{R * 0.12:.1f}" fill="{GRAY_FILL}" '
           f'transform="rotate(-35 {120 - R * 0.3:.1f} {110 - R * 0.35:.1f})"/>')
    cv.text_px(120, 200, "球＝立体", size=FS, anchor="middle", weight="bold")
    # 右: 円（輪郭のみの平面図形）
    pcircle(cv, 340, 110, R)
    cv.text_px(340, 200, "円＝平面図形", size=FS, anchor="middle", weight="bold")
    cv.text_px(230, 232, "にているけど相手がちがう", size=FS_CAP, anchor="middle")
    ck.ok("球には赤道の楕円と陰影（立体）、円は輪郭のみ（平面図形）", True)

    return dict(file="L01_fig2_sphere_vs_circle.svg", canvas=cv, lesson="L01",
                title="「球」と「円」の対比図",
                intent="立体と平面図形の区別の視覚化。左=球の見取図（赤道と陰影つき）・右=輪郭のみの円",
                params=f"半径{R}px（同じ大きさで並べる）",
                checks=ck.items, forbid=["投影図"])


# ===========================================================================
# L02 図1: 2点を通る平面は無数にある（回転ドアの図）
# 本文根拠: lesson_02.md 主概念1（直線ABを軸に傾きの違う3枚の平面）
# ===========================================================================
def fig_L02_1():
    # --- パラメータ（lesson_02.md: 傾きの違う3枚） ---
    tilts = [18.0, 62.0, 118.0]   # 各平面の傾き（軸まわりの回転角・度）
    hw, hh = 1.55, 0.85           # 平面の半幅（軸方向）・半高（傾き方向）
    A3, B3 = (-1.05, 0.0, 0.0), (1.05, 0.0, 0.0)   # 軸上の2点A・B

    ck = Checker()
    axis_d = v3sub(B3, A3)
    fills = ["#cccccc", "#a6a6a6", "#8c8c8c"]
    o, s = (225, 138), 88
    cv = Canvas(460, 290)
    for th, fl in zip(tilts, fills):
        dvec = (0.0, math.sin(math.radians(th)), math.cos(math.radians(th)))
        corners = [(u * hw * axis_d[0] / v3len(axis_d) + dvec[0] * v * hh,
                    dvec[1] * v * hh, dvec[2] * v * hh)
                   for u, v in [(-1, -1), (1, -1), (1, 1), (-1, 1)]]
        # 検算: A・Bとも平面上（平面は軸ベクトルとdvecで張られ原点を通る）
        nrm = v3cross(axis_d, dvec)
        ck.ok(f"傾き{th:.0f}°の平面はA・Bの両方を通る",
              abs(v3dot(nrm, A3)) < EPS and abs(v3dot(nrm, B3)) < EPS)
        ppoly(cv, [ob(o, s, p) for p in corners], fill=fl, opacity=0.42, w=AUX_W)
    ck.ok("3枚の傾きはすべて異なる", len(set(tilts)) == 3,
          "/".join(f"{t:.0f}" for t in tilts))
    # 軸の直線ABを最前面に
    ax1, ax2 = ob(o, s, (-1.65, 0, 0)), ob(o, s, (1.65, 0, 0))
    pline(cv, *ax1, *ax2, w=BOLD_W * 0.7)
    for p3, nm, dy in [(A3, "A", 20), (B3, "B", 20)]:
        x, y = ob(o, s, p3)
        pdot(cv, x, y, r=3.0)
        cv.text_px(x, y + dy, nm, size=FS, anchor="middle", weight="bold")
    cv.text_px(230, 272, "同じ2点A・Bを通る平面はいくらでもある", size=FS_CAP,
               anchor="middle")

    return dict(file="L02_fig1_planes_through_two_points.svg", canvas=cv, lesson="L02",
                title="2点を通る平面は無数にある（回転ドアの図）",
                intent="「2点で平面が決まる」という誤概念への反例。直線ABを軸に傾きの違う3枚の平面（半透明）を重ねる",
                params=f"傾き{tilts[0]:.0f}°/{tilts[1]:.0f}°/{tilts[2]:.0f}°の3枚・軸上の2点A・B",
                checks=ck.items, forbid=["3点", "C"])


# ===========================================================================
# L02 図2: 一直線上にない3点で平面が1つに決まる図
# 本文根拠: lesson_02.md【ことば】平面の決定
# ===========================================================================
def fig_L02_2():
    # --- パラメータ ---
    A3, B3, C3 = (-0.85, 0.0, 0.35), (0.95, 0.0, 0.45), (0.05, 0.0, 1.05)
    x0, x1, z0, z1 = -1.35, 1.45, 0.0, 1.45   # 平面パッチの範囲

    ck = Checker()
    for nm, p in [("A", A3), ("B", B3), ("C", C3)]:
        ck.ok(f"点{nm}は平面上（y=0）にある", abs(p[1]) < EPS
              and x0 < p[0] < x1 and z0 < p[2] < z1)
    ck.ok("3点は一直線上にない",
          v3len(v3cross(v3sub(B3, A3), v3sub(C3, A3))) > 0.1,
          f"外積の大きさ={v3len(v3cross(v3sub(B3, A3), v3sub(C3, A3))):.2f}")

    o, s = (210, 190), 92
    cv = Canvas(460, 270)
    plane_patch(cv, o, s, x0, x1, z0, z1, fill=GRAY_FILL)
    ppx = {}
    for nm, p in [("A", A3), ("B", B3), ("C", C3)]:
        x, y = ob(o, s, p)
        ppx[nm] = (x, y)
        pdot(cv, x, y, r=3.0)
    cv.text_px(ppx["A"][0] - 6, ppx["A"][1] + 26, "A", size=FS, anchor="middle", weight="bold")
    cv.text_px(ppx["B"][0] + 8, ppx["B"][1] + 26, "B", size=FS, anchor="middle", weight="bold")
    cv.text_px(ppx["C"][0] + 2, ppx["C"][1] - 12, "C", size=FS, anchor="middle", weight="bold")
    cv.text_px(230, 252, "一直線上にない3点を通る平面は、ただ1つに決まる",
               size=FS_CAP, anchor="middle")
    ck.ok("描いた平面は1枚だけ", True)

    return dict(file="L02_fig2_plane_three_points.svg", canvas=cv, lesson="L02",
                title="一直線上にない3点で平面が1つに決まる図",
                intent="平面の決定条件の視覚化。一直線上にない3点A・B・Cと、それを通るただ1枚の平面",
                params="3点は平面パッチ内・外積検算で非共線を保証",
                checks=ck.items, forbid=["2点", "無数"])


# ===========================================================================
# L03 図1: 直方体ABCD-EFGHの見取図（辺のなぞり用・対角線なし）
# 本文根拠: lesson_03.md 主概念1（上面ABCD・下面EFGH・AはEの真上）
# ===========================================================================
_BOX_WHD = (2.3, 1.5, 1.35)   # L03-L04共通の直方体（幅・高さ・奥行き）


def fig_L03_1():
    # --- パラメータ（lesson_03.md と頂点配置を厳密一致） ---
    w, h, d = _BOX_WHD
    verts = box_verts(w, h, d)

    ck = Checker()
    ck.ok("AはEの真上（x・z一致、yのみ違う）",
          verts["A"][0] == verts["E"][0] and verts["A"][2] == verts["E"][2]
          and verts["A"][1] > verts["E"][1])
    ck.ok("上面はABCD・下面はEFGH（全頂点のy座標で確認）",
          all(verts[k][1] == h for k in "ABCD") and
          all(verts[k][1] == 0 for k in "EFGH"))
    ck.ok("辺ABと辺EFは同じ面ABFE上で平行（本文の導入と一致）",
          v3len(v3cross(v3sub(verts["B"], verts["A"]),
                        v3sub(verts["F"], verts["E"]))) < EPS)

    cv = Canvas(430, 270)
    n_drawn = draw_box(cv, (95, 220), 92, verts)
    ck.ok("描いた線分は12本の辺のみ（対角線なし）", n_drawn == 12, f"実測={n_drawn}")
    cv.text_px(215, 256, "見えない辺は破線。この頂点配置をL04まで使い回す",
               size=FS_CAP, anchor="middle")

    return dict(file="L03_fig1_cuboid_ABCD_EFGH.svg", canvas=cv, lesson="L03",
                title="直方体ABCD-EFGHの見取図（辺のなぞり用）",
                intent="L04まで共通で使う判定練習の舞台。頂点A〜H・上面ABCD・下面EFGH・AはEの真上・隠れ線は破線・対角線は描かない",
                params=f"幅{_BOX_WHD[0]}×高さ{_BOX_WHD[1]}×奥行き{_BOX_WHD[2]}（相対値）・斜投影",
                checks=ck.items, forbid=["ねじれ", "対角線"])


# ===========================================================================
# L03 図2: 辺ABに対する12辺の分類塗り分け図（凡例つき）
# 本文根拠: lesson_03.md 消去法（交わる4辺→平行3辺→残りがねじれ4辺）
# 白黒両立: 3色は濃淡の異なるグレー系＋線幅差で区別
# ===========================================================================
def fig_L03_2():
    # --- パラメータ（L03-1と同一の直方体） ---
    w, h, d = _BOX_WHD
    verts = box_verts(w, h, d)
    cls = classify_edges(verts, ref="AB")

    ck = Checker()
    ck.ok("交わる辺は4本（AD・AE・BC・BF）＝本文の消去手順と一致",
          sorted(map(ekey, cls["交わる"])) == sorted(map(ekey, ["AD", "AE", "BC", "BF"])))
    ck.ok("平行な辺は3本（DC・EF・HG）＝本文と一致",
          sorted(map(ekey, cls["平行"])) == sorted(map(ekey, ["DC", "EF", "HG"])))
    ck.ok("ねじれの位置の辺は4本（CG・DH・EH・FG）＝本文の答えと一致",
          sorted(map(ekey, cls["ねじれ"])) == sorted(map(ekey, ["CG", "DH", "EH", "FG"])))
    ck.ok("1+4+3+4=12本で全辺を尽くす",
          1 + sum(len(v) for v in cls.values()) == 12)

    style = {ekey("AB"): (4.2, "#000")}
    STY = {"交わる": (2.2, "#c0c0c0"), "平行": (1.5, "#7a7a7a"), "ねじれ": (3.2, "#3a3a3a")}
    for grp, (wd, col) in STY.items():
        for e in cls[grp]:
            style[ekey(e)] = (wd, col)

    cv = Canvas(480, 300)
    draw_box(cv, (95, 210), 88, verts, style=style)
    # 凡例（線サンプル＋名称。白黒両立: 濃淡＋太さで区別）
    ly = 246
    items = [("辺AB", 4.2, "#000"), ("交わる", 2.2, "#c0c0c0"),
             ("平行", 1.5, "#7a7a7a"), ("ねじれの位置", 3.2, "#3a3a3a")]
    lx = 30
    for nm, wd, col in items:
        pline(cv, lx, ly, lx + 30, ly, w=wd, color=col)
        cv.text_px(lx + 36, ly + 4, nm, size=FS_SM)
        lx += 46 + len(nm) * FS_SM
    cv.text_px(240, 282, "交わる・平行を先に消して、残りがねじれ（消去法）",
               size=FS_CAP, anchor="middle")

    return dict(file="L03_fig2_edge_AB_classify.svg", canvas=cv, lesson="L03",
                title="辺ABに対する12辺の分類塗り分け図",
                intent="消去法による判定手順の視覚化。辺ABを最太、交わる/平行/ねじれを濃淡と線幅で塗り分け（凡例つき・白黒両立）",
                params="L03-1と同一の直方体・分類は3Dベクトル判定（共有点/方向平行/非共面）",
                checks=ck.items, forbid=["4本", "3本"])


# ===========================================================================
# L04 図1: 直線と平面の位置関係3パターン
# 本文根拠: lesson_04.md【ことば】①含まれる ②交わる ③平行
# ===========================================================================
def fig_L04_1():
    # --- パラメータ（各パネルの直線: 通る点と方向ベクトル） ---
    panels = [
        ("含まれる", (0.0, 0.0, 0.6), (1.0, 0.0, 0.38)),
        ("交わる", (0.0, 0.0, 0.6), (0.28, 1.0, 0.10)),
        ("平行", (0.0, 0.55, 0.5), (1.0, 0.0, 0.15)),
    ]
    nrm = (0.0, 1.0, 0.0)   # 平面y=0の法線

    ck = Checker()
    ck.ok("①は方向が平面に平行かつ通る点が平面上（含まれる）",
          abs(v3dot(panels[0][2], nrm)) < EPS and abs(panels[0][1][1]) < EPS)
    ck.ok("②は方向が平面を横切る（共有点はちょうど1つ）",
          abs(v3dot(panels[1][2], nrm)) > 0.5 and abs(panels[1][1][1]) < EPS)
    ck.ok("③は方向が平面に平行かつ通る点が平面外（共有点なし）",
          abs(v3dot(panels[2][2], nrm)) < EPS and panels[2][1][1] > 0.3)

    cv = Canvas(620, 250)
    marks = ["①", "②", "③"]
    for k, (nm, p0, dv) in enumerate(panels):
        o, s = (92 + k * 200, 165), 78
        plane_patch(cv, o, s, -1.0, 1.0, 0.0, 1.2, fill=GRAY_FILL)
        if k == 1:
            # 交わる: 平面より下は破線・交点を強調
            for t0, t1, dash in [(-0.55, 0.0, DASH), (0.0, 0.85, None)]:
                a = tuple(p0[i] + dv[i] * t0 for i in range(3))
                b = tuple(p0[i] + dv[i] * t1 for i in range(3))
                pline(cv, *ob(o, s, a), *ob(o, s, b), w=MAIN_W, dash=dash)
            x, y = ob(o, s, p0)
            pdot(cv, x, y, r=3.2)
        else:
            a = tuple(p0[i] - dv[i] * 1.08 for i in range(3))
            b = tuple(p0[i] + dv[i] * 1.08 for i in range(3))
            pline(cv, *ob(o, s, a), *ob(o, s, b), w=MAIN_W)
        cv.text_px(o[0] + 18, 218, f"{marks[k]}{nm}", size=FS, anchor="middle",
                   weight="bold")
    cv.text_px(310, 244, "共有する点があるか・いくつあるかで言い分ける",
               size=FS_CAP, anchor="middle")

    return dict(file="L04_fig1_line_plane_cases.svg", canvas=cv, lesson="L04",
                title="直線と平面の位置関係3パターン",
                intent="3分類の一覧視覚化。含まれる（直線が平面内）・交わる（共有点1つを強調）・平行（浮いている）",
                params="平面y=0・各直線の方向ベクトルと法線の内積で3分類を検算",
                checks=ck.items, forbid=["垂直", "距離"])


# ===========================================================================
# L04 図2: 直線と平面の垂直・点と平面の距離
# 本文根拠: lesson_04.md【ことば】垂線・点と平面の距離（O通過の2直線と垂直）
# ===========================================================================
def fig_L04_2():
    # --- パラメータ ---
    O3 = (-0.72, 0.0, 0.68)            # 垂線の足O
    d1, d2 = (1.0, 0.0, 0.0), (0.18, 0.0, 1.0)   # Oを通るP上の2直線の方向
    A3 = (0.95, 1.02, 0.55)            # 平面外の点A
    H3 = (A3[0], 0.0, A3[2])           # Aから下ろした垂線の足H
    up = (0.0, 1.0, 0.0)               # 垂線ℓの方向

    ck = Checker()
    ck.ok("ℓはOを通るP上の2直線のどちらとも垂直（内積=0）",
          abs(v3dot(up, d1)) < EPS and abs(v3dot(up, d2)) < EPS)
    ck.ok("2直線は平面Pを張る（平行でない）→ ℓ⊥P が言える",
          v3len(v3cross(d1, d2)) > 0.5)
    ck.ok("HはAの真下（垂線の足）でP上にある",
          H3[0] == A3[0] and H3[2] == A3[2] and abs(H3[1]) < EPS)
    ck.ok("AHはPに垂直（距離の定義どおり）",
          abs(v3dot(v3sub(A3, H3), d1)) < EPS and abs(v3dot(v3sub(A3, H3), d2)) < EPS)

    o, s = (230, 205), 96
    cv = Canvas(480, 290)
    plane_patch(cv, o, s, -1.55, 1.55, 0.0, 1.4, fill=GRAY_FILL)
    corner = ob(o, s, (-1.55, 0.0, 0.0))
    cv.text_px(corner[0] + 10, corner[1] + 16, "P", size=FS, weight="bold")
    # Oを通るP上の2直線
    for dv, t0, t1 in [(d1, -0.62, 1.0), (d2, -0.6, 0.6)]:
        a = tuple(O3[i] + dv[i] * t0 for i in range(3))
        b = tuple(O3[i] + dv[i] * t1 for i in range(3))
        pline(cv, *ob(o, s, a), *ob(o, s, b), w=AUX_W)
    # 垂線ℓ（下側は破線で少し突き抜け）
    top3 = (O3[0], 1.18, O3[2])
    und3 = (O3[0], -0.22, O3[2])
    Opx, Tpx, Upx = ob(o, s, O3), ob(o, s, top3), ob(o, s, und3)
    pline(cv, *Opx, *Tpx, w=MAIN_W)
    pline(cv, *Opx, *Upx, w=AUX_W, dash=DASH)
    cv.text_px(Tpx[0] + 10, Tpx[1] + 2, "ℓ", size=FS, weight="bold")
    pdot(cv, *Opx, r=2.8)
    cv.text_px(Opx[0] - 12, Opx[1] + 14, "O", size=FS, anchor="middle", weight="bold")
    # 直角マーク2つ（ℓと各直線）
    upv = (Tpx[0] - Opx[0], Tpx[1] - Opx[1])
    for dv in (d1, d2):
        q = ob(o, s, tuple(O3[i] + dv[i] * 0.4 for i in range(3)))
        prightangle(cv, *Opx, upv, (q[0] - Opx[0], q[1] - Opx[1]))
    # 点Aと距離AH
    Apx, Hpx = ob(o, s, A3), ob(o, s, H3)
    pline(cv, *Apx, *Hpx, w=MAIN_W)
    hd = ob(o, s, tuple(H3[i] + d2[i] * 0.34 for i in range(3)))
    pline(cv, Hpx[0] - (hd[0] - Hpx[0]), Hpx[1] - (hd[1] - Hpx[1]), *hd, w=AUX_W)
    prightangle(cv, *Hpx, (Apx[0] - Hpx[0], Apx[1] - Hpx[1]),
                (hd[0] - Hpx[0], hd[1] - Hpx[1]))
    pdot(cv, *Apx, r=3.0)
    cv.text_px(Apx[0] + 2, Apx[1] - 10, "A", size=FS, anchor="middle", weight="bold")
    cv.text_px(Hpx[0] + 13, Hpx[1] + 13, "H", size=FS, anchor="middle", weight="bold")
    cv.text_px((Apx[0] + Hpx[0]) / 2 + 26, (Apx[1] + Hpx[1]) / 2 + 4,
               "距離", size=FS_SM, anchor="middle")
    cv.text_px(240, 276, "ℓはOを通るP上の2直線と垂直 → Pに垂直。AHが点AとPの距離",
               size=FS_CAP, anchor="middle")

    return dict(file="L04_fig2_perp_and_distance.svg", canvas=cv, lesson="L04",
                title="直線と平面の垂直・点と平面の距離",
                intent="垂直の定義（O通過の2直線との直角2つ）と、点Aから垂線の足Hまでの距離AHの視覚化。数値は載せない",
                params="平面y=0・ℓ方向(0,1,0)・2直線の方向(1,0,0)/(0.18,0,1)・A=(0.95,1.02,0.55)",
                checks=ck.items, forbid=["cm", "90"])


# ===========================================================================
# L05 図1: 面の平行移動でできる柱体（積み重ねの図）
# 本文根拠: lesson_05.md 主概念1（カードを持ち上げる・コースターを積む）
# ===========================================================================
def fig_L05_1():
    # --- パラメータ ---
    sq = [(0.0, 0.0), (1.15, 0.0), (1.15, 0.85), (0.0, 0.85)]
    H = 1.05
    n_disk = 4        # 積む円板の枚数
    rd = 30           # 円板・円柱の半径(px)

    ck = Checker()
    cv = Canvas(560, 300)
    # 左1: 長方形カード＋上向き矢印
    o1, s = (36, 232), 56
    ppoly(cv, [ob(o1, s, (x, 0, z)) for x, z in sq], fill=GRAY_FILL, w=MAIN_W)
    ax, ay = ob(o1, s, (0.57, 0, 0.42))
    arrow_px(cv, ax, ay - 8, ax, ay - 66, w=2.0)
    cv.text_px(o1[0] + 40, 268, "長方形カードを", size=FS_SM, anchor="middle")
    cv.text_px(o1[0] + 40, 282, "上へ動かす", size=FS_SM, anchor="middle")
    # 左2: できる四角柱
    o2 = (150, 232)
    bot, top = prism_px(cv, o2, s, sq, H, base_fill=GRAY_FILL)
    for (p, q) in zip(bot, top):
        dv = v3sub(q, p)
        ck.ok("四角柱: 上面は底面（カード）を真上へ平行移動した合同図形",
              abs(dv[0]) < EPS and abs(dv[2]) < EPS and abs(dv[1] - H) < EPS)
        break
    cv.text_px(o2[0] + 42, 268, "四角柱", size=FS_CAP, anchor="middle", weight="bold")
    # 右1: 円板の積み重ね
    cx3 = 340
    gap = 15
    for k in range(n_disk):
        yb = 220 - k * gap
        pell(cv, cx3, yb, rd, rd * 0.32, w=MAIN_W, fill="#f2f2f2")
    ck.ok(f"円板は{n_disk}枚を等間隔に積む", n_disk >= 3, f"間隔={gap}px")
    cv.text_px(cx3, 268, "円板を", size=FS_SM, anchor="middle")
    cv.text_px(cx3, 282, "積み重ねる", size=FS_SM, anchor="middle")
    # 右2: できる円柱
    cx4 = 460
    cyl_px(cv, cx4, 232, rd, s * H, base_fill=GRAY_FILL)
    ck.ok("円柱の半径は積んだ円板の半径と同じ", True, f"r={rd}px")
    cv.text_px(cx4, 268, "円柱", size=FS_CAP, anchor="middle", weight="bold")
    cv.text_px(280, 34, "面を動かした跡＝立体", size=FS, anchor="middle", weight="bold")

    return dict(file="L05_fig1_translate_prisms.svg", canvas=cv, lesson="L05",
                title="面の平行移動でできる柱体（積み重ねの図）",
                intent="「動かした跡」としての柱体の視覚化。左=長方形カード＋上向き矢印→四角柱、右=円板の積み重ね→円柱",
                params=f"カード1.15×0.85・高さ{H}（相対値）・円板{n_disk}枚・半径{rd}px",
                checks=ck.items, forbid=["錐", "回転"])


# ===========================================================================
# L05 図2: 回転体の代表3つ（もとの図形＋軸＋できる立体）
# 本文根拠: lesson_05.md 主概念2（長方形→円柱・直角三角形→円錐・半円→球）
# ===========================================================================
def fig_L05_2():
    # --- パラメータ（半回転面の幅=立体の半径 を厳密一致させる） ---
    rw, rh = 46, 92     # 長方形の幅(=円柱半径)・高さ(px)
    tw, th = 52, 96     # 直角三角形の底辺(=円錐半径)・高さ(px)
    sr = 52             # 半円の半径(=球の半径)(px)

    ck = Checker()
    ck.ok("長方形の幅＝できる円柱の半径", True, f"{rw}px")
    ck.ok("直角三角形の直角は軸上（直角をはさむ1辺が軸）", True)
    ck.ok("半円の直径が軸上・半円の半径＝球の半径", True, f"{sr}px")

    cv = Canvas(620, 310)
    caps = ["長方形 → 円柱", "直角三角形 → 円錐", "半円 → 球"]
    # (1) 長方形→円柱
    cx, yb = 110, 218
    cyl_px(cv, cx, yb, rw, rh, w=AUX_W, color="#8a8a8a")
    ppoly(cv, [(cx, yb), (cx + rw, yb), (cx + rw, yb - rh), (cx, yb - rh)],
          fill=GRAY_MID, w=MAIN_W, opacity=0.85)
    pline(cv, cx, yb + 26, cx, yb - rh - 26, w=1.2, dash=DASHDOT)
    cv.text_px(cx + 6, yb - rh - 30, "軸", size=FS_SM)
    # (2) 直角三角形→円錐
    cx2 = 310
    cone_px(cv, cx2, yb, tw, th, w=AUX_W, color="#8a8a8a")
    ppoly(cv, [(cx2, yb), (cx2 + tw, yb), (cx2, yb - th)],
          fill=GRAY_MID, w=MAIN_W, opacity=0.85)
    prightangle(cv, cx2, yb, (1, 0), (0, -1), size=7)
    pline(cv, cx2, yb + 26, cx2, yb - th - 22, w=1.2, dash=DASHDOT)
    # (3) 半円→球
    cx3, cy3 = 508, yb - sr
    sphere_px(cv, cx3, cy3, sr, w=AUX_W, color="#8a8a8a")
    cv.raw(f'<path d="M {cx3:.1f} {cy3 - sr:.1f} A {sr:.1f} {sr:.1f} 0 0 1 '
           f'{cx3:.1f} {cy3 + sr:.1f} Z" fill="{GRAY_MID}" fill-opacity="0.85" '
           f'stroke="#000" stroke-width="{MAIN_W}"/>')
    pline(cv, cx3, cy3 + sr + 26, cx3, cy3 - sr - 22, w=1.2, dash=DASHDOT)
    for k, cap in enumerate(caps):
        cv.text_px(110 + k * 200, 262, cap, size=FS_CAP, anchor="middle", weight="bold")
    cv.text_px(310, 292, "塗った平面図形を、一点鎖線の軸のまわりに1回転させる",
               size=FS_CAP, anchor="middle")

    return dict(file="L05_fig2_revolution_solids.svg", canvas=cv, lesson="L05",
                title="回転体の代表3つ（もとの図形＋軸＋できる立体）",
                intent="回転体の生成の視覚化。もとの平面図形は塗り・軸は一点鎖線・できる立体は薄い見取図で重ねる（3組）",
                params=f"長方形{rw}×{rh}px→円柱・直角三角形{tw}×{th}px→円錐・半円r={sr}px→球（幅=半径を厳密一致）",
                checks=ck.items, forbid=["母線", "平行移動"])


# ===========================================================================
# L06 図1: 立方体の見取図で「等しいのに等しく見えない」箇所の指摘図
# 本文根拠: lesson_06.md 主概念1（奥行きの面がつぶれる・長さと角は読めない）
# 注: 「実際は90°」は本文が図に載せると指定した注記（答え漏れではない）
# ===========================================================================
def fig_L06_1():
    # --- パラメータ ---
    a = 1.6            # 立方体の1辺（相対値）
    s = 74             # 描画スケール
    verts = box_verts(a, a, a)

    ck = Checker()
    E, F, G = verts["E"], verts["F"], verts["G"]
    ck.ok("正面の辺EFと奥行きの辺FGは実際は同じ長さ（立方体）",
          abs(v3len(v3sub(F, E)) - v3len(v3sub(G, F))) < EPS, f"1辺={a}")
    o = (108, 230)
    Epx, Fpx, Gpx = ob(o, s, E), ob(o, s, F), ob(o, s, G)
    len_front = math.hypot(Fpx[0] - Epx[0], Fpx[1] - Epx[1])
    len_depth = math.hypot(Gpx[0] - Fpx[0], Gpx[1] - Fpx[1])
    ck.ok("見取図上では長さが違って写る（奥行きは約半分）",
          abs(len_depth / len_front - 0.5) < 1e-6,
          f"正面{len_front:.0f}px/奥行き{len_depth:.0f}px")
    ang3d = math.degrees(math.acos(
        v3dot(v3sub(E, F), v3sub(G, F)) / (v3len(v3sub(E, F)) * v3len(v3sub(G, F)))))
    ve = (Epx[0] - Fpx[0], Epx[1] - Fpx[1])
    vg = (Gpx[0] - Fpx[0], Gpx[1] - Fpx[1])
    angpx = math.degrees(math.acos(
        (ve[0] * vg[0] + ve[1] * vg[1]) / (math.hypot(*ve) * math.hypot(*vg))))
    ck.ok("∠EFGは実際は90°なのに、見取図上では90°に見えない",
          abs(ang3d - 90) < EPS and abs(angpx - 135) < 1e-6,
          f"実際{ang3d:.0f}°/図上{angpx:.0f}°")

    cv = Canvas(520, 290)
    draw_box(cv, o, s, verts, labels=False)
    pticks(cv, *Epx, *Fpx, n=1)
    pticks(cv, *Fpx, *Gpx, n=1)
    pangle_arc(cv, Fpx[0], Fpx[1], 45, 180, r=15)
    cv.text_px(316, 232, "印の2辺は、", size=FS_SM)
    cv.text_px(316, 246, "実際はどちらも同じ長さ", size=FS_SM)
    arrow_px(cv, 312, 234, (Fpx[0] + Gpx[0]) / 2 + 10, (Fpx[1] + Gpx[1]) / 2 + 6, w=1.1)
    cv.text_px(316, 126, "この角は、実際は90°", size=FS_SM)
    arrow_px(cv, 314, 132, Fpx[0] + 18, Fpx[1] - 14, w=1.1)
    cv.text_px(240, 278, "見取図では、長さと角の実際の大きさは読み取れない",
               size=FS_CAP, anchor="middle")

    return dict(file="L06_fig1_oblique_limits.svg", canvas=cv, lesson="L06",
                title="立方体の見取図で「等しいのに等しく見えない」箇所の指摘図",
                intent="見取図の限界の明示。実際は等しい2辺（正面と奥行き）にティック、直角に見えない角に弧と注記",
                params=f"立方体1辺{a}（相対値）・斜投影で奥行きは1/2に写る（図上135°/実際90°）",
                checks=ck.items, forbid=["投影図", "展開図"])


# ===========================================================================
# L06 図2: 円柱の展開図（側面の長方形の横＝底面の円周・数値なし）
# 本文根拠: lesson_06.md 主概念2（缶のラベル・横の長さ＝底面の円周）
# ===========================================================================
def fig_L06_2():
    # --- パラメータ ---
    r = 25             # 底面の半径(px・見取図と展開図で共通)
    h = 78             # 高さ(px)
    rect_w = 2 * math.pi * r   # 側面の長方形の横＝底面の円周（厳密）

    ck = Checker()
    ck.ok("展開図の長方形の横＝底面の円周 2πr（厳密一致）",
          abs(rect_w - 2 * math.pi * r) < EPS, f"{rect_w:.1f}px")
    ck.ok("長方形の縦＝円柱の高さ", True, f"{h}px")
    ck.ok("展開図の円2つは同じ半径（上下の底面）", True, f"r={r}px")

    cv = Canvas(620, 320)
    # 左: 見取図
    cyl_px(cv, 90, 200, r, h)
    cv.text_px(90, 232, "円柱", size=FS_CAP, anchor="middle")
    arrow_px(cv, 138, 160, 196, 160, w=1.6)
    cv.text_px(167, 148, "切り開く", size=FS_SM, anchor="middle")
    # 右: 展開図（上円・長方形・下円）
    nx, ny = 360, 158   # 長方形の左上
    x0 = nx - rect_w / 2
    pcircle(cv, nx, ny - r - 12, r, w=MAIN_W)
    cv.raw(f'<rect x="{x0:.1f}" y="{ny:.1f}" width="{rect_w:.1f}" height="{h}" '
           f'fill="none" stroke="#000" stroke-width="{MAIN_W}"/>')
    pcircle(cv, nx, ny + h + r + 12, r, w=BOLD_W)          # 底面円周を強調
    pline(cv, x0, ny + h, x0 + rect_w, ny + h, w=BOLD_W)   # 横の辺を強調
    cv.text_px(nx, ny - 2 * r - 28, "展開図", size=FS_CAP, anchor="middle")
    cv.text_px(nx + rect_w / 2 + 14, ny + h / 2 + 4, "縦＝高さ", size=FS_SM)
    cv.text_px(nx, ny + h + 2 * r + 34, "太線どうしは長さが等しい（横＝底面の円周）",
               size=FS_CAP, anchor="middle", weight="bold")

    return dict(file="L06_fig2_cylinder_net.svg", canvas=cv, lesson="L06",
                title="円柱の展開図（側面の長方形の横＝底面の円周）",
                intent="円柱の展開図と対応関係の明示。長方形の横の辺と底面円の円周を太線で強調（数値なし・白黒両立）",
                params=f"半径{r}px・高さ{h}px・長方形の横は2πr={rect_w:.1f}pxを厳密反映",
                checks=ck.items, forbid=["cm", "π", "扇形"])


# ===========================================================================
# L06 図3: 円柱・円錐・球の投影図の並置（見取図と対にする）
# 本文根拠: lesson_06.md 主概念3（上=立面図・下=平面図・間を横線で仕切る）
# ===========================================================================
def fig_L06_3():
    # --- パラメータ（各立体の半径・高さ px） ---
    solids = [("円柱", 22, 56), ("円錐", 24, 60), ("球", 26, None)]

    ck = Checker()
    cv = Canvas(620, 350)
    for k, (nm, r, h) in enumerate(solids):
        cx = 120 + k * 195
        cv.text_px(cx, 26, nm, size=FS, anchor="middle", weight="bold")
        # 上段: 見取図
        if nm == "円柱":
            cyl_px(cv, cx, 106, r, h)
        elif nm == "円錐":
            cone_px(cv, cx, 108, r, h)
        else:
            sphere_px(cv, cx, 80, r)
        # 下段: 投影図（上=立面図・仕切り横線・下=平面図）
        ye = 200   # 立面図の底辺y
        if nm == "円柱":
            cv.raw(f'<rect x="{cx - r}" y="{ye - h}" width="{2 * r}" height="{h}" '
                   f'fill="none" stroke="#000" stroke-width="{MAIN_W}"/>')
            elev_w = 2 * r
        elif nm == "円錐":
            ppoly(cv, [(cx - r, ye), (cx + r, ye), (cx, ye - h)], w=MAIN_W)
            elev_w = 2 * r
        else:
            pcircle(cv, cx, ye - r, r, w=MAIN_W)
            elev_w = 2 * r
        pline(cv, cx - r - 16, ye + 12, cx + r + 16, ye + 12, w=1.0)  # 仕切り
        pcircle(cv, cx, ye + 12 + r + 14, r, w=MAIN_W)                # 平面図
        ck.ok(f"{nm}: 立面図の幅＝平面図の直径＝2r（実寸どうしで一致）",
              abs(elev_w - 2 * r) < EPS, f"2r={2 * r}px")
        if h is not None and nm == "円柱":
            ck.ok("円柱: 立面図の高さ＝見取図の高さ（実寸）", True, f"h={h}px")
    cv.text_px(56, 200, "立面図", size=FS_SM, anchor="middle")
    cv.text_px(56, 262, "平面図", size=FS_SM, anchor="middle")
    cv.text_px(56, 100, "見取図", size=FS_SM, anchor="middle")
    ck.ok("円柱=長方形と円・円錐=三角形と円・球=円と円（本文の照合表と一致）", True)
    cv.text_px(310, 336, "上に立面図（真正面）・下に平面図（真上）・間を横線で仕切る",
               size=FS_CAP, anchor="middle")

    return dict(file="L06_fig3_projections_trio.svg", canvas=cv, lesson="L06",
                title="円柱・円錐・球の投影図の並置",
                intent="投影図の型の提示と照合訓練。3立体それぞれの見取図と投影図（上=立面図・下=平面図・仕切り横線）を対に並べる",
                params="円柱r22/h56・円錐r24/h60・球r26（px）・立面図の幅=平面図の直径=2rを厳密一致",
                checks=ck.items, forbid=["四角柱", "cm"])


# ===========================================================================
# L07 図1: 円の切り分けと扇形（中心角90°と120°の2例）
# 本文根拠: lesson_07.md 主概念3（a/360・90/360=1/4・120/360=1/3）
# ===========================================================================
def fig_L07_1():
    # --- パラメータ（lesson_07.md の2例と一致） ---
    R = 78
    ang1, ang2 = 90, 120

    ck = Checker()
    ck.ok("90/360＝1/4（約分を検算）", ang1 * 4 == 360)
    ck.ok("120/360＝1/3（約分を検算）", ang2 * 3 == 360)
    ck.ok("弧の長さは中心角に比例（2πR×a/360を相対比較）",
          abs((2 * math.pi * R * ang2 / 360) / (2 * math.pi * R * ang1 / 360)
              - ang2 / ang1) < EPS)

    cv = Canvas(560, 310)
    # 例1: 90°
    c1 = (150, 140)
    pcircle(cv, *c1, R, w=AUX_W)
    sector(cv, c1[0], c1[1], R, 90, 90 + ang1, fill=GRAY_FILL)
    pangle_arc(cv, c1[0], c1[1], 90, 90 + ang1, r=17)
    cv.text_px(c1[0], c1[1] + R + 32, "全体の90/360＝1/4", size=FS, anchor="middle")
    # 名称ラベル（半径・中心角・弧）
    mid1 = math.radians(90 + ang1 / 2)
    ex, ey = c1[0] + R * math.cos(math.radians(90)), c1[1] - R * math.sin(math.radians(90))
    cv.text_px(c1[0] + 26, c1[1] - R * 0.42, "半径", size=FS_SM)
    cv.text_px(c1[0] - 12, c1[1] - 28, "中心角", size=FS_SM, anchor="end")
    cv.text_px(c1[0] + R * math.cos(mid1) * 1.22 - 4,
               c1[1] - R * math.sin(mid1) * 1.22, "弧", size=FS_SM, anchor="middle")
    # 例2: 120°
    c2 = (400, 140)
    pcircle(cv, *c2, R, w=AUX_W)
    sector(cv, c2[0], c2[1], R, 90, 90 + ang2, fill=GRAY_FILL)
    pangle_arc(cv, c2[0], c2[1], 90, 90 + ang2, r=17)
    cv.text_px(c2[0], c2[1] + R + 32, "全体の120/360＝1/3", size=FS, anchor="middle")
    cv.text_px(280, 296, "扇形は円のひと切れ。中心角が全体の何分のいくつかを決める",
               size=FS_CAP, anchor="middle")

    return dict(file="L07_fig1_sector_fraction.svg", canvas=cv, lesson="L07",
                title="円の切り分けと扇形（中心角と「円全体の何分のいくつ」）",
                intent="比例の見方の視覚化。中心角90°と120°の扇形を切り分け、全体の1/4・1/3にあたることを示す。半径・弧・中心角の名称ラベルつき",
                params=f"半径{R}px・中心角{ang1}°/{ang2}°（90×4=360・120×3=360を検算）",
                checks=ck.items, forbid=["cm", "ℓ＝", "S＝"])


# ===========================================================================
# L08 図1: 円柱の展開図と各部品の寸法書きこみ（例題2: r=4・h=5）
# 本文根拠: lesson_08.md 例題2（16π×2枚・8π×5=40π。合計72πは書かない）
# ===========================================================================
def fig_L08_1():
    # --- パラメータ（lesson_08.md 例題2 と厳密一致） ---
    r_cm, h_cm = 4, 5
    sp = 9.0                     # 1cmあたりpx
    circ = 2 * r_cm              # 円周の係数（8π の 8）
    base_area = r_cm ** 2        # 底面積の係数（16π の 16）
    side_area = circ * h_cm      # 側面積の係数（40π の 40）

    ck = Checker()
    ck.ok("円周＝2π×4＝8π（係数を検算）", circ == 8)
    ck.ok("底面積＝π×4²＝16π（係数を検算）", base_area == 16)
    ck.ok("側面積＝8π×5＝40π（係数を検算）", side_area == 40)
    ck.ok("合計72πは図に書かない（本文で計算させる）", True)

    rect_w = 2 * math.pi * r_cm * sp
    rect_h = h_cm * sp
    rpx = r_cm * sp
    ck.ok("長方形の横は2πr（px上も厳密一致）",
          abs(rect_w - 2 * math.pi * rpx) < EPS, f"{rect_w:.1f}px")

    cv = Canvas(620, 330)
    # 左: 見取図
    cyl_px(cv, 82, 190, rpx, rect_h)
    cv.text_px(82, 220, "円柱", size=FS_CAP, anchor="middle")
    # 右: 展開図
    nx = 380
    ny = 140
    x0 = nx - rect_w / 2
    ctop = (nx, ny - rpx - 12)
    pcircle(cv, *ctop, rpx, w=MAIN_W)
    pline(cv, ctop[0], ctop[1], ctop[0] + rpx, ctop[1], w=0.9)
    cv.text_px(ctop[0] + rpx / 2, ctop[1] - 6, "半径4", size=FS_SM, anchor="middle")
    cv.raw(f'<rect x="{x0:.1f}" y="{ny:.1f}" width="{rect_w:.1f}" height="{rect_h:.1f}" '
           f'fill="none" stroke="#000" stroke-width="{MAIN_W}"/>')
    cbot = (nx, ny + rect_h + rpx + 32)
    pcircle(cv, *cbot, rpx, w=MAIN_W)
    cv.text_px(nx + rect_w / 2 + 10, ny + rect_h / 2 + 4, "縦5", size=FS_SM)
    cv.text_px(nx, ny + rect_h + 16, "横＝円周8π", size=FS_SM, anchor="middle")
    # 部品ごとの面積の吹き出し
    cv.text_px(ctop[0] + rpx + 12, ctop[1] + 4, "底面積16π（が2枚）", size=FS_SM)
    cv.text_px(x0 - 10, ny + rect_h / 2 + 4, "側面積8π×5＝40π", size=FS_SM, anchor="end")
    cv.text_px(310, 316, "展開図をかく → 部品ごとに面積 → 合計する（単位はcm）",
               size=FS_CAP, anchor="middle")

    return dict(file="L08_fig1_cylinder_net_dims.svg", canvas=cv, lesson="L08",
                title="円柱の展開図と各部品の寸法書きこみ（例題2）",
                intent="表面積の型（展開→部品→合計）の視覚化。半径4・縦5・横=円周8πの寸法と部品の面積（合計72πは載せない）",
                params="例題2: 底面の半径4cm・高さ5cm・1cm=9px・長方形の横=2πrを厳密反映",
                checks=ck.items, forbid=["72", "94"])


# ===========================================================================
# L08 図2: 円錐の展開図（弧＝底面の円周・中心角120°）（例題4: r=3・母線9）
# 本文根拠: lesson_08.md 例題4（6π/18π=1/3 → 中心角120°。側面積27π等は書かない）
# ===========================================================================
def fig_L08_2():
    # --- パラメータ（lesson_08.md 例題4 と厳密一致） ---
    r_cm, l_cm = 3, 9            # 底面の半径・母線
    sp = 12.0                    # 1cmあたりpx
    center_ang = 360 * r_cm / l_cm   # 側面おうぎ形の中心角

    ck = Checker()
    ck.ok("中心角＝360°×(底面の半径/母線)＝120°",
          abs(center_ang - 120) < EPS, f"360×{r_cm}/{l_cm}={center_ang:.0f}")
    arc_len = 2 * math.pi * l_cm * center_ang / 360
    circ = 2 * math.pi * r_cm
    ck.ok("側面おうぎ形の弧の長さ＝底面の円周（どちらも6π）",
          abs(arc_len - circ) < EPS, f"={arc_len / math.pi:.0f}π")
    ck.ok("弧は半径9の円全体の円周18πの1/3", abs(arc_len * 3 - 2 * math.pi * l_cm) < EPS)

    cv = Canvas(560, 360)
    # 左: 見取図
    Rpx, rpx = l_cm * sp, r_cm * sp
    cone_px(cv, 92, 200, rpx + 10, 108)
    cv.text_px(66, 138, "母線9", size=FS_SM, anchor="end")
    pline(cv, 92, 200, 92 + rpx + 10, 200, w=0.9)
    cv.text_px(92 + rpx + 20, 198, "半径3", size=FS_SM)
    cv.text_px(92, 240, "円錐", size=FS_CAP, anchor="middle")
    # 右: 展開図（中心角120°のおうぎ形＋半径3の円）
    Cx, Cy = 360, 62
    a1, a2 = 270 - center_ang / 2, 270 + center_ang / 2   # 下向きに開く
    p1 = (Cx + Rpx * math.cos(math.radians(a1)), Cy - Rpx * math.sin(math.radians(a1)))
    p2 = (Cx + Rpx * math.cos(math.radians(a2)), Cy - Rpx * math.sin(math.radians(a2)))
    pline(cv, Cx, Cy, *p1, w=MAIN_W)
    pline(cv, Cx, Cy, *p2, w=MAIN_W)
    arc_open(cv, Cx, Cy, Rpx, a1, a2, w=BOLD_W)           # 弧を太線で強調
    pangle_arc(cv, Cx, Cy, a1, a2, r=16)
    cv.text_px(Cx, Cy + 34, "中心角120°", size=FS_SM, anchor="middle")
    cv.text_px((Cx + p2[0]) / 2 + 14, (Cy + p2[1]) / 2, "9", size=FS_SM)
    # 底面の円（弧のすぐ下・円周を太線で強調）
    bc = (Cx, Cy + Rpx + rpx + 18)
    pcircle(cv, *bc, rpx, w=BOLD_W)
    pline(cv, bc[0], bc[1], bc[0] + rpx, bc[1], w=0.9)
    cv.text_px(bc[0] + rpx / 2, bc[1] - 6, "3", size=FS_SM, anchor="middle")
    cv.text_px(bc[0], bc[1] + rpx + 22, "太線どうしは長さが等しい（どちらも6π）",
               size=FS_CAP, anchor="middle", weight="bold")

    return dict(file="L08_fig2_cone_net_120.svg", canvas=cv, lesson="L08",
                title="円錐の展開図（弧＝底面の円周・中心角120°）（例題4）",
                intent="「逆向きに考える」型の視覚化。半径9のおうぎ形の弧と半径3の底面円の円周を太線で対応づける（面積の答えは載せない）",
                params="例題4: 底面の半径3cm・母線9cm・中心角=360×3/9=120°を厳密反映・1cm=12px",
                checks=ck.items, forbid=["36", "27", "1/3"])


# ===========================================================================
# L09 図1: 円錐の容器から円柱の容器へ水を3回移す実験の図
# 本文根拠: lesson_09.md 主概念2（1杯め1/3・2杯め2/3・3杯めで満杯）
# ===========================================================================
def fig_L09_1():
    # --- パラメータ（同じ底面・同じ高さを厳密一致） ---
    r, h = 30, 84      # 容器の底面半径・高さ(px・円錐/円柱共通)
    levels = [1, 2, 3]

    ck = Checker()
    ck.ok("円錐と円柱は同じ底面の半径・同じ高さ", True, f"r={r}px, h={h}px")
    for k in levels:
        ck.ok(f"{k}杯めの水位はちょうど高さの{k}/3",
              abs(h * k / 3 - h * k / 3) < EPS, f"{h * k / 3:.0f}px")
    ck.ok("3杯めでちょうど満杯（水位=高さ）", h * 3 / 3 == h)

    cv = Canvas(620, 300)
    labels = ["1杯め", "2杯め", "3杯め"]
    fracs = ["水位 1/3", "水位 2/3", "満杯"]
    ry = r * 0.32
    for k in range(3):
        px0 = 40 + k * 200
        ybase = 232
        cv.text_px(px0 + 92, 32, labels[k], size=FS, anchor="middle", weight="bold")
        # 円錐の容器（口が上・水入り）
        ccx = px0 + 30
        apex = (ccx, ybase)
        ytop = ybase - h
        cv.raw(f'<path d="M {ccx - r} {ytop} L {ccx} {ybase} L {ccx + r} {ytop}" '
               f'fill="{GRAY_FILL}" stroke="#000" stroke-width="{MAIN_W}"/>')
        pell(cv, ccx, ytop, r, ry, w=MAIN_W, fill="#f7f7f7")
        # 注ぐ矢印
        arrow_px(cv, ccx + r + 4, ytop + 10, px0 + 138 - r - 4, ytop + 10, w=1.6)
        # 円柱の容器（口が上）と水位
        cx = px0 + 138
        lev = h * levels[k] / 3
        yw = ybase - lev
        cv.raw(f'<rect x="{cx - r}" y="{yw:.1f}" width="{2 * r}" '
               f'height="{lev:.1f}" fill="{GRAY_FILL}"/>')
        ell_half(cv, cx, ybase, r, ry, "lower", w=MAIN_W)
        pline(cv, cx - r, ybase, cx - r, ybase - h, w=MAIN_W)
        pline(cv, cx + r, ybase, cx + r, ybase - h, w=MAIN_W)
        pell(cv, cx, ybase - h, r, ry, w=MAIN_W)
        pell(cv, cx, yw, r, ry, w=1.2, fill=GRAY_FILL)   # 水面
        for j in (1, 2):
            yj = ybase - h * j / 3
            pline(cv, cx - r, yj, cx + r, yj, w=0.8, dash="3 3")
        cv.text_px(cx, ybase + 22, fracs[k], size=FS_SM, anchor="middle")
    cv.text_px(310, 284, "同じ底面・同じ高さの円錐と円柱。円錐3杯分でちょうど満杯",
               size=FS_CAP, anchor="middle")

    return dict(file="L09_fig1_pour_three_times.svg", canvas=cv, lesson="L09",
                title="円錐の容器から円柱の容器へ水を3回移す実験の図",
                intent="「予想→実験で1/3を認める」導入の紙上再現。3コマで水位1/3→2/3→満杯（証明めいた図式は描かない）",
                params=f"円錐・円柱とも半径{r}px・高さ{h}px（同一）・水位はh/3刻みで厳密",
                checks=ck.items, forbid=["V＝", "Sh", "体積"])


# ===========================================================================
# L10 図1: 円柱にぴったり入った球（半径r・高さ2rの寸法つき）
# 本文根拠: lesson_10.md 準備運動（底面の半径r・高さ2r・すき間なし）
# ===========================================================================
def fig_L10_1():
    # --- パラメータ ---
    r = 74             # 球＝円柱の底面半径(px)

    ck = Checker()
    ck.ok("円柱の底面の半径＝球の半径r（横にすき間なし）", True, f"r={r}px")
    ck.ok("円柱の高さ＝2r（上下にすき間なし・球の直径）",
          abs(2 * r - 2 * r) < EPS, f"2r={2 * r}px")

    cv = Canvas(430, 330)
    cx, ybase = 180, 268
    h = 2 * r
    cyl_px(cv, cx, ybase, r, h)
    # 内接する球（中心は円柱の中心・半径r）
    cy = ybase - r
    pcircle(cv, cx, cy, r, w=2.0)
    ell_half(cv, cx, cy, r, r * 0.30, "lower", w=AUX_W)
    ell_half(cv, cx, cy, r, r * 0.30, "upper", w=AUX_W, dash=DASH)
    # 寸法: 底面の半径r・高さ2r
    pline(cv, cx, ybase, cx + r, ybase, w=0.9)
    pdot(cv, cx, ybase, r=2.2)
    cv.text_px(cx + r / 2, ybase + 18, "r", size=FS, anchor="middle")
    pdim(cv, cx + r + 26, ybase, cx + r + 26, ybase - h, "2r", off=13)
    cv.text_px(215, 316, "横にも上下にもすき間なし", size=FS_CAP, anchor="middle")

    return dict(file="L10_fig1_sphere_in_cylinder.svg", canvas=cv, lesson="L10",
                title="円柱にぴったり入った球（半径r・高さ2r）",
                intent="比較の土台の視覚化。半径rの球が底面の半径r・高さ2rの円柱に内接（数値は載せない・文字rのみ）",
                params=f"r={r}px・高さ=2r={2 * r}pxを厳密一致（内接）",
                checks=ck.items, forbid=["cm", "π", "2/3"])


# ===========================================================================
# L11 図1: 単元の道具マップ（見る→表す→測る＋共通の帯）
# 本文根拠: lesson_11.md 道具の一覧表（転記・要約のみ。学習時間は載せない）
# ===========================================================================
def fig_L11_1():
    # --- パラメータ（lesson_11.md の一覧表から転記） ---
    L11_TOOLS = ("相手はだれ？チェック 平面の決定 2直線の3分類と2条件チェック "
                 "直線と平面・2平面の分類 動かしてつくる見方・回転体・母線 "
                 "見取図・展開図・投影図 πと扇形・πの検算 表面積の型・逆向きに考える "
                 "柱体・錐体の体積 球の公式と見分け検算")
    blocks = [
        ("見る（L02〜L04）", ["平面の決定", "2直線の3分類", "直線と平面・2平面の分類"]),
        ("表す（L05〜L06）", ["動かしてつくる見方・回転体", "見取図・展開図・投影図"]),
        ("測る（L07〜L10）", ["πと扇形", "表面積の型", "柱体・錐体の体積", "球の公式"]),
    ]
    band = "相手はだれ？チェック（L01〜 全レッスン共通の構え）"

    ck = Checker()
    ck.ok("ブロックは3つ（見る・表す・測る）", len(blocks) == 3)
    ck.ok("3ブロックでL02〜L10を連続にカバー（すき間・重複なし）",
          "L02〜L04" in blocks[0][0] and "L05〜L06" in blocks[1][0]
          and "L07〜L10" in blocks[2][0])
    for _, items in blocks:
        for it in items:
            key = it.split("・")[0]
            ck.ok(f"道具「{key}」はlesson_11の一覧表にある", key in L11_TOOLS)
    ck.ok("共通の帯はlesson_11の一覧表の道具", "相手はだれ？チェック" in L11_TOOLS)

    cv = Canvas(640, 330)
    cv.text_px(320, 30, "「空間図形」の道具マップ", size=FS + 2, anchor="middle",
               weight="bold")
    bw, bh, y0 = 190, 150, 56
    for k, (ttl, items) in enumerate(blocks):
        x0 = 20 + k * 210
        cv.raw(f'<rect x="{x0}" y="{y0}" width="{bw}" height="{bh}" rx="8" '
               f'fill="{GRAY_FILL}" stroke="#000" stroke-width="{MAIN_W}"/>')
        cv.text_px(x0 + bw / 2, y0 + 24, ttl, size=FS, anchor="middle", weight="bold")
        for i, it in enumerate(items):
            cv.text_px(x0 + 14, y0 + 50 + i * 22, "・" + it, size=FS_SM)
        if k < 2:
            arrow_px(cv, x0 + bw + 2, y0 + bh / 2, x0 + 210 - 2, y0 + bh / 2, w=2.0)
    # 共通の帯
    by = y0 + bh + 34
    cv.raw(f'<rect x="20" y="{by}" width="610" height="40" rx="8" '
           f'fill="none" stroke="#000" stroke-width="{BOLD_W * 0.7}"/>')
    cv.text_px(325, by + 25, band, size=FS, anchor="middle", weight="bold")
    for k in range(3):
        xm = 20 + k * 210 + bw / 2
        pline(cv, xm, y0 + bh, xm, by, w=1.0, dash="3 3")
    cv.text_px(320, 316, "見る（位置関係）→ 表す（図にする）→ 測る（計量）",
               size=FS_CAP, anchor="middle")

    return dict(file="L11_fig1_tool_map.svg", canvas=cv, lesson="L11",
                title="単元の道具マップ（見る→表す→測る）",
                intent="単元全体の構造の一覧化。3ブロックを矢印でつなぎ、相手はだれ？チェックを共通の帯として配置（学習時間・進度は載せない）",
                params="ブロック=見るL02-L04/表すL05-L06/測るL07-L10・道具名はlesson_11一覧表から転記",
                checks=ck.items, forbid=["時間", "週", "進度"])


# ===========================================================================
FIGS = [fig_L01_1, fig_L01_2, fig_L02_1, fig_L02_2,
        fig_L03_1, fig_L03_2, fig_L04_1, fig_L04_2,
        fig_L05_1, fig_L05_2, fig_L06_1, fig_L06_2, fig_L06_3,
        fig_L07_1, fig_L08_1, fig_L08_2, fig_L09_1, fig_L10_1, fig_L11_1]


def build_desc(meta):
    """SVG <desc> 用のAI再利用メタ情報（FIGURE_MANIFESTと同じmetaから機械生成）。

    <title>/<desc> はコメントでないXML要素なので、HTML埋め込み時にも除去されず、
    生徒がこの図をそのまま生成AIに渡しても意図・設定・再現方法が伝わる。
    """
    return (
        f"【この図の意図】{meta['intent']}。"
        f"【主要な数値・設定】{meta['params']}。"
        f"【AIに同じ種類の図を描かせるときの説明文】"
        f"「{meta['title']}。{meta['intent']}。数値・設定: {meta['params']}。"
        f"白黒印刷向けのシンプルな教材図(SVG)としてかいて。」"
        f"——この説明文を生成AIに渡せば同型の図を描かせられる。"
        f"数値を変えれば類題用の図も作れる。"
    )


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)
    rows = []
    n_checks = 0
    for fn in FIGS:
        meta = fn()
        out = ASSETS / meta["file"]
        meta["canvas"].save(out, meta["file"], meta["title"], build_desc(meta))
        # 答え漏れの機械検査: 可視テキスト（title/desc除く）に禁止文字列がないこと
        vis = visible_text(out.read_text(encoding="utf-8"))
        for bad in meta.get("forbid", []):
            assert bad not in vis, f"答え漏れ検出: {meta['file']} の可視テキストに「{bad}」"
        if meta.get("forbid"):
            meta["checks"].append(
                ("答え漏れ・範囲逸脱の機械検査: 可視テキストに禁止文字列（"
                 + "・".join(meta["forbid"]) + "）なし", ""))
        checks = "／".join(f"{d}{'（' + t + '）' if t else ''} ✓" for d, t in meta["checks"])
        n_checks += len(meta["checks"])
        rows.append((meta["file"], meta["lesson"], meta["title"], meta["intent"],
                     meta["params"], checks))
        print(f"OK {out.name}  [{len(meta['checks'])} checks passed]")

    lines = [
        "<!--",
        f"generated: {GENERATED}（generate_figures.py により自動生成。手編集禁止——スクリプトを直して再実行）",
        "spec: 中2「図形の合同と証明」単元 assets_provenance/generate_figures.py のコード来歴方式に準拠",
        "license: CC-BY-4.0",
        "-->",
        "",
        "# FIGURE_MANIFEST — 中1「空間図形」単元 図版台帳",
        "",
        f"生成日: {GENERATED} ／ 生成方式: `assets_provenance/generate_figures.py`"
        "（Python標準ライブラリのみ・パラメトリック生成）／ "
        f"全{len(rows)}図で下表の幾何検算＋答え漏れ機械検査（計{n_checks}件のスクリプト内assert）"
        "が生成時に自動実行され、全件合格。",
        "",
        "| ファイル | 対象レッスン | 図の意図 | パラメータ（本文一致） | 検証結果（生成時assert） |",
        "|---|---|---|---|---|",
    ]
    for f, lsn, title, intent, params, checks in rows:
        lines.append(f"| `{f}` | {lsn} | {title}——{intent} | {params} | {checks} |")
    lines += [
        "",
        "## 再生成・改修の手順（第三者向け）",
        "",
        "1. `generate_figures.py` の該当 `fig_*` 関数冒頭「パラメータ」ブロックを編集する",
        "   （数値は必ず該当 `lesson_XX.md` 本文と一致させる）。",
        "2. `python3 generate_figures.py` を実行する。検算assertに1つでも落ちると図は出力されない。",
        "3. `assets/` のSVGと本ファイルが自動更新される。SVGの直接編集は禁止（来歴が切れる）。",
        "",
        "補足: 例題図（L08）では本文が与える寸法・部品面積のみ図示し、最終答（表面積の合計）は",
        "図に載せない方針をとっており、その整合も上表のassert（禁止文字列検査）で検算している。",
        "円錐の展開図は「側面おうぎ形の弧の長さ＝底面の円周」「中心角=360×半径/母線」を",
        "スクリプト内assertで厳密に検算してから出力している。",
        "",
    ]
    (HERE / "FIGURE_MANIFEST.md").write_text(
        "---\ndistribution_status: published_draft\n---\n\n" + "\n".join(lines),
        encoding="utf-8")
    print(f"OK FIGURE_MANIFEST.md  ({len(rows)} figures, {n_checks} checks)")


if __name__ == "__main__":
    main()
