blank_issues_enabled: false
contact_links:
  - name: おたよりフォーム（GitHubアカウント不要・匿名OK）
    url: https://docs.google.com/forms/d/e/1FAIpQLSeKBOQ9EB_DGfkh7Y0LYU83w6ghkPTQfH65BSFjVVWtwEEt9Q/viewform
    about: アカウントがなくても送れます。名前不要・匿名OK。名前・学校名・住所などの個人情報は書かないでください
