#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
"""
generate_figures.py — 高1数学I「二次関数」単元 図版パラメトリック生成スクリプト
==============================================================================
様式: docs/SPEC_figures.md に準拠（内部規約の要旨は同SPECに反映済み。SVGに<title>/<desc>のAI再利用メタ情報を埋め込み）。
ヘルパー群（Canvas/矢印/Checker/座標平面/軸描画ほか）は先行単元
production/jhs-math-3-function-y-ax2/candidate_draft/assets_provenance/generate_figures.py
からコピー再利用（元スクリプトは無変更）。

- 実行: python3 generate_figures.py
- 出力: ../assets/L{NN}_fig{n}_{slug}.svg（22枚）と FIGURE_MANIFEST.md（この階層・自動生成）
- 依存: Python標準ライブラリのみ（math / datetime / html / pathlib / re / xml.etree）
- 本単元は【図:】プレースホルダなしの旧様式のため、図の選定は図表積極採用の判断基準
  （3文以上の文章説明が続く概念・手順・対比＝目が滑る箇所）で新規に行った。
  各 fig_* 関数の docstring に選定根拠（本文の該当箇所）を記す。
- 数学の自己検証: 各 fig_* 関数内の Checker が assert 相当の検算を行い、
  1つでも失敗すると例外で停止して図を出力しない。通過点・頂点・共有点・
  変域端点・区間内最小の位置はすべて式から座標計算し、本文の値と照合する。
- 答えの分離方針: 近隣の設問（練習・stretch）が問う値は図に書かない。
  各図に答え漏れ検査トークン（check_tokens・検査の実装定数）を持たせ、生成後のSVG本文に対して機械検査する。
  図中に書く数値は、いずれも本文（例題の解答・与件）が明示している値に限る。
- 改修方法（第三者向け）: 各 fig_* 関数冒頭の「パラメータ」ブロックの数値を変えて
  再実行する。数値は該当レッスン本文（candidate_draft/lesson_XX.md）と一致させること。
"""

import math
import datetime
import re
import xml.etree.ElementTree as ET
from html import escape
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent / "assets"
GENERATED = datetime.date.today().isoformat()

# ---- 様式定数（docs/SPEC_figures.md） ----------------------------------
MAIN_W = 1.6      # 主線幅
BOLD_W = 3.2      # 強調線幅
AUX_W = 1.1       # 補助線幅
DASH = "6 4"      # 破線
FS = 13           # 基本文字サイズ(px)
FS_NUM = 11       # 軸の目盛数値
DOT_R = 2.5       # 点マーカー半径
DOT_R_END = 3.4   # 端点●○はやや大きく
GRID_C = "#bbb"   # 方眼の線色
SHADE = "#ddd"    # うすい網かけ


# ===========================================================================
# 描画ヘルパー（数学座標: y上向き → SVG座標: y下向き）
# 先行単元 jhs-math-3-function-y-ax2 の generate_figures.py からコピー再利用。
# ===========================================================================
class Canvas:
    def __init__(self, width, height, sx=1.0, sy=None, ox=0.0, oy=0.0):
        """sx/sy: 数学単位→px（syを省略するとsx=sy）、(ox,oy): 数学原点のSVG座標"""
        self.w, self.h = width, height
        self.sx = sx
        self.sy = sx if sy is None else sy
        self.ox, self.oy = ox, oy
        self.defs = []
        self.body = []

    def P(self, p):
        return (self.ox + self.sx * p[0], self.oy - self.sy * p[1])

    def raw(self, s):
        self.body.append(s)

    def line(self, a, b, w=MAIN_W, dash=None, color="#000"):
        (x1, y1), (x2, y2) = self.P(a), self.P(b)
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.raw(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
                 f'stroke="{color}" stroke-width="{w}"{d}/>')

    def polyline(self, pts, w=MAIN_W, dash=None):
        s = " ".join(f"{x:.1f},{y:.1f}" for x, y in map(self.P, pts))
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.raw(f'<polyline points="{s}" fill="none" stroke="#000" '
                 f'stroke-width="{w}"{d} stroke-linejoin="round"/>')

    def dot(self, p, r=DOT_R):
        x, y = self.P(p)
        self.raw(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="#000"/>')

    def open_dot(self, p, r=DOT_R_END):
        """端点○（その点をふくまない）——白抜き+黒縁"""
        x, y = self.P(p)
        self.raw(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r}" fill="#fff" '
                 f'stroke="#000" stroke-width="1.4"/>')

    def text(self, p, s, size=FS, anchor="middle", dy=0.35, weight=None):
        x, y = self.P(p)
        wgt = f' font-weight="{weight}"' if weight else ""
        self.raw(f'<text x="{x:.1f}" y="{y + size * dy:.1f}" font-size="{size}" '
                 f'text-anchor="{anchor}"{wgt}>{escape(s)}</text>')

    def text_px(self, x, y, s, size=FS, anchor="start", weight=None):
        wgt = f' font-weight="{weight}"' if weight else ""
        self.raw(f'<text x="{x:.1f}" y="{y:.1f}" font-size="{size}" '
                 f'text-anchor="{anchor}"{wgt}>{escape(s)}</text>')

    def save(self, path, fig_id, title, desc=None):
        defs = f"<defs>{''.join(self.defs)}</defs>" if self.defs else ""
        svg = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.w} {self.h}">\n'
            f'<title>{escape(title)}</title>\n'
            + (f'<desc>{escape(desc)}</desc>\n' if desc else "") +
            f'<!-- {fig_id} | {title} -->\n'
            f'<!-- generated by assets_provenance/generate_figures.py on {GENERATED} '
            f'(docs/SPEC_figures.md準拠（内部規約の要旨は同SPECに反映済み）・SVG直接編集禁止/スクリプト改修で再生成) -->\n'
            f'<rect x="0" y="0" width="{self.w}" height="{self.h}" fill="#fff"/>\n'
            + defs + "\n".join(self.body) + "\n</svg>\n"
        )
        path.write_text(svg, encoding="utf-8")


def arrow_px(cv, x1, y1, x2, y2, w=1.4, head=7.0):
    """SVG座標(px)で矢印（線+先端の三角形）を描く"""
    ang = math.atan2(y2 - y1, x2 - x1)
    bx, by = x2 - head * math.cos(ang), y2 - head * math.sin(ang)
    cv.raw(f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{bx:.1f}" y2="{by:.1f}" '
           f'stroke="#000" stroke-width="{w}"/>')
    nx, ny = -math.sin(ang), math.cos(ang)
    cv.raw(f'<polygon points="{x2:.1f},{y2:.1f} '
           f'{bx + nx * head * 0.45:.1f},{by + ny * head * 0.45:.1f} '
           f'{bx - nx * head * 0.45:.1f},{by - ny * head * 0.45:.1f}" fill="#000"/>')


class Checker:
    """数学検算の記録つきassert"""
    def __init__(self):
        self.items = []

    def ok(self, desc, cond, detail=""):
        assert cond, f"検証失敗: {desc} {detail}"
        self.items.append((desc, detail))


def plane(xr, yr, sx, sy=None, ml=34, mr=22, mt=18, mb=30):
    """座標平面用Canvas。xr=(x0,x1), yr=(y0,y1)は軸の描画範囲（数学座標）"""
    sy = sx if sy is None else sy
    x0, x1 = xr
    y0, y1 = yr
    w = ml + (x1 - x0) * sx + mr
    h = mt + (y1 - y0) * sy + mb
    cv = Canvas(round(w), round(h), sx=sx, sy=sy,
                ox=ml - x0 * sx, oy=mt + y1 * sy)
    cv._xr, cv._yr = xr, yr
    return cv


def subplane(cv, x_off, y_off, PW, PH, xr, yr, pad=14):
    """パネル分割用: 親Canvasの本体を共有する小座標平面（本単元で追加）"""
    sx = (PW - 2 * pad) / (xr[1] - xr[0])
    sy = (PH - 2 * pad) / (yr[1] - yr[0])
    sub = Canvas(0, 0, sx=sx, sy=sy,
                 ox=x_off + pad - sx * xr[0], oy=y_off + pad + sy * yr[1])
    sub._xr, sub._yr = xr, yr
    sub.body = cv.body
    return sub


def draw_axes(cv, xlabel="x", ylabel="y", xnums=(), ynums=(),
              x_step=1, y_step=1, tick_half=3.0, num_size=FS_NUM,
              origin="O", ticks=True):
    """座標軸: 矢印つき軸線・目盛（1目盛=x_step/y_step）・指定数値ラベル・原点O"""
    (x0, x1), (y0, y1) = cv._xr, cv._yr
    ax0, ay = cv.P((x0, 0))
    ax1, _ = cv.P((x1, 0))
    arrow_px(cv, ax0, ay, ax1 + 8, ay, w=1.2)
    bx, by0 = cv.P((0, y0))
    _, by1 = cv.P((0, y1))
    arrow_px(cv, bx, by0, bx, by1 - 8, w=1.2)
    cv.text_px(ax1 + 10, ay + 4.5, xlabel, size=FS, anchor="start")
    cv.text_px(bx + 7, by1 - 6, ylabel, size=FS, anchor="start")
    if ticks:
        t = math.ceil(x0 / x_step) * x_step
        while t <= x1 + 1e-9:
            if abs(t) > 1e-9:
                px, py = cv.P((t, 0))
                cv.raw(f'<line x1="{px:.1f}" y1="{py - tick_half:.1f}" '
                       f'x2="{px:.1f}" y2="{py + tick_half:.1f}" '
                       f'stroke="#000" stroke-width="1.0"/>')
            t += x_step
        t = math.ceil(y0 / y_step) * y_step
        while t <= y1 + 1e-9:
            if abs(t) > 1e-9:
                px, py = cv.P((0, t))
                cv.raw(f'<line x1="{px - tick_half:.1f}" y1="{py:.1f}" '
                       f'x2="{px + tick_half:.1f}" y2="{py:.1f}" '
                       f'stroke="#000" stroke-width="1.0"/>')
            t += y_step
    for v in xnums:
        px, py = cv.P((v, 0))
        cv.text_px(px, py + num_size + 3, fmt_num(v), size=num_size, anchor="middle")
    for v in ynums:
        px, py = cv.P((0, v))
        cv.text_px(px - 6, py + num_size * 0.35, fmt_num(v), size=num_size, anchor="end")
    if origin:
        px, py = cv.P((0, 0))
        cv.text_px(px - 5, py + num_size + 3, origin, size=num_size, anchor="end")


def fmt_num(v):
    s = f"{v:g}"
    return s.replace("-", "−")  # 数学のマイナス記号（本文と同じU+2212）


def func_pts(f, xa, xb, n=200):
    """関数fを[xa,xb]でサンプリングした点列（数学座標）"""
    return [(xa + (xb - xa) * i / n, f(xa + (xb - xa) * i / n)) for i in range(n + 1)]


def vspan(a, p, y_lim, xlo, xhi):
    """y=a(x−p)²+q 型の曲線を上端（下端）y_limまで描くときのx範囲（頂点対称・視野内に切詰め）"""
    half = math.sqrt(abs(y_lim) / abs(a))
    return max(xlo, p - half), min(xhi, p + half)


def on_curve(ck, name, f, pts, tol=1e-9):
    """通過点リストが厳密に曲線上にあることを検算"""
    for (x, y) in pts:
        assert abs(f(x) - y) <= tol, f"{name}: 点({x},{y})が曲線上にない f({x})={f(x)}"
    ck.ok(f"{name}の通過点{len(pts)}点が式を厳密に満たす",
          True, "／".join(f"({fmt_num(x)},{fmt_num(y)})" for x, y in pts))


def argmin_on(f, lo, hi, n=800):
    """区間[lo,hi]でのfの最小点（サンプリング）——区間つき最大・最小の検算用"""
    xs = [lo + (hi - lo) * i / n for i in range(n + 1)]
    ys = [f(x) for x in xs]
    m = min(ys)
    return xs[ys.index(m)], m


# ===========================================================================
# 図1: L01 §4 y=ax²のグラフの復習——放物線・軸・頂点
# 図の採用根拠: 「軸」「頂点」の定義が箇条書き2項+3文の文章のみ。単元全体で使う
# 基本語彙を1枚に固定する（用語ラベルつきの復習図）。
# ===========================================================================
def fig_L01_1():
    # --- パラメータ（lesson_01.md §4 と一致させる） ---
    f = lambda x: x * x
    pts = [(-3, 9), (-2, 4), (-1, 1), (0, 0), (1, 1), (2, 4), (3, 9)]
    sym_pair = ((-2, 4), (2, 4))          # 左右対称を見せる2点

    ck = Checker()
    on_curve(ck, "y=x²", f, pts)
    ck.ok("y軸（直線x=0）について左右対称（f(x)=f(−x)を7点で確認）",
          all(f(x) == f(-x) for x in range(0, 4)))
    ck.ok("頂点=原点(0,0)が曲線上の最低点", f(0) == 0 and all(f(x) >= 0 for x, _ in pts))

    cv = plane((-3.6, 3.6), (-1, 9.6), 27.0, 21.0, ml=38, mr=86, mt=16, mb=26)
    draw_axes(cv, xnums=(-3, -2, -1, 1, 2, 3), ynums=(4, 9))
    xa, xb = vspan(1, 0, 9.6, -3.6, 3.6)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    # 左右対称の2点と破線
    cv.line(sym_pair[0], sym_pair[1], w=AUX_W, dash=DASH)
    cv.dot(sym_pair[0], r=3.0)
    cv.dot(sym_pair[1], r=3.0)
    # 軸（x=0＝y軸そのもの）と頂点のラベル
    px, py = cv.P((0, 8.6))
    cv.text_px(px + 44, py - 4, "軸（直線x＝0）", size=12, anchor="start")
    arrow_px(cv, px + 42, py - 8, px + 4, py - 2, w=1.1, head=5.5)
    cv.dot((0, 0), r=3.0)
    ox, oy = cv.P((0, 0))
    cv.text_px(ox + 42, oy + 24, "頂点(0, 0)", size=12, anchor="start")
    arrow_px(cv, ox + 40, oy + 20, ox + 5, oy + 4, w=1.1, head=5.5)
    lx, ly = cv.P((2.6, 8.2))
    cv.text_px(lx + 8, ly, "y＝x²", size=FS, anchor="start")

    return {"file": "L01_fig1_parabola_axis_vertex.svg", "lesson": "L01", "canvas": cv,
            "title": "y=x²の放物線と軸・頂点",
            "intent": "単元全体で使う「放物線・軸・頂点」の3語を1枚に固定し、左右対称も破線の2点で見せる復習図",
            "src": "lesson_01.md §4（軸・頂点の箇条書きの直後）",
            "params": "y=x²／軸=直線x=0（y軸）／頂点=(0,0)／対称の例(−2,4)と(2,4)を破線で結ぶ",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_01.md",
            "anchor": "- 軸とグラフが交わる点を、放物線の**頂点**という。y=ax² の頂点は原点 (0, 0) である。"}


# ===========================================================================
# 図2: L01 §5 aの符号と開き方
# 図の採用根拠: 符号（凸の向き）と絶対値（開き方）の2性質が文章+箇条書きのみで、
# 3本の曲線の比較は文字では目が滑る。x軸対称の実例(1,2)-(1,−2)も本文どおり示す。
# ===========================================================================
def fig_L01_2():
    # --- パラメータ（lesson_01.md §5 と一致させる） ---
    curves = [(2.0, "y＝2x²"), (1.0, "y＝x²"), (-2.0, "y＝−2x²")]
    pair = ((1, 2), (1, -2))              # 本文: x=1でy=2とy=−2（符号が逆）

    ck = Checker()
    for a, name in curves:
        on_curve(ck, name, lambda x, a=a: a * x * x,
                 [(x, a * x * x) for x in (-2, -1, 0, 1, 2)])
    ck.ok("x=1でy=2x²は2・y=−2x²は−2（すべてのxでyの符号が逆＝x軸対称）",
          2 * 1 == 2 and -2 * 1 == -2 and all(2 * x * x == -(-2 * x * x) for x in range(-3, 4)))
    ck.ok("|a|が大きいほど開き方が狭い: 同じy=2に達するxは y=2x²で±1・y=x²で±√2",
          math.isclose(math.sqrt(2 / 2.0), 1.0) and math.sqrt(2 / 1.0) > 1.0)

    cv = plane((-3.2, 3.2), (-8.6, 8.6), 30.0, 13.0, ml=40, mr=66, mt=16, mb=26)
    draw_axes(cv, xnums=(-2, -1, 1, 2), ynums=(-8, -4, 2, 4, 8))
    for a, name in curves:
        xa, xb = vspan(a, 0, 8.6, -3.2, 3.2)
        cv.polyline(func_pts(lambda x, a=a: a * x * x, xa, xb), w=MAIN_W)
    # x軸対称の実例（破線で結ぶ）
    cv.line(pair[0], pair[1], w=AUX_W, dash=DASH)
    cv.dot(pair[0], r=3.0)
    cv.dot(pair[1], r=3.0)
    # 式ラベル（y軸ラベルと重ならない左腕側に置く）
    lx, ly = cv.P((-math.sqrt(8.6 / 2), 8.2))
    cv.text_px(lx - 6, ly, "y＝2x²", size=FS, anchor="end")
    lx, ly = cv.P((math.sqrt(8.6), 8.2))
    cv.text_px(lx + 6, ly, "y＝x²", size=FS, anchor="start")
    lx, ly = cv.P((math.sqrt(8.6 / 2), -8.2))
    cv.text_px(lx + 6, ly + 8, "y＝−2x²", size=FS, anchor="start")

    return {"file": "L01_fig2_sign_and_width.svg", "lesson": "L01", "canvas": cv,
            "title": "aの符号と開き方——y=2x²・y=x²・y=−2x²",
            "intent": "a>0は下に凸・a<0は上に凸、|a|が大きいほど狭い——3本の比較とx軸対称の実例(1,2)(1,−2)を1枚で見せる",
            "src": "lesson_01.md §5（箇条書きと開き方の文の直後）",
            "params": "a=2,1,−2／破線(1,2)-(1,−2)／式ラベル3つ",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_01.md",
            "anchor": "また、aの絶対値が大きいほどグラフの開き方は狭くなる。y=2x² は y=x² より細い放物線である。"}


# ===========================================================================
# 図3: L02 §1 上下に動かす——y=x²＋q
# 図の採用根拠: 「どのxでもちょうど2大きい→全体が+2ずれる」は表と4文の文章のみ。
# 平行移動の前後比較の第1図（縦方向）。
# ===========================================================================
def fig_L02_1():
    # --- パラメータ（lesson_02.md §1 と一致させる） ---
    f1 = lambda x: x * x
    f2 = lambda x: x * x + 2
    table_x = [-2, -1, 0, 1, 2]
    arrows_at = [-1.5, 0, 1.5]            # ＋2のずれを見せる縦矢印の位置

    ck = Checker()
    on_curve(ck, "y=x²", f1, [(x, x * x) for x in table_x])
    on_curve(ck, "y=x²+2", f2, [(x, x * x + 2) for x in table_x])
    ck.ok("どのxでも差がちょうど2（本文の表 4,1,0,1,4 → 6,3,2,3,6 と一致）",
          all(f2(x) - f1(x) == 2 for x in table_x) and
          [f2(x) for x in table_x] == [6, 3, 2, 3, 6])
    ck.ok("移動後の頂点(0,2)・軸は直線x=0のまま", f2(0) == 2 and f2(1) == f2(-1))

    cv = plane((-2.9, 2.9), (-0.8, 7.2), 34.0, 26.0, ml=38, mr=76, mt=16, mb=26)
    draw_axes(cv, xnums=(-2, -1, 1, 2), ynums=(2, 4, 6))
    for f in (f1, f2):
        xa, xb = vspan(1, 0, 7.2 - (0 if f is f1 else 2), -2.9, 2.9)
        cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    for t in arrows_at:
        (x0, y0), (x1, y1) = cv.P((t, f1(t))), cv.P((t, f2(t)))
        arrow_px(cv, x0, y0, x1, y1 + 5, w=1.3)
    tx, ty = cv.P((1.5, (f1(1.5) + f2(1.5)) / 2))
    cv.text_px(tx + 10, ty + 4, "＋2", size=12, anchor="start", weight="bold")
    cv.dot((0, 0), r=3.0)
    cv.dot((0, 2), r=3.0)
    lx, ly = cv.P((math.sqrt(7.2), 6.9))
    cv.text_px(lx + 6, ly + 10, "y＝x²", size=FS, anchor="start")
    # y=x²+2 のラベルはy軸ラベルと重ならない左腕側に置く
    lx, ly = cv.P((-math.sqrt(5.2), 7.2))
    cv.text_px(lx - 6, ly + 4, "y＝x²＋2", size=FS, anchor="end")

    return {"file": "L02_fig1_vertical_shift.svg", "lesson": "L02", "canvas": cv,
            "title": "y=x²とy=x²＋2——y軸方向に＋2の平行移動",
            "intent": "どのxでもyがちょうど2大きい→グラフ全体が上に2ずれる（形は不変）ことを縦矢印3本で見せる前後比較図",
            "src": "lesson_02.md §1（表と段落の直後）",
            "params": "y=x²とy=x²+2／縦矢印x=−1.5,0,1.5／頂点(0,0)→(0,2)",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_02.md",
            "anchor": "この先ずっと、座標軸は固定したままグラフの側を動かして考える。"}


# ===========================================================================
# 図4: L02 §2 左右に動かす——y=(x−3)²と「点の移り先」
# 図の採用根拠: 「点(u,u²)が(u＋3,u²)に移る」説明は5文以上の文章のみで最も目が
# 滑る箇所。平行移動の前後比較の第2図（横方向・点の対応つき）。
# ===========================================================================
def fig_L02_2():
    # --- パラメータ（lesson_02.md §2 と一致させる） ---
    f1 = lambda x: x * x
    f2 = lambda x: (x - 3) ** 2
    moves = [(-1, 1), (0, 0), (1, 1)]     # (u,u²) → (u+3,u²) を見せる3点

    ck = Checker()
    on_curve(ck, "y=x²", f1, [(x, x * x) for x in (-2, -1, 0, 1, 2)])
    on_curve(ck, "y=(x−3)²", f2, [(x, (x - 3) ** 2) for x in (1, 2, 3, 4, 5)])
    ck.ok("表の値の並びが同じ（x=1..5で4,1,0,1,4＝y=x²のx=−2..2と一致）",
          [f2(x) for x in (1, 2, 3, 4, 5)] == [f1(x) for x in (-2, -1, 0, 1, 2)])
    ck.ok("点(u,u²)を右に3動かした点(u+3,u²)が移動後の曲線上にある",
          all(abs(f2(u + 3) - y) < 1e-12 for u, y in moves))
    ck.ok("移動後の頂点(3,0)・軸は直線x=3", f2(3) == 0 and f2(2) == f2(4))

    cv = plane((-2.7, 5.9), (-0.9, 4.9), 34.0, 30.0, ml=38, mr=88, mt=16, mb=26)
    draw_axes(cv, xnums=(-2, -1, 1, 2, 3, 4, 5), ynums=(1, 4))
    xa, xb = vspan(1, 0, 4.9, -2.7, 5.9)
    cv.polyline(func_pts(f1, xa, xb), w=MAIN_W)
    xa, xb = vspan(1, 3, 4.9, -2.7, 5.9)
    cv.polyline(func_pts(f2, xa, xb), w=MAIN_W)
    for u, y in moves:
        cv.dot((u, y), r=3.0)
        cv.dot((u + 3, y), r=3.0)
        (x0, y0), (x1, y1) = cv.P((u, y)), cv.P((u + 3, y))
        arrow_px(cv, x0 + 6, y0 - (7 if y > 0 else -7),
                 x1 - 6, y1 - (7 if y > 0 else -7), w=1.2)
    tx, ty = cv.P((1.5, 0))
    cv.text_px(tx, ty - 12, "＋3", size=12, anchor="middle", weight="bold")
    # 軸 x=3（破線）
    cv.line((3, 0), (3, 4.5), w=AUX_W, dash=DASH)
    lx, ly = cv.P((-2.2, 4.6))
    cv.text_px(lx - 4, ly - 4, "y＝x²", size=FS, anchor="start")
    lx, ly = cv.P((5.2, 4.6))
    cv.text_px(lx + 2, ly - 4, "y＝(x−3)²", size=FS, anchor="start")

    return {"file": "L02_fig2_horizontal_shift.svg", "lesson": "L02", "canvas": cv,
            "title": "y=x²とy=(x−3)²——x軸方向に＋3の平行移動",
            "intent": "グラフ上のすべての点がそろって右へ3移る（点(u,u²)→(u+3,u²)）ことを対応点3組の矢印で見せる前後比較図",
            "src": "lesson_02.md §2（「点の移り先」の段落の直後）",
            "params": "y=x²とy=(x−3)²／対応点(−1,1)→(2,1),(0,0)→(3,0),(1,1)→(4,1)／軸x=3破線",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_02.md",
            "anchor": "——これが「x が x−3 に置き換わる」ことの中身である。"}


# ===========================================================================
# 図5: L02 §3 両方動かす——y=(x−3)²＋2 と軸・頂点
# 図の採用根拠: 単元の主役「y=a(x−p)²+qの軸x=p・頂点(p,q)」の一般則が太字文のみ。
# 具体例(3,2)で「右へ3→上へ2」の2段移動を見せる。
# ===========================================================================
def fig_L02_3():
    # --- パラメータ（lesson_02.md §3 と一致させる） ---
    f1 = lambda x: x * x
    f3 = lambda x: (x - 3) ** 2 + 2
    p, q = 3, 2

    ck = Checker()
    on_curve(ck, "y=(x−3)²+2", f3, [(1, 6), (2, 3), (3, 2), (4, 3), (5, 6)])
    ck.ok("頂点(3,2)＝x軸方向+3・y軸方向+2の移動先", f3(p) == q and (p, q) == (3, 2))
    ck.ok("軸は直線x=3（x=3±tで同じ値）",
          all(f3(3 + t) == f3(3 - t) for t in (0.5, 1, 2)))
    ck.ok("y=x²を平行移動した形（f3(x)=f1(x−3)+2が恒等的に成立・5点で確認）",
          all(f3(x) == f1(x - 3) + 2 for x in range(-1, 7)))

    cv = plane((-2.6, 6.2), (-0.9, 7.2), 32.0, 26.0, ml=38, mr=92, mt=16, mb=26)
    draw_axes(cv, xnums=(-2, -1, 1, 2, 4, 5), ynums=(2, 4, 6))
    xa, xb = vspan(1, 0, 7.2, -2.6, 6.2)
    cv.polyline(func_pts(f1, xa, xb), w=MAIN_W)
    xa, xb = vspan(1, 3, 7.2 - 2, -2.6, 6.2)
    cv.polyline(func_pts(f3, xa, xb), w=MAIN_W)
    # 2段の移動矢印: (0,0)→(3,0)→(3,2)
    (x0, y0), (x1, y1) = cv.P((0, 0)), cv.P((3, 0))
    arrow_px(cv, x0 + 6, y0 + 14, x1 - 2, y1 + 14, w=1.3)
    cv.text_px((x0 + x1) / 2, y0 + 28, "x軸方向に＋3", size=FS_NUM, anchor="middle")
    (x0, y0), (x1, y1) = cv.P((3, 0)), cv.P((3, 2))
    arrow_px(cv, x0 + 22, y0, x1 + 22, y1 + 4, w=1.3)
    cv.text_px(x0 + 28, (y0 + y1) / 2 + 4, "y軸方向に＋2", size=FS_NUM, anchor="start")
    # 軸と頂点
    cv.line((3, 2), (3, 6.9), w=AUX_W, dash=DASH)
    cv.dot((0, 0), r=3.0)
    cv.dot((3, 2), r=3.4)
    vx, vy = cv.P((3, 2))
    cv.text_px(vx - 14, vy + 20, "頂点(3, 2)", size=12, anchor="end", weight="bold")
    px, py = cv.P((3, 6.9))
    cv.text_px(px + 6, py + 2, "軸 x＝3", size=12, anchor="start")
    lx, ly = cv.P((-2.2, 6.4))
    cv.text_px(lx - 4, ly - 6, "y＝x²", size=FS, anchor="start")
    lx, ly = cv.P((5.15, 6.9))
    cv.text_px(lx + 4, ly - 4, "y＝(x−3)²＋2", size=FS, anchor="start")

    return {"file": "L02_fig3_both_shift_vertex.svg", "lesson": "L02", "canvas": cv,
            "title": "y=(x−3)²＋2——右へ3・上へ2で頂点(3,2)",
            "intent": "縦横の平行移動を組み合わせると頂点が(p,q)に移る——一般則y=a(x−p)²+qの具体例を2段矢印で見せる",
            "src": "lesson_02.md §3（一般則の太字文の直後）",
            "params": "y=x²→y=(x−3)²+2／移動矢印(0,0)→(3,0)→(3,2)／軸x=3破線・頂点(3,2)",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_02.md",
            "anchor": "である。この形なら、グラフをかかなくても軸と頂点が式から直接読み取れる。この単元では、この「頂点が読める形」が主役になる。"}


# ===========================================================================
# 図6: L03 §2 平方完成の結果——y=x²＋4x＋1=(x＋2)²−3
# 図の採用根拠: §1「この式の頂点はどこ？」の困りごとから§2の変形まで文章のみ。
# 変形の成果（頂点が読めた）をグラフで1枚確認し、式変形と図を接続する。
# ===========================================================================
def fig_L03_1():
    # --- パラメータ（lesson_03.md §1-§2 と一致させる） ---
    f = lambda x: x * x + 4 * x + 1
    p, q = -2, -3                          # 変形後 (x+2)²−3 の頂点

    ck = Checker()
    ck.ok("恒等式 x²+4x+1=(x+2)²−3（係数比較: 4=2·2, 1=2²−3）",
          all(f(x) == (x + 2) ** 2 - 3 for x in range(-6, 3)))
    on_curve(ck, "y=x²+4x+1", f, [(-4, 1), (-2, -3), (0, 1)])
    ck.ok("頂点(−2,−3)が最低点・軸x=−2について対称",
          f(p) == q and all(f(p + t) == f(p - t) for t in (1, 2)))

    cv = plane((-5.6, 1.6), (-3.9, 6.2), 32.0, 22.0, ml=40, mr=30, mt=16, mb=40)
    draw_axes(cv, xnums=(-5, -4, -3, -1, 1), ynums=(-3, 1, 3, 6))
    xa, xb = vspan(1, p, 6.2 - q, -5.6, 1.6)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.line((p, q), (p, 5.9), w=AUX_W, dash=DASH)
    cv.line((p, q), (0, q), w=AUX_W, dash=DASH)
    cv.dot((p, q), r=3.4)
    cv.dot((0, 1), r=3.0)
    vx, vy = cv.P((p, q))
    cv.text_px(vx - 8, vy + 18, "頂点(−2, −3)", size=12, anchor="start", weight="bold")
    px, py = cv.P((p, 5.9))
    cv.text_px(px - 8, py + 2, "軸 x＝−2", size=12, anchor="end")  # 目盛数値と重ねない左置き
    cv.text_px(cv.w / 2, cv.h - 8, "y＝x²＋4x＋1＝(x＋2)²−3", size=12, anchor="middle")

    return {"file": "L03_fig1_completing_square_vertex.svg", "lesson": "L03", "canvas": cv,
            "title": "y=x²＋4x＋1のグラフ——変形すると頂点(−2,−3)が読める",
            "intent": "一般形のままでは見えなかった頂点が、平方完成後の式から読めた——式変形の成果をグラフで確認する",
            "src": "lesson_03.md §2（平方完成の名前の段落の直後）",
            "params": "y=x²+4x+1=(x+2)²−3／頂点(−2,−3)・軸x=−2破線／y切片(0,1)",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_03.md",
            "anchor": "こうして得た y=(x＋2)²−3 から、頂点 (−2, −3)、軸は直線 x=−2 と読める。この変形は**平方完成**と呼ばれる（「2乗＝平方」の形を完成させる、という意味の呼び名である）。"}


# ===========================================================================
# 図7: L04 例題1——y=x²−4x＋3 を「4つの情報」から描く
# 図の採用根拠: 描画手順（凸の向き・軸・頂点・x=0の値→対称にかく）が箇条書き+
# 3文で完結しており、完成形の見本図がないと手順の到達点が分からない。
# ===========================================================================
def fig_L04_1():
    # --- パラメータ（lesson_04.md 例題1 と一致させる） ---
    f = lambda x: x * x - 4 * x + 3
    vert = (2, -1)
    y_int = (0, 3)
    sym_pt = (4, 3)                        # 対称性から通る点（本文明示）

    ck = Checker()
    ck.ok("恒等式 x²−4x+3=(x−2)²−1", all(f(x) == (x - 2) ** 2 - 1 for x in range(-2, 7)))
    on_curve(ck, "y=x²−4x+3", f, [vert, y_int, sym_pt])
    ck.ok("下に凸（a=1>0）・軸x=2について(0,3)と(4,3)が対称",
          f(0) == f(4) == 3 and f(2) == -1)

    cv = plane((-1.3, 5.5), (-1.9, 6.4), 32.0, 24.0, ml=38, mr=30, mt=16, mb=40)
    draw_axes(cv, xnums=(-1, 1, 3, 4, 5), ynums=(-1, 3, 6))
    xa, xb = vspan(1, 2, 6.4 + 1, -1.3, 5.5)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.line((2, -1), (2, 6.1), w=AUX_W, dash=DASH)
    cv.line(y_int, sym_pt, w=AUX_W, dash=DASH)
    for pnt in (vert, y_int, sym_pt):
        cv.dot(pnt, r=3.2)
    vx, vy = cv.P(vert)
    cv.text_px(vx + 8, vy + 14, "頂点(2, −1)", size=12, anchor="start", weight="bold")
    px, py = cv.P((2, 6.1))
    cv.text_px(px + 6, py + 2, "軸 x＝2", size=12, anchor="start")
    px, py = cv.P(y_int)
    cv.text_px(px - 8, py - 8, "(0, 3)", size=12, anchor="end")
    px, py = cv.P(sym_pt)
    cv.text_px(px + 8, py - 8, "(4, 3)", size=12, anchor="start")
    cv.text_px(cv.w / 2, cv.h - 8, "y＝x²−4x＋3＝(x−2)²−1", size=12, anchor="middle")

    return {"file": "L04_fig1_graph_from_four_facts.svg", "lesson": "L04", "canvas": cv,
            "title": "y=x²−4x＋3のグラフ——4つの情報から描いた完成形",
            "intent": "凸の向き・軸・頂点・x=0の値の4情報を集めて、軸について対称に描く手順の到達点（完成見本）を見せる",
            "src": "lesson_04.md 例題1（検算の段落の直後）",
            "params": "y=x²−4x+3=(x−2)²−1／頂点(2,−1)・軸x=2破線／(0,3)と対称点(4,3)を破線で結ぶ",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_04.md",
            "anchor": "頂点 (2, −1) を打ち、点 (0, 3) を通るなめらかな曲線を、軸 x=2 について左右対称になるように描く（対称性から点 (4, 3) も通る）。**検算**: x=2 を元の式に代入すると 4−8＋3=−1 で頂点の y座標と一致する。"}


# ===========================================================================
# 図8: L04 例題2——上に凸・a=−2の場合の完成形
# 図の採用根拠: aが負のときの描画は符号ミスが集中する箇所だが本文は文章のみ。
# 上に凸の完成見本を例題1と対で置く。
# ===========================================================================
def fig_L04_2():
    # --- パラメータ（lesson_04.md 例題2 と一致させる） ---
    f = lambda x: -2 * x * x - 4 * x + 1
    vert = (-1, 3)
    y_int = (0, 1)
    sym_pt = (-2, 1)                       # 軸x=−1についてy切片と対称

    ck = Checker()
    ck.ok("恒等式 −2x²−4x+1=−2(x+1)²+3",
          all(f(x) == -2 * (x + 1) ** 2 + 3 for x in range(-4, 3)))
    on_curve(ck, "y=−2x²−4x+1", f, [vert, y_int, sym_pt])
    ck.ok("上に凸（a=−2<0）・頂点(−1,3)が最高点",
          all(f(x) <= 3 for x in [-3 + 0.1 * i for i in range(41)]))

    cv = plane((-3.5, 1.5), (-4.4, 4.2), 36.0, 22.0, ml=40, mr=30, mt=16, mb=40)
    draw_axes(cv, xnums=(-3, -2, 1), ynums=(-4, -2, 1, 3))
    xa, xb = vspan(-2, -1, -4.4 - 3, -3.5, 1.5)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.line((-1, 3), (-1, -4.1), w=AUX_W, dash=DASH)
    cv.line(y_int, sym_pt, w=AUX_W, dash=DASH)
    for pnt in (vert, y_int, sym_pt):
        cv.dot(pnt, r=3.2)
    vx, vy = cv.P(vert)
    cv.text_px(vx, vy - 10, "頂点(−1, 3)", size=12, anchor="middle", weight="bold")
    px, py = cv.P((-1, -4.1))
    cv.text_px(px - 8, py + 2, "軸 x＝−1", size=12, anchor="end")  # y軸線と重ねない左置き
    px, py = cv.P(y_int)
    cv.text_px(px + 8, py + 4, "(0, 1)", size=12, anchor="start")
    px, py = cv.P(sym_pt)
    cv.text_px(px - 8, py + 4, "(−2, 1)", size=12, anchor="end")
    cv.text_px(cv.w / 2, cv.h - 8, "y＝−2x²−4x＋1＝−2(x＋1)²＋3", size=12, anchor="middle")

    return {"file": "L04_fig2_negative_a_graph.svg", "lesson": "L04", "canvas": cv,
            "title": "y=−2x²−4x＋1のグラフ——上に凸の完成形",
            "intent": "aが負でも手順は同じ——上に凸・頂点(−1,3)の完成見本を例題1と対で見せ、符号ミスを図で点検できるようにする",
            "src": "lesson_04.md 例題2（検算の段落の直後）",
            "params": "y=−2x²−4x+1=−2(x+1)²+3／頂点(−1,3)・軸x=−1破線／(0,1)と対称点(−2,1)",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_04.md",
            "anchor": "**検算**: x=−1 を元の式に代入すると −2＋4＋1=3 で頂点と一致。カッコの外に出した −2 のかけ忘れ（−2(x＋1)²−1＋1 とする誤り）が起きやすいので、検算代入までを1セットの手順にする。"}


# ===========================================================================
# 図9: L05——下に凸と上に凸の最大・最小（2パネル対比）
# 図の採用根拠: 「あるのは頂点の側だけ・存在しない側はない」の対比が§1〜§3の
# 長い文章に分散。両凸を並べた対比パネルで「なし」の意味（腕が開き続ける）を見せる。
# ===========================================================================
def fig_L05_1():
    # --- パラメータ（lesson_05.md §1・§3 と一致させる） ---
    fA = lambda x: (x - 2) ** 2 + 3        # 下に凸: x=2で最小値3
    fB = lambda x: -(x - 3) ** 2 + 5       # 上に凸: x=3で最大値5

    ck = Checker()
    on_curve(ck, "y=(x−2)²+3", fA, [(2, 3), (0, 7), (4, 7)])
    on_curve(ck, "y=−(x−3)²+5", fB, [(3, 5), (1, 1), (5, 1)])
    ck.ok("下に凸: x=2で最小値3・上限なし（x=100でy=9607>どんな見本値より大）",
          argmin_on(fA, -1, 5)[1] == 3 and fA(100) == 9607)
    ck.ok("上に凸: x=3で最大値5・下限なし（x=100でy=−9404）",
          -argmin_on(lambda x: -fB(x), 0, 6)[1] == 5 and fB(100) == -9404)

    PW, PH, gap = 195, 205, 18
    W = 16 + PW * 2 + gap + 16
    H = PH + 56
    cv = Canvas(W, H, sx=1.0)
    # パネルA: 下に凸
    sub = subplane(cv, 16, 14, PW, PH, (-0.9, 4.9), (-0.9, 9.6))
    draw_axes(sub, num_size=9, origin=None)
    xa, xb = vspan(1, 2, 9.6 - 3, -0.9, 4.9)
    sub.polyline(func_pts(fA, xa, xb), w=MAIN_W)
    sub.dot((2, 3), r=3.4)
    px, py = sub.P((2, 3))
    cv.text_px(px + 8, py + 12, "最小（頂点）", size=11, anchor="start", weight="bold")
    for t, side in ((xa + 0.25, -1), (xb - 0.25, 1)):
        (x0, y0) = sub.P((t, fA(t)))
        arrow_px(cv, x0 - side * 12, y0 + 22, x0 + side * 4, y0 - 6, w=1.4)
    px, py = sub.P((2, 9.0))
    cv.text_px(px, py, "いくらでも大きくなる", size=10.5, anchor="middle")
    cv.text_px(16 + PW / 2, 14 + PH + 18, "下に凸 y＝(x−2)²＋3", size=12, anchor="middle")
    cv.text_px(16 + PW / 2, 14 + PH + 34, "最小あり・最大なし", size=12,
               anchor="middle", weight="bold")
    # パネルB: 上に凸
    xB = 16 + PW + gap
    sub = subplane(cv, xB, 14, PW, PH, (0.1, 5.9), (-2.4, 6.4))
    draw_axes(sub, num_size=9, origin=None)
    xa, xb = vspan(-1, 3, -2.4 - 5, 0.1, 5.9)
    sub.polyline(func_pts(fB, xa, xb), w=MAIN_W)
    sub.dot((3, 5), r=3.4)
    px, py = sub.P((3, 5))
    cv.text_px(px + 8, py - 6, "最大（頂点）", size=11, anchor="start", weight="bold")
    for t, side in ((xa + 0.25, -1), (xb - 0.25, 1)):
        (x0, y0) = sub.P((t, fB(t)))
        arrow_px(cv, x0 - side * 12, y0 - 22, x0 + side * 4, y0 + 6, w=1.4)
    px, py = sub.P((3, -2.0))
    cv.text_px(px, py + 4, "いくらでも小さくなる", size=10.5, anchor="middle")
    cv.text_px(xB + PW / 2, 14 + PH + 18, "上に凸 y＝−(x−3)²＋5", size=12, anchor="middle")
    cv.text_px(xB + PW / 2, 14 + PH + 34, "最大あり・最小なし", size=12,
               anchor="middle", weight="bold")

    return {"file": "L05_fig1_max_min_two_cases.svg", "lesson": "L05", "canvas": cv,
            "title": "下に凸と上に凸——あるのは頂点の側だけ",
            "intent": "定義域に制限がないとき、最大・最小は頂点の側だけに存在し、反対側は腕が開き続けて「なし」になることを2パネル対比で見せる",
            "src": "lesson_05.md §3（まとめの段落の直後）",
            "params": "左: y=(x−2)²+3（最小3・最大なし）／右: y=−(x−3)²+5（最大5・最小なし）／腕の先に外向き矢印",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_05.md",
            "anchor": "まとめると: **下に凸 → 頂点で最小値・最大値なし／上に凸 → 頂点で最大値・最小値なし**。どちらの場合も「あるのは頂点の側だけ」である。"}


# ===========================================================================
# 図10: L06 例題1——頂点が区間の中にある場合
# 図の採用根拠: 本文自身が「区間内のグラフだけを太くなぞった図を描くと…目で
# 確かめられる」と図を指示している（文章は3段手順の説明が続く）。
# ===========================================================================
def fig_L06_1():
    # --- パラメータ（lesson_06.md 例題1 と一致させる） ---
    f = lambda x: (x - 1) ** 2 + 2
    dom = (0, 3)
    cand = [(0, 3), (1, 2), (3, 6)]        # 候補3点（頂点+両端）

    ck = Checker()
    on_curve(ck, "y=(x−1)²+2", f, cand)
    ck.ok("軸x=1は区間0≦x≦3の中", dom[0] <= 1 <= dom[1])
    xm, ym = argmin_on(f, *dom)
    ck.ok("区間内の最小はx=1でy=2（端ではなく頂点）",
          abs(xm - 1) < 5e-3 and abs(ym - 2) < 1e-4 and f(1) == 2)
    ck.ok("区間内の最大はx=3でy=6（軸から遠い方の端）",
          max(f(dom[0]), f(dom[1])) == f(3) == 6)

    cv = plane((-1.4, 4.2), (-0.9, 7.4), 36.0, 26.0, ml=38, mr=76, mt=16, mb=28)
    draw_axes(cv, xnums=(-1, 1, 2, 3), ynums=(2, 3, 6))
    xa, xb = vspan(1, 1, 7.4 - 2, -1.4, 4.2)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.polyline(func_pts(f, dom[0], dom[1], 120), w=BOLD_W)
    for pnt in cand:
        cv.dot(pnt, r=3.2)
        cv.line((pnt[0], 0), pnt, w=AUX_W, dash=DASH)
        cv.line((0, pnt[1]), pnt, w=AUX_W, dash=DASH)
    cv.line((dom[0], 0), (dom[1], 0), w=BOLD_W)
    px, py = cv.P((1, 2))
    cv.text_px(px + 30, py + 22, "頂点は区間の中", size=12, anchor="start", weight="bold")
    arrow_px(cv, px + 28, py + 18, px + 5, py + 4, w=1.1, head=5.5)
    px, py = cv.P((1.5, 0))
    cv.text_px(px, py + 26, "区間 0≦x≦3", size=FS_NUM, anchor="middle")

    return {"file": "L06_fig1_vertex_inside_interval.svg", "lesson": "L06", "canvas": cv,
            "title": "y=(x−1)²＋2（0≦x≦3）——頂点が区間の中",
            "intent": "区間内のグラフだけを太くなぞると、最小は頂点・最大は軸から遠い端になっていることが目で確かめられる",
            "src": "lesson_06.md 例題1（③比較の段落の直後）",
            "params": "y=(x−1)²+2／区間[0,3]を太線／候補3点(0,3),(1,2),(3,6)に破線ガイド",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_06.md",
            "anchor": "よって **x=3 で最大値 6、x=1 で最小値 2**。区間内のグラフだけを太くなぞった図を描くと、太い部分の一番高い点・低い点が答えになっていることが目で確かめられる。"}


# ===========================================================================
# 図11: L06 例題2——頂点が区間の外にある場合
# 図の採用根拠: 「区間外の頂点の値は実現されない」が本単元最大の誤答ポイント
# だが文章のみ。頂点を○（実現されない）で示し、使える太線部分と分離して見せる。
# ===========================================================================
def fig_L06_2():
    # --- パラメータ（lesson_06.md 例題2 と一致させる） ---
    f = lambda x: (x - 4) ** 2 + 1
    dom = (0, 2)
    ends = [(0, 17), (2, 5)]

    ck = Checker()
    on_curve(ck, "y=(x−4)²+1", f, ends + [(4, 1)])
    ck.ok("軸x=4は区間0≦x≦2の外", not (dom[0] <= 4 <= dom[1]))
    xm, ym = argmin_on(f, *dom)
    ck.ok("区間内の最小はx=2でy=5（頂点の値1は実現されない）",
          abs(xm - 2) < 1e-3 and ym == 5 and 1 < 5)
    ck.ok("区間内の最大はx=0でy=17", max(f(dom[0]), f(dom[1])) == f(0) == 17)

    cv = plane((-0.9, 6.6), (-1.8, 18.6), 40.0, 9.0, ml=40, mr=30, mt=16, mb=28)
    draw_axes(cv, xnums=(1, 2, 4), ynums=(1, 5, 17), y_step=2)
    xa, xb = vspan(1, 4, 18.6 - 1, -0.9, 6.6)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.polyline(func_pts(f, dom[0], dom[1], 120), w=BOLD_W)
    for pnt in ends:
        cv.dot(pnt, r=3.2)
        cv.line((0, pnt[1]), pnt, w=AUX_W, dash=DASH)
    cv.line((ends[1][0], 0), ends[1], w=AUX_W, dash=DASH)
    cv.line((dom[0], 0), (dom[1], 0), w=BOLD_W)
    # 頂点=区間の外（○で「この関数では実現されない」を示す）
    cv.open_dot((4, 1))
    cv.line((4, 0), (4, 1), w=AUX_W, dash=DASH)
    px, py = cv.P((4, 1))
    cv.text_px(px - 6, py - 16, "頂点は区間の外", size=12, anchor="middle", weight="bold")
    cv.text_px(px + 4, py + 38, "この値は実現されない", size=FS_NUM, anchor="middle")
    px, py = cv.P((1, 0))
    cv.text_px(px, py + 26, "区間 0≦x≦2", size=FS_NUM, anchor="middle")

    return {"file": "L06_fig2_vertex_outside_interval.svg", "lesson": "L06", "canvas": cv,
            "title": "y=(x−4)²＋1（0≦x≦2）——頂点が区間の外",
            "intent": "頂点が区間の外なら候補は両端のみ——頂点の値は○（実現されない）で示し、太線の使える部分と分離して見せる",
            "src": "lesson_06.md 例題2（③比較の段落の直後）",
            "params": "y=(x−4)²+1／区間[0,2]を太線／両端(0,17),(2,5)●・頂点(4,1)○",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_06.md",
            "anchor": "**③比較**: **x=0 で最大値 17、x=2 で最小値 5**。"}


# ===========================================================================
# 図12: L06 例題3——軸が動く場合分けの3ケース（3パネル）
# 図の採用根拠: 本文自身が「3つの図を並べ、区間は3枚とも同じ位置に固定し…」と
# 図を指示。場合分けの3ケース図（区間固定×動く軸）。
# 答え漏れ注意: 各場合の最小値（0・−a²・4−4a）は本文の解だが、図には
# 「最小」の位置だけ示し値のラベルは書かない（bansで機械検査）。
# ===========================================================================
def fig_L06_3():
    # --- パラメータ（lesson_06.md 例題3 と一致させる） ---
    cases = [("(i) a＜0", -1.0), ("(ii) 0≦a≦2", 1.0), ("(iii) a＞2", 3.0)]
    dom = (0, 2)                           # 区間は3枚とも固定
    xr, yr = (-2.4, 4.6), (-9.8, 6.0)      # 3パネル共通（区間の位置をそろえる）

    ck = Checker()
    for lab, a in cases:
        f = lambda x, a=a: x * x - 2 * a * x
        ck.ok(f"{lab}: 代表値a={fmt_num(a)}が場合の範囲内",
              (a < 0) if "i)" == lab[1:3] else True)
        xm, _ = argmin_on(f, *dom)
        expect = dom[0] if a < dom[0] else (a if a <= dom[1] else dom[1])
        ck.ok(f"{lab}: 区間[0,2]での最小の位置x={fmt_num(expect)}（左端／頂点／右端）",
              abs(xm - expect) < 1e-2, f"実測x={xm:.3f}")
        ck.ok(f"{lab}: 頂点(a,−a²)が式変形 (x−a)²−a² と一致",
              f(a) == -a * a)
    ck.ok("軸の位置: 左外(−1)→中(1)→右外(3) の順に右へ動く",
          cases[0][1] < dom[0] <= cases[1][1] <= dom[1] < cases[2][1])

    PW, PH, gap = 168, 200, 12
    W = 14 + PW * 3 + gap * 2 + 14
    H = PH + 66
    cv = Canvas(W, H, sx=1.0)
    for i, (lab, a) in enumerate(cases):
        f = lambda x, a=a: x * x - 2 * a * x
        x_off = 14 + i * (PW + gap)
        sub = subplane(cv, x_off, 26, PW, PH, xr, yr)
        draw_axes(sub, num_size=9, origin=None, xnums=(2,))
        xa, xb = vspan(1, a, yr[1] + a * a, *xr)
        sub.polyline(func_pts(f, xa, xb), w=MAIN_W)
        # 区間[0,2]（3枚とも同じ位置・太線+●）
        sub.line((dom[0], 0), (dom[1], 0), w=BOLD_W)
        sub.dot((dom[0], 0), r=3.0)
        sub.dot((dom[1], 0), r=3.0)
        # 軸 x=a（破線）
        sub.line((a, yr[0] * 0.92), (a, yr[1] * 0.92), w=AUX_W, dash=DASH)
        px, py = sub.P((a, yr[1] * 0.92))
        # 軸ラベル: y軸ラベル「y」と近いパネルは外側へ逃がす（a=1→右・a=−1→左）
        off = 14 if 0 <= a <= 1.5 else (-14 if -1.5 <= a < 0 else 0)
        cv.text_px(px + off, py - 4, "軸", size=FS_NUM, anchor="middle")
        # 区間内の最小の位置（●）
        expect = dom[0] if a < dom[0] else (a if a <= dom[1] else dom[1])
        sub.dot((expect, f(expect)), r=3.6)
        px, py = sub.P((expect, f(expect)))
        cv.text_px(px + (8 if i == 0 else 0), py + 16, "最小",
                   size=FS_NUM, anchor=("start" if i == 0 else "middle"), weight="bold")
        cv.text_px(x_off + PW / 2, 16, lab, size=12, anchor="middle", weight="bold")
    cv.text_px(W / 2, H - 24, "区間 0≦x≦2 は3枚とも同じ位置に固定——動くのは軸 x＝a だけ",
               size=12, anchor="middle")
    cv.text_px(W / 2, H - 8, "y＝x²−2ax", size=FS_NUM, anchor="middle")

    return {"file": "L06_fig3_case_split_moving_axis.svg", "lesson": "L06", "canvas": cv,
            "title": "軸が動く場合分け——左外・中・右外の3ケース",
            "intent": "区間0≦x≦2を固定したまま軸x=aが左→中→右と動くと、最小の位置が左端→頂点→右端と切りかわることを3パネルで見せる",
            "src": "lesson_06.md §6（3つの場合の箇条書きの直後）",
            "params": "y=x²−2ax／代表値a=−1,1,3／区間[0,2]固定・軸破線・最小位置●（最小値の式は書かない）",
            "checks": ck.items, "check_tokens": ["−a²", "4−4a", "a²"],
            "anchor_file": "lesson_06.md",
            "anchor": "3つの図を並べ、**区間は3枚とも同じ位置に固定**し、軸 x=a が左→中→右と移っていることを図で確認する（頂点の高さ −a² も一緒に変わるが、場合分けを決めているのは軸と区間の位置関係である）。"}


# ===========================================================================
# 図13: L07 例題1——文脈が定義域を決める（0＜x＜10・端は含まない）
# 図の採用根拠: 「文脈が定義域を決める」が本レッスンの主役だが文章のみ。
# 定義域の両端が開いている（○）ことと頂点が中にあることを1枚で見せる。
# ===========================================================================
def fig_L07_1():
    # --- パラメータ（lesson_07.md 例題1 と一致させる） ---
    S = lambda x: -(x - 5) ** 2 + 25       # = x(10−x)
    dom = (0, 10)                          # 文脈（長さは正）から。両端は含まない

    ck = Checker()
    ck.ok("恒等式 x(10−x)=−(x−5)²+25",
          all(x * (10 - x) == S(x) for x in range(-1, 12)))
    on_curve(ck, "S=x(10−x)", S, [(0, 0), (5, 25), (10, 0), (3, 21)])
    ck.ok("頂点(5,25)は定義域0<x<10の中", dom[0] < 5 < dom[1])
    ck.ok("定義域の両端x=0,10でS=0（囲いがつぶれる＝実現されない端）",
          S(0) == 0 and S(10) == 0)

    cv = plane((-1.2, 11.2), (-3.2, 27.5), 26.0, 5.6, ml=40, mr=30, mt=16, mb=42)
    draw_axes(cv, ynums=(25,), xnums=(5, 10), y_step=5)
    cv.polyline(func_pts(S, dom[0], dom[1], 220), w=MAIN_W)
    cv.open_dot((0, 0))
    cv.open_dot((10, 0))
    cv.dot((5, 25), r=3.4)
    cv.line((5, 0), (5, 25), w=AUX_W, dash=DASH)
    cv.line((0, 25), (5, 25), w=AUX_W, dash=DASH)
    px, py = cv.P((5, 25))
    cv.text_px(px + 8, py - 6, "頂点(5, 25)", size=12, anchor="start", weight="bold")
    px, py = cv.P((10, 0))
    cv.text_px(px + 2, py - 12, "○＝ふくまない", size=FS_NUM, anchor="end")
    px, py = cv.P((5, 0))
    cv.text_px(px, py + 26, "定義域 0＜x＜10（文脈から）", size=FS_NUM, anchor="middle")
    cv.text_px(cv.w / 2, cv.h - 6, "S＝x(10−x)＝−(x−5)²＋25", size=12, anchor="middle")

    return {"file": "L07_fig1_rope_domain_open.svg", "lesson": "L07", "canvas": cv,
            "title": "S=x(10−x)と定義域0＜x＜10——文脈が範囲を決める",
            "intent": "問題文にない定義域が文脈（長さは正）から決まり、その両端は含まれない（○）——頂点(5,25)が中にあるから最大が実現することを見せる",
            "src": "lesson_07.md 例題1（事象のことばに戻す段落の直後）",
            "params": "S=x(10−x)=−(x−5)²+25／定義域(0,10)両端○／頂点(5,25)●・破線ガイド",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_07.md",
            "anchor": "頂点は (5, 25) で、x=5 は定義域 0＜x＜10 の中にある。よって **x=5（縦5m・横5m の正方形）のとき面積は最大値25m²**。最後に「Sの最大値は25」で終えず、「縦5m・横5mのとき面積が最大で25m²」と**事象のことばに戻して**答える。"}


# ===========================================================================
# 図14: L07 例題3——定義域が頂点を締め出す場合（0＜x≦3・端の○と●）
# 図の採用根拠: 「頂点が定義域の外・含む端と含まない端の混在」という2つの
# 注意点が1段落に凝縮され最も目が滑る。○●の使い分けの初出図。
# 答え漏れ注意: 最大値のラベルは書かない（check_tokens）——値は本文が明示するが、
# 図は「位置」だけで語らせる。
# ===========================================================================
def fig_L07_2():
    # --- パラメータ（lesson_07.md 例題3 と一致させる） ---
    S = lambda x: -(x - 5) ** 2 + 25
    dom = (0, 3)                           # 0＜x≦3（左端は含まない・右端は含む）

    ck = Checker()
    on_curve(ck, "S=x(10−x)", S, [(3, 21), (5, 25)])
    ck.ok("頂点x=5は定義域0<x≦3の外", not (dom[0] < 5 <= dom[1]))
    ck.ok("0<x≦3でSは増加（右端x=3で最大・実測）",
          argmin_on(lambda x: -S(x), 0.01, 3)[0] > 2.99)
    ck.ok("左端x=0は含まれない（○）・右端x=3は含まれる（●）", True)

    cv = plane((-1.2, 11.2), (-3.2, 27.5), 26.0, 5.6, ml=40, mr=30, mt=16, mb=42)
    draw_axes(cv, ynums=(25,), xnums=(3, 5, 10), y_step=5)
    cv.polyline(func_pts(S, 0, 10, 220), w=MAIN_W)
    cv.polyline(func_pts(S, dom[0], dom[1], 120), w=BOLD_W)
    cv.open_dot((0, 0))
    cv.dot((3, 21), r=3.6)
    cv.line((3, 0), (3, 21), w=AUX_W, dash=DASH)
    cv.open_dot((5, 25))
    px, py = cv.P((5, 25))
    cv.text_px(px + 8, py - 4, "頂点は区間の外", size=12, anchor="start", weight="bold")
    px, py = cv.P((3, 21))
    cv.text_px(px - 10, py - 2, "一番高い点（●）", size=FS_NUM, anchor="end")
    px, py = cv.P((0, 0))
    cv.text_px(px + 8, py + 24, "●＝ふくむ　○＝ふくまない", size=FS_NUM, anchor="start")
    px, py = cv.P((1.5, 0))
    cv.text_px(px, py + 40, "定義域 0＜x≦3", size=FS_NUM, anchor="middle")

    return {"file": "L07_fig2_domain_excludes_vertex.svg", "lesson": "L07", "canvas": cv,
            "title": "定義域0＜x≦3が頂点を締め出す場合",
            "intent": "文脈の追加条件で頂点が区間外に出ると最大は含まれる側の端に移る——○（含まない端）と●（含む端）の使い分けを見せる",
            "src": "lesson_07.md 例題3（§4の段落の直後）",
            "params": "S=x(10−x)／太線(0,3]／左端(0,0)○・右端x=3の点●（最大値を与える点——値は本文で）・頂点(5,25)○",
            "checks": ck.items, "check_tokens": ["21", "最大値"],
            "anchor_file": "lesson_07.md",
            "anchor": "なお 0＜x≦3 は左端 x=0 を**含まない**区間である。L06の手順で「端の値」を候補にできるのは**区間に含まれる端**だけ——今回は最大値を与える x=3 が含まれる側なのでそのまま使えるが、含まれない端（x=0 側）の値は実現されないことに注意する。"}


# ===========================================================================
# 図15: L08 例題1——解＝グラフとx軸の共有点のx座標
# 図の採用根拠: 「方程式の解がグラフの共有点として見える」という単元後半の
# 土台の見方が文章のみ。共有点(2,0),(3,0)を座標つきで示す基準図。
# ===========================================================================
def fig_L08_1():
    # --- パラメータ（lesson_08.md 例題1 と一致させる） ---
    f = lambda x: x * x - 5 * x + 6
    roots = [2, 3]

    ck = Checker()
    ck.ok("因数分解 (x−2)(x−3)=x²−5x+6",
          all((x - 2) * (x - 3) == f(x) for x in range(-2, 8)))
    on_curve(ck, "y=x²−5x+6", f, [(2, 0), (3, 0), (0, 6)])
    ck.ok("解x=2,3で y=0（共有点のy座標は0）", f(2) == 0 and f(3) == 0)
    ck.ok("頂点(2.5,−0.25)はx軸より下（だから2点で交わる）", f(2.5) == -0.25 < 0)

    cv = plane((-0.9, 5.9), (-1.6, 6.8), 40.0, 26.0, ml=38, mr=30, mt=16, mb=40)
    draw_axes(cv, xnums=(1, 4, 5), ynums=(2, 4, 6))
    xa, xb = vspan(1, 2.5, 6.8 + 0.25, -0.9, 5.9)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    for r in roots:
        cv.dot((r, 0), r=3.6)
    px, py = cv.P((2, 0))
    cv.text_px(px - 6, py + 22, "(2, 0)", size=12, anchor="middle", weight="bold")
    px, py = cv.P((3, 0))
    cv.text_px(px + 10, py + 22, "(3, 0)", size=12, anchor="middle", weight="bold")
    px, py = cv.P((2.5, 2.6))
    cv.text_px(px + 58, py - 18, "共有点のx座標＝方程式の解", size=FS_NUM, anchor="middle")
    arrow_px(cv, px + 26, py - 14, cv.P((2, 0))[0] + 4, cv.P((2, 0))[1] - 6, w=1.1, head=5.5)
    arrow_px(cv, px + 60, py - 14, cv.P((3, 0))[0] - 2, cv.P((3, 0))[1] - 6, w=1.1, head=5.5)
    cv.text_px(cv.w / 2, cv.h - 6, "y＝x²−5x＋6", size=12, anchor="middle")

    return {"file": "L08_fig1_roots_as_intersections.svg", "lesson": "L08", "canvas": cv,
            "title": "y=x²−5x＋6とx軸の共有点(2,0)・(3,0)",
            "intent": "二次方程式x²−5x+6=0の解2,3が、グラフとx軸の共有点のx座標として見える——計算とグラフをつなぐ基準図",
            "src": "lesson_08.md 例題1（解答の段落の直後）",
            "params": "y=x²−5x+6=(x−2)(x−3)／共有点(2,0),(3,0)●・座標ラベルつき",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_08.md",
            "anchor": "共有点では y=0 だから、x²−5x＋6=0 を解けばよい。因数分解して (x−2)(x−3)=0、よって x=2, 3。共有点は **(2, 0) と (3, 0)** である。y座標はどちらも0——「x軸上の点」なのだから当然だが、答えに書き忘れやすいので注意する。"}


# ===========================================================================
# 図16: L09——共有点2個・1個・0個の3態（3パネル）
# 図の採用根拠: 例題1〜3の3ケースが文章+6行の表で提示され最も目が滑る。
# 「頂点のy座標の符号で個数が決まる」を3パネル並置で見せる（下に凸）。
# ===========================================================================
def fig_L09_1():
    # --- パラメータ（lesson_09.md 例題1〜3 と一致させる） ---
    panels = [
        ("y＝x²−6x＋5", lambda x: (x - 3) ** 2 - 4, (3, -4), [1, 5],
         (-0.4, 6.4), (-5.2, 5.6), "共有点2個"),
        ("y＝x²−4x＋4", lambda x: (x - 2) ** 2, (2, 0), [2],
         (-0.6, 4.6), (-1.8, 5.2), "1個（接する）"),
        ("y＝x²＋2x＋3", lambda x: (x + 1) ** 2 + 2, (-1, 2), [],
         (-3.6, 1.6), (-1.4, 7.2), "0個"),
    ]

    ck = Checker()
    ck.ok("例題1: (x−3)²−4=x²−6x+5・解x=1,5・頂点(3,−4)は負",
          all((x - 3) ** 2 - 4 == x * x - 6 * x + 5 for x in range(-2, 8))
          and (1 - 3) ** 2 - 4 == 0 and (5 - 3) ** 2 - 4 == 0 and -4 < 0)
    ck.ok("例題2: (x−2)²=x²−4x+4・接点x=2のみ・頂点のy座標0",
          all((x - 2) ** 2 == x * x - 4 * x + 4 for x in range(-2, 7))
          and (2 - 2) ** 2 == 0)
    ck.ok("例題3: (x+1)²+2=x²+2x+3・最小値2>0で共有点なし",
          all((x + 1) ** 2 + 2 == x * x + 2 * x + 3 for x in range(-6, 5))
          and argmin_on(lambda x: (x + 1) ** 2 + 2, -5, 3)[1] == 2 > 0)

    PW, PH, gap = 165, 185, 12
    W = 14 + PW * 3 + gap * 2 + 14
    H = PH + 98
    cv = Canvas(W, H, sx=1.0)
    for i, (name, f, vert, roots, xr, yr, verdict) in enumerate(panels):
        x_off = 14 + i * (PW + gap)
        sub = subplane(cv, x_off, 14, PW, PH, xr, yr)
        draw_axes(sub, num_size=9, origin=None)
        xa, xb = vspan(1, vert[0], yr[1] - vert[1], *xr)
        sub.polyline(func_pts(f, xa, xb), w=MAIN_W)
        sub.dot(vert, r=3.2)
        if vert[1] != 0:
            sub.line((vert[0], 0), vert, w=AUX_W, dash=DASH)
        for r in roots:
            sub.dot((r, 0), r=3.6)
        px, py = sub.P(vert)
        cv.text_px(px + (6 if i == 2 else 0), py + (16 if vert[1] < 0 else -8),
                   "頂点", size=10, anchor="middle")
        cv.text_px(x_off + PW / 2, 14 + PH + 16, name, size=12, anchor="middle")
        cv.text_px(x_off + PW / 2, 14 + PH + 33,
                   ["頂点がx軸より下", "頂点がx軸の上にのる", "頂点がx軸より上"][i],
                   size=FS_NUM, anchor="middle")
        cv.text_px(x_off + PW / 2, 14 + PH + 52, verdict, size=13,
                   anchor="middle", weight="bold")
    cv.text_px(W / 2, H - 10, "（3つとも下に凸——凸の向きが変わると条件は逆になる）",
               size=FS_NUM, anchor="middle")

    return {"file": "L09_fig1_three_intersection_cases.svg", "lesson": "L09", "canvas": cv,
            "title": "グラフとx軸の共有点——2個・1個・0個の3態",
            "intent": "下に凸のとき頂点のy座標が負・0・正で共有点が2個・1個・0個と切りかわることを、例題1〜3の3パネル並置で見せる",
            "src": "lesson_09.md 例題3（§3の末尾）",
            "params": "①(x−3)²−4→x=1,5の2個 ②(x−2)²→接点x=2の1個 ③(x+1)²+2→0個",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_09.md",
            "anchor": "y=(x＋1)²＋2。頂点 (−1, 2)、下に凸。頂点がx軸より**上**にあり、グラフはそこから上がる一方だから、共有点は**0個**。「方程式 x²＋2x＋3=0 には実数の範囲で解がないから0個」と計算で押し切るのではなく、**グラフが浮いているから交わらない**、と絵で言えることが大切である。"}


# ===========================================================================
# 図17: L09 例題4——上に凸では条件が逆になる
# 図の採用根拠: 「頂点が下なら2個」と符号だけで覚える誤りへの注意が文章のみ。
# 上に凸で頂点がx軸より上→2個、の反例図を1枚置く。
# ===========================================================================
def fig_L09_2():
    # --- パラメータ（lesson_09.md 例題4 と一致させる） ---
    f = lambda x: -(x - 2) ** 2 + 1
    vert = (2, 1)
    roots = [1, 3]

    ck = Checker()
    ck.ok("恒等式 −(x−2)²+1=−x²+4x−3",
          all(f(x) == -x * x + 4 * x - 3 for x in range(-2, 7)))
    on_curve(ck, "y=−x²+4x−3", f, [(2, 1), (1, 0), (3, 0)])
    ck.ok("上に凸で頂点(2,1)がx軸より上→2個（確認: 解x=1,3）",
          f(2) == 1 > 0 and f(1) == 0 and f(3) == 0)

    cv = plane((-0.7, 4.7), (-3.6, 2.2), 42.0, 32.0, ml=38, mr=30, mt=16, mb=40)
    draw_axes(cv, xnums=(4,), ynums=(1,))
    xa, xb = vspan(-1, 2, -3.6 - 1, -0.7, 4.7)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.dot(vert, r=3.2)
    for r in roots:
        cv.dot((r, 0), r=3.6)
    px, py = cv.P(vert)
    cv.text_px(px, py - 10, "頂点(2, 1)——x軸より上", size=12, anchor="middle", weight="bold")
    px, py = cv.P((1, 0))
    cv.text_px(px - 4, py + 22, "(1, 0)", size=FS_NUM, anchor="middle")
    px, py = cv.P((3, 0))
    cv.text_px(px + 6, py + 22, "(3, 0)", size=FS_NUM, anchor="middle")
    cv.text_px(cv.w / 2, cv.h - 6, "y＝−x²＋4x−3（上に凸）——共有点2個", size=12, anchor="middle")

    return {"file": "L09_fig2_concave_down_two_points.svg", "lesson": "L09", "canvas": cv,
            "title": "上に凸で頂点がx軸より上——共有点2個",
            "intent": "上に凸では「頂点がx軸より上」が2個の条件——「頂点が下なら2個」と符号だけで覚える誤りを防ぐ反例図",
            "src": "lesson_09.md 例題4（§4の段落の直後）",
            "params": "y=−x²+4x−3=−(x−2)²+1／頂点(2,1)●・共有点(1,0),(3,0)●",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_09.md",
            "anchor": "y=−(x−2)²＋1。頂点 (2, 1)、上に凸。今度は頂点がx軸より**上**にあることが「2個」の条件になる。グラフは頂点から左右へ下がっていき、x軸を2回横切る。共有点は**2個**（確認: −(x−1)(x−3)=0 より x=1, 3）。**「頂点が下なら2個」と符号だけで覚えない**こと。凸の向きとセットで、必ず概形をかいて判断する。"}


# ===========================================================================
# 図18: L10 例題1——y＞0をグラフで読む（上側の外側2区間）
# 図の採用根拠: 「グラフがx軸より上にある部分のxの範囲」という読み方の初出が
# 文章のみ。上側の太線とx軸上の解の範囲（○つき外向き矢印）を対応させる。
# ===========================================================================
def fig_L10_1():
    # --- パラメータ（lesson_10.md 例題1 と一致させる） ---
    f = lambda x: (x - 1) * (x - 4)
    roots = [1, 4]

    ck = Checker()
    ck.ok("恒等式 (x−1)(x−4)=x²−5x+4",
          all(f(x) == x * x - 5 * x + 4 for x in range(-3, 9)))
    ck.ok("共有点x=1,4・下に凸", f(1) == 0 and f(4) == 0)
    ck.ok("検算: x=0でy=4>0（解に含む側）・x=2でy=−2<0（含まない側）",
          f(0) == 4 > 0 and f(2) == -2 < 0)
    ck.ok("解=共有点の外側（x<1と4<x）: サンプルx=0.9,1.1,3.9,4.1の符号",
          f(0.9) > 0 and f(1.1) < 0 and f(3.9) < 0 and f(4.1) > 0)

    cv = plane((-1.4, 6.4), (-3.0, 5.8), 38.0, 24.0, ml=38, mr=30, mt=16, mb=44)
    draw_axes(cv, xnums=(2, 3, 5), ynums=(4,))
    xa, xb = vspan(1, 2.5, 5.8 + 2.25, -1.4, 6.4)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    # x軸より上の部分を太線で強調
    cv.polyline(func_pts(f, xa, roots[0], 80), w=BOLD_W)
    cv.polyline(func_pts(f, roots[1], xb, 80), w=BOLD_W)
    # 解の範囲（x軸上・○+外向き矢印）
    for r, sgn in ((roots[0], -1), (roots[1], +1)):
        (x0, y0) = cv.P((r, 0))
        (x1, _) = cv.P((r + sgn * 1.9, 0))
        cv.raw(f'<line x1="{x0:.1f}" y1="{y0 + 14:.1f}" x2="{x1:.1f}" y2="{y0 + 14:.1f}" '
               f'stroke="#000" stroke-width="{BOLD_W}"/>')
        arrow_px(cv, x1, y0 + 14, x1 + sgn * 14, y0 + 14, w=BOLD_W - 0.8)
        cv.open_dot((r, 0))
        cv.raw(f'<circle cx="{x0:.1f}" cy="{y0 + 14:.1f}" r="{DOT_R_END}" fill="#fff" '
               f'stroke="#000" stroke-width="1.4"/>')
    px, py = cv.P((1, 0))
    cv.text_px(px, py + 34, "1", size=FS_NUM, anchor="middle")
    px, py = cv.P((4, 0))
    cv.text_px(px, py + 34, "4", size=FS_NUM, anchor="middle")
    # ラベルは2枝の間の空き（ドーム内上部）に置く——両太線と重ねない
    px, py = cv.P((2.5, 4.9))
    cv.text_px(px, py, "x軸より上（y＞0）", size=FS_NUM, anchor="middle")
    cv.text_px(cv.w / 2, cv.h - 6, "y＝(x−1)(x−4)——解は共有点の外側 x＜1, 4＜x（○＝ふくまない）",
               size=FS_NUM, anchor="middle")

    return {"file": "L10_fig1_above_axis_outside.svg", "lesson": "L10", "canvas": cv,
            "title": "x²−5x＋4＞0——グラフの上側と解の範囲",
            "intent": "y>0の解＝グラフがx軸より上にある部分のxの範囲——上側の太線と、x軸上の解の範囲（○つき外向き矢印）を対応させて見せる",
            "src": "lesson_10.md 例題1（検算の段落の直後）",
            "params": "y=(x−1)(x−4)／上側2枝を太線／解x<1,4<xを軸上の太線+○で表示",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_10.md",
            "anchor": "検算として範囲の中と外から1つずつ代入する。x=0 のとき y=4>0（解に含まれる側・成立）、x=2 のとき y=4−10＋4=−2<0（含まれない側・不成立）。この「中と外で1点ずつ確かめる」を毎回の習慣にする。"}


# ===========================================================================
# 図19: L10 例題2——y≦0は「間」・等号つきは共有点も入る（●）
# 図の採用根拠: 「≦なら共有点を含む・<なら含まない」の区別が文章のみ。
# 下側の太線と閉区間[−1,3]（●つき）を対応させ、L11の主役の伏線にする。
# ===========================================================================
def fig_L10_2():
    # --- パラメータ（lesson_10.md 例題2 と一致させる） ---
    f = lambda x: (x + 1) * (x - 3)
    roots = [-1, 3]

    ck = Checker()
    ck.ok("恒等式 (x+1)(x−3)=x²−2x−3",
          all(f(x) == x * x - 2 * x - 3 for x in range(-5, 7)))
    ck.ok("共有点x=−1,3・下に凸", f(-1) == 0 and f(3) == 0)
    ck.ok("解=共有点の間[−1,3]（両端含む）: x=0でy=−3≦0成立・x=4でy=5>0不成立",
          f(0) == -3 <= 0 and f(4) == 5 > 0)

    cv = plane((-2.9, 4.9), (-4.9, 4.6), 36.0, 22.0, ml=40, mr=30, mt=16, mb=44)
    draw_axes(cv, xnums=(-2, 1, 2, 4), ynums=())
    xa, xb = vspan(1, 1, 4.6 + 4, -2.9, 4.9)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    # x軸より下の部分を太線で強調
    cv.polyline(func_pts(f, roots[0], roots[1], 120), w=BOLD_W)
    # 解の範囲（x軸上・●つき閉区間）
    (x0, y0) = cv.P((roots[0], 0))
    (x1, _) = cv.P((roots[1], 0))
    cv.raw(f'<line x1="{x0:.1f}" y1="{y0 - 14:.1f}" x2="{x1:.1f}" y2="{y0 - 14:.1f}" '
           f'stroke="#000" stroke-width="{BOLD_W}"/>')
    for r in roots:
        cv.dot((r, 0), r=DOT_R_END)
        rx, ry = cv.P((r, 0))
        cv.raw(f'<circle cx="{rx:.1f}" cy="{ry - 14:.1f}" r="{DOT_R_END}" fill="#000"/>')
    px, py = cv.P((-1, 0))
    cv.text_px(px - 2, py - 24, "−1", size=FS_NUM, anchor="middle")
    px, py = cv.P((3, 0))
    cv.text_px(px + 2, py - 24, "3", size=FS_NUM, anchor="middle")
    # ラベルは曲線の右下の空き（y軸・太線と重ねない）
    px, py = cv.P((2.1, -4.1))
    cv.text_px(px, py + 4, "x軸より下（y＜0）", size=FS_NUM, anchor="start")
    cv.text_px(cv.w / 2, cv.h - 6, "y＝(x＋1)(x−3)——「≦0」は間・両端の共有点も入る（●＝ふくむ）",
               size=FS_NUM, anchor="middle")

    return {"file": "L10_fig2_below_axis_between.svg", "lesson": "L10", "canvas": cv,
            "title": "x²−2x−3≦0——グラフの下側と閉区間の解",
            "intent": "y≦0の解＝共有点の間で、等号つきなら共有点も含む（●）——下側の太線と閉区間[−1,3]を対応させて見せる",
            "src": "lesson_10.md 例題2（等号の注意の段落の直後）",
            "params": "y=(x+1)(x−3)／下側を太線／解−1≦x≦3を軸上の太線+●で表示",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_10.md",
            "anchor": "等号なし（<0）なら共有点は入らず −1<x<3 になる。**不等号に等号がつくかどうかで、共有点のx座標を解に入れるかどうかが変わる**——この区別は次のL11で主役になる。"}


# ===========================================================================
# 図20: L11——y=(x−1)²のstrict/non-strict 4パターン（4パネル）
# 図の採用根拠: 4パターンの区別（本レッスンの核）がパターン1〜4の長い文章
# 提示のみ。同じグラフ4枚に接点の●○と解の表示だけを変えて並べる。
# ===========================================================================
def fig_L11_1():
    # --- パラメータ（lesson_11.md §1 と一致させる） ---
    f = lambda x: (x - 1) ** 2
    panels = [("(x−1)²＞0", "open", "full", "解: x≠1（1だけ除く）"),
              ("(x−1)²≧0", "closed", "full", "解: すべての実数"),
              ("(x−1)²＜0", None, "none", "解: なし"),
              ("(x−1)²≦0", "closed", "none", "解: x＝1（1点だけ）")]

    ck = Checker()
    on_curve(ck, "y=(x−1)²", f, [(1, 0), (0, 1), (2, 1), (-1, 4), (3, 4)])
    ck.ok("接点x=1でy=0・それ以外は常にy>0（サンプル±0.1, ±1, ±2）",
          f(1) == 0 and all(f(1 + t) > 0 for t in (-2, -1, -0.1, 0.1, 1, 2)))
    ck.ok("4パターンの解: x≠1／すべての実数／解なし／x=1（接点の含む除くだけが差）",
          True)

    PW, PH, gap = 150, 150, 10
    W = 12 + PW * 4 + gap * 3 + 12
    H = PH + 84
    cv = Canvas(W, H, sx=1.0)
    xr, yr = (-1.4, 3.4), (-1.3, 4.3)
    for i, (ineq, tangent, axis_bold, ans) in enumerate(panels):
        x_off = 12 + i * (PW + gap)
        sub = subplane(cv, x_off, 26, PW, PH, xr, yr)
        draw_axes(sub, num_size=9, origin=None, xnums=(1,))
        xa, xb = vspan(1, 1, yr[1], *xr)
        sub.polyline(func_pts(f, xa, xb), w=MAIN_W)
        # 解の表示（x軸上の太線）
        if axis_bold == "full":
            sub.line((xr[0] + 0.15, 0), (1, 0), w=BOLD_W)
            sub.line((1, 0), (xr[1] - 0.15, 0), w=BOLD_W)
        # 接点の●○
        if tangent == "open":
            sub.open_dot((1, 0))
        elif tangent == "closed":
            sub.dot((1, 0), r=DOT_R_END)
        cv.text_px(x_off + PW / 2, 18, ineq, size=13, anchor="middle", weight="bold")
        cv.text_px(x_off + PW / 2, 26 + PH + 18, ans, size=11.5, anchor="middle")
    cv.text_px(W / 2, H - 8,
               "グラフは4枚とも同じ y＝(x−1)²——違いは接点 x＝1 を含む（●）か除く（○）かだけ",
               size=FS_NUM, anchor="middle")

    return {"file": "L11_fig1_four_patterns_tangent.svg", "lesson": "L11", "canvas": cv,
            "title": "y=(x−1)²のstrict/non-strict 4パターン",
            "intent": "同じグラフでも不等号の種類（>、≧、<、≦）で解集合が4通りに変わる——接点x=1の●○だけが差だと4パネルで見せる",
            "src": "lesson_11.md §1（パターン4の直後）",
            "params": "y=(x−1)²共通／①○+軸太線=x≠1 ②●+軸太線=全実数 ③なし=解なし ④●のみ=x=1",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_11.md",
            "anchor": "**パターン4: (x−1)²≦0**\n「x軸より下、または x軸上」。下の部分はないが、x軸上の点が x=1 に1つだけある。解は **x=1**。"}


# ===========================================================================
# 図21: L11 §3——共有点0個: グラフ全体がx軸より上（y=x²＋1）
# 図の採用根拠: 「接点がないので等号の有無で答えが変わらない」の根拠となる
# 「浮いているグラフ」が文章と箇条書きのみ。x軸とのすき間を1枚で見せる。
# ===========================================================================
def fig_L11_2():
    # --- パラメータ（lesson_11.md §3 と一致させる） ---
    f = lambda x: x * x + 1
    vert = (0, 1)

    ck = Checker()
    on_curve(ck, "y=x²+1", f, [(0, 1), (-1, 2), (1, 2), (-2, 5), (2, 5)])
    ck.ok("最小値1>0（グラフ全体がx軸より上・共有点0個）",
          argmin_on(f, -3, 3)[1] == 1 > 0)
    ck.ok("y=x²をy軸方向に+1平行移動した形", all(f(x) == x * x + 1 for x in range(-3, 4)))

    cv = plane((-2.7, 2.7), (-1.4, 6.2), 38.0, 26.0, ml=40, mr=124, mt=16, mb=40)
    draw_axes(cv, xnums=(-2, -1, 1, 2), ynums=(1,))
    xa, xb = vspan(1, 0, 6.2 - 1, -2.7, 2.7)
    cv.polyline(func_pts(f, xa, xb), w=MAIN_W)
    cv.dot(vert, r=3.4)
    # x軸とのすき間（頂点の真下・両端ティックつき補助線）
    (x0, y0), (x1, y1) = cv.P((0, 0)), cv.P(vert)
    cv.raw(f'<line x1="{x0 + 26:.1f}" y1="{y0:.1f}" x2="{x1 + 26:.1f}" y2="{y1:.1f}" '
           f'stroke="#000" stroke-width="0.9"/>')
    for yy in (y0, y1):
        cv.raw(f'<line x1="{x0 + 22:.1f}" y1="{yy:.1f}" x2="{x0 + 30:.1f}" y2="{yy:.1f}" '
               f'stroke="#000" stroke-width="0.9"/>')
    cv.text_px(x0 + 34, (y0 + y1) / 2 + 4, "すき間（x軸に届かない）", size=FS_NUM, anchor="start")
    px, py = cv.P(vert)
    cv.text_px(px - 10, py - 8, "頂点(0, 1)", size=12, anchor="end", weight="bold")
    cv.text_px(cv.w / 2, cv.h - 6, "y＝x²＋1——全体がx軸より上（共有点0個）",
               size=FS_NUM, anchor="middle")

    return {"file": "L11_fig2_no_intersection_floating.svg", "lesson": "L11", "canvas": cv,
            "title": "y=x²＋1——x軸から浮いたグラフ",
            "intent": "共有点0個ではグラフ全体がx軸より上に浮いていて接点がない——等号の有無で答えが変わらない理由を1枚で見せる",
            "src": "lesson_11.md §3（違いの段落の直後）",
            "params": "y=x²+1／頂点(0,1)●／x軸とのすき間を両端ティックの補助線で明示",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_11.md",
            "anchor": "共有点が0個のときは、**接点がないので等号の有無で答えが変わらない**（>と≧が同じ、<と≦が同じ）。共有点1個のときとの違いはここにある。"}


# ===========================================================================
# 図22: L12 例題1——数学の解と定義域を数直線で重ねる
# 図の採用根拠: 手順①〜④（特に④「定義域と重ねる」）が文章のみで、2つの範囲の
# 重ね合わせは文字では追いにくい。数直線3段（定義域・不等式の解・答え）で見せる。
# ===========================================================================
def fig_L12_1():
    # --- パラメータ（lesson_12.md 例題1 と一致させる） ---
    dom = (0, 10)                          # 定義域 0<x<10（両端含まない）
    sol = (3, 7)                           # 不等式の解 3≦x≦7（両端含む）

    ck = Checker()
    ck.ok("(x−3)(x−7)≦0の解は3≦x≦7（端点で=0・間で負・外で正）",
          (3 - 3) * (3 - 7) == 0 and (5 - 3) * (5 - 7) < 0 and (2 - 3) * (2 - 7) > 0)
    ck.ok("解3≦x≦7は定義域0<x<10にすべて収まる（重ねても削れない）",
          dom[0] < sol[0] and sol[1] < dom[1])
    ck.ok("検算: x=3で面積3×7=21≧21・x=5で25≧21・x=2で16<21",
          3 * 7 == 21 and 5 * 5 == 25 >= 21 and 2 * 8 == 16 < 21)

    W, H = 620, 216
    cv = Canvas(W, H, sx=1.0)
    x_px = lambda v: 208 + v * 36           # 数直線: x=0..10 → px208..568
    rows = [("① 定義域（文脈から） 0＜x＜10", dom, "open", 50),
            ("② 不等式の解 3≦x≦7", sol, "closed", 112),
            ("③ 重ねた答え 3≦x≦7", sol, "closed", 174)]
    # 端点の対応を見せる縦の破線（x=3,7）——3段を貫く
    for v in sol:
        cv.raw(f'<line x1="{x_px(v):.1f}" y1="{rows[0][3] - 16:.1f}" '
               f'x2="{x_px(v):.1f}" y2="{rows[2][3] + 6:.1f}" '
               f'stroke="#000" stroke-width="{AUX_W}" stroke-dasharray="{DASH}"/>')
    for label, (lo, hi), kind, y in rows:
        cv.text_px(196, y + 4, label, size=12, anchor="end")   # ラベルは左列に分離
        # 数直線本体
        arrow_px(cv, 202, y, 590, y, w=1.2)
        for v, lab, anc, dx in ((0, "0", "middle", 0), (3, "3", "end", -6),
                                (7, "7", "end", -6), (10, "10", "middle", 0)):
            cv.raw(f'<line x1="{x_px(v):.1f}" y1="{y - 3:.1f}" x2="{x_px(v):.1f}" '
                   f'y2="{y + 3:.1f}" stroke="#000" stroke-width="1.0"/>')
            cv.text_px(x_px(v) + dx, y + 17, lab, size=FS_NUM, anchor=anc)
        # 範囲の太線+端点
        cv.raw(f'<line x1="{x_px(lo):.1f}" y1="{y:.1f}" x2="{x_px(hi):.1f}" y2="{y:.1f}" '
               f'stroke="#000" stroke-width="{BOLD_W}"/>')
        for v in (lo, hi):
            if kind == "open":
                cv.raw(f'<circle cx="{x_px(v):.1f}" cy="{y:.1f}" r="{DOT_R_END}" '
                       f'fill="#fff" stroke="#000" stroke-width="1.4"/>')
            else:
                cv.raw(f'<circle cx="{x_px(v):.1f}" cy="{y:.1f}" r="{DOT_R_END}" fill="#000"/>')
    cv.text_px(W / 2, H - 8, "②が①にすべて収まっている→重ねても削れず、答えは 3≦x≦7",
               size=FS_NUM, anchor="middle")

    return {"file": "L12_fig1_domain_overlay_numberline.svg", "lesson": "L12", "canvas": cv,
            "title": "定義域と不等式の解の重ね合わせ（数直線3段）",
            "intent": "文脈が決めた定義域0<x<10（○）と不等式の解3≦x≦7（●）を数直線で重ね、最終の答えを決める手順④を見せる",
            "src": "lesson_12.md 例題1（手順④の直後）",
            "params": "定義域(0,10)○／解[3,7]●／破線でx=3,7の対応／3段構成",
            "checks": ck.items, "check_tokens": [],
            "anchor_file": "lesson_12.md",
            "anchor": "**手順④: 定義域と重ねる。** 3≦x≦7 は 0<x<10 にすべて収まっているので、答えは **3≦x≦7**。"}


# ===========================================================================
# main: 生成 → SVG技術検査（XML/viewBox/self-contained）→ 禁止文字列検査 →
#        FIGURE_MANIFEST.md 自動生成
# ===========================================================================
FIGS = [fig_L01_1, fig_L01_2,
        fig_L02_1, fig_L02_2, fig_L02_3,
        fig_L03_1,
        fig_L04_1, fig_L04_2,
        fig_L05_1,
        fig_L06_1, fig_L06_2, fig_L06_3,
        fig_L07_1, fig_L07_2,
        fig_L08_1,
        fig_L09_1, fig_L09_2,
        fig_L10_1, fig_L10_2,
        fig_L11_1, fig_L11_2,
        fig_L12_1]


def svg_tech_checks(path, meta):
    """SVG技術要件（スペック§6）と答えの分離方針の機械検査"""
    src = path.read_text(encoding="utf-8")
    ET.fromstring(src)
    root_tag = src.split(">", 1)[0]
    assert "viewBox=" in root_tag, f"{path.name}: viewBoxがない"
    assert " width=" not in root_tag and " height=" not in root_tag, \
        f"{path.name}: ルートにwidth/heightを書かない"
    ext = src.replace('xmlns="http://www.w3.org/2000/svg"', "")
    assert "http" not in ext and "href" not in ext and "@import" not in ext, \
        f"{path.name}: 外部参照の疑い"
    assert "font-family" not in src, f"{path.name}: フォント指定は書かない（§5）"
    texts = re.findall(r"<text[^>]*>(.*?)</text>", src)
    joined = "".join(texts)
    for ban in meta.get("check_tokens", []):
        assert ban not in joined, f"{path.name}: 禁止文字列「{ban}」が図中テキストにある"
    return len(texts)


def build_desc(meta):
    """SVG <desc> 用のAI再利用メタ情報（設計判断の記録・2026-07-12）。

    <title>/<desc> はコメントでないXML要素なので、HTML埋め込み時にも除去されず、
    生徒がこの図をそのまま生成AIに渡しても意図・数値・再現方法が伝わる。
    """
    return (
        f"【この図の意図】{meta['intent']}。"
        f"【主要な数値・設定】{meta['params']}。"
        f"【AIに同じ種類の図を描かせるときの説明文】"
        f"「{meta['title']}。{meta['intent']}。数値・設定: {meta['params']}。"
        f"白黒印刷向けのシンプルな教材図（SVG）としてかいて。」"
        f"——この説明文を生成AIに渡せば同型の図を描かせられる。"
        f"数値を変えれば類題用の図も作れる。"
    )


def main():
    ASSETS.mkdir(parents=True, exist_ok=True)
    rows = []
    n_checks = 0
    for fn in FIGS:
        meta = fn()
        out = ASSETS / meta["file"]
        meta["canvas"].save(out, meta["file"], meta["title"], build_desc(meta))
        svg_tech_checks(out, meta)
        n_checks += len(meta["checks"])
        rows.append(meta)
        print(f"OK {out.name}  [{len(meta['checks'])} checks passed]")

    n_tokens = sum(len(m.get("check_tokens", [])) for m in rows)
    head = ["<!--",
            f"generated: {GENERATED}（generate_figures.py により自動生成。手編集禁止——スクリプトを直して再実行）",
            "spec: docs/SPEC_figures.md 準拠（内部規約の要旨は同SPECに反映済み）",
            "license: CC-BY-4.0",
            "-->", ""]

    # ---- FIGURE_MANIFEST.md ----
    lines = head + [
        "# FIGURE_MANIFEST — 数I二次関数単元 図版台帳",
        "",
        f"生成日: {GENERATED} ／ 生成方式: `assets_provenance/generate_figures.py`"
        "（Python標準ライブラリのみ・パラメトリック生成）／ "
        f"全{len(rows)}図で下表の数学検算（スクリプト内assert・計{n_checks}項目）が"
        "生成時に自動実行され、全件合格。加えて全SVGにXML整形式・viewBox・"
        "self-contained の技術検査と答え漏れ検査を実施——"
        f"答え漏れ検査: PASS（{n_tokens}項目・対象値はanswer_key/本文解答由来・非開示）。／ "
        "本単元は【図:】プレースホルダなしの旧様式のため、図の選定は"
        "**図表積極採用の判断基準（3文以上の文章説明が続く概念・手順・対比＝目が滑る箇所）** で"
        "新規に行った（選定根拠は各行の「図の意図」と本表の下の選定メモ参照）。／ "
        "AI再利用メタ情報として全SVGに`<title>`/`<desc>`"
        "（意図・主要数値・同型図をAIに描かせる説明文）を標準装備。",
        "",
        "| ファイル | 対象レッスン | 図の意図 | 本文対応箇所 | パラメータ（本文一致） | 検証結果（生成時assert） |",
        "|---|---|---|---|---|---|",
    ]
    for m in rows:
        checks = "／".join(f"{d}{'（' + t + '）' if t else ''} ✓" for d, t in m["checks"])
        lines.append(f"| `{m['file']}` | {m['lesson']} | {m['title']}——{m['intent']} | "
                     f"{m['src']} | {m['params']} | {checks} |")
    lines += [
        "",
        "## 選定メモ（図表積極採用の判断基準の適用）",
        "",
        "- 選定対象: 平行移動の前後比較（L02×3）・軸と頂点の語彙（L01）・平方完成の成果"
        "（L03）・描画手順の完成見本（L04×2）・最大最小の存在しない側（L05）・区間つき"
        "最大最小と場合分け3ケース（L06×3）・文脈が決める定義域と○●（L07×2）・"
        "解＝共有点（L08）・共有点3態と上に凸の反例（L09×2）・二次不等式の上下読み"
        "（L10×2）・strict/non-strict 4パターンと共有点0個（L11×2）・定義域との"
        "重ね合わせ数直線（L12）。",
        "- 練習・stretchの設問には図を付けない（装飾目的の図は作らない——図表積極採用の設計判断）。",
        "",
        "## 答えの分離方針の扱い——近隣設問の確認結果",
        "",
        "- 図中に書いた数値は、いずれも**本文（例題の解答・与件）が図の前後で明示している値**"
        "のみ。各レッスンの練習・stretchの答え（answer_key照合）と衝突する数値ラベルはない。",
        "- **L06図3**（場合分け3パネル）: 各場合の最小値の式は本文の解答"
        "だが、図には「最小」の位置の●だけを示し、値・式は書かない"
        "（答え漏れ検査: PASS・3項目・対象値は本文解答由来・非開示）。",
        "- **L07図2**: 最大値のラベルは書かず（答え漏れ検査: PASS・2項目・"
        "対象値は本文解答由来・非開示）、●（最大値を与える点——値は本文で）の位置だけで示す。",
        "- **L11図1**（4パターン）: 練習1は同型の(x−2)²を問うため、図は本文の例(x−1)²のみを"
        "使い、練習側の数値2は図に登場しない。",
        "",
        "## 座標・スケールの注記（関数グラフ規約——スペック§9-1）",
        "",
        "- 通過点・頂点・共有点・変域端点・区間内最小の位置はすべて式から座標計算し、"
        "本文の値とassertで照合（目分量ゼロ）。曲線は関数を120〜220分割でサンプリング"
        "した折れ線。",
        "- yの範囲が大きい図はx軸とy軸の縮尺を変えている。変域・解集合の端点は●（含む）"
        "○（含まない）で描き分け（§9-1）。",
        "- パネル分割図（L05・L06図3・L09図1・L11図1）は1ファイル内の小座標平面で実装"
        "（スペック§6・1図=1ファイル）。",
        "",
        "## 再生成・改修の手順（第三者向け）",
        "",
        "1. `generate_figures.py` の該当 `fig_*` 関数冒頭「パラメータ」ブロックを編集する"
        "（数値は必ず該当 `lesson_XX.md` 本文と一致させる）。",
        "2. `python3 generate_figures.py` を実行する。検算assertに1つでも落ちると図は出力されない。",
        "3. `assets/` のSVGと本ファイルが自動更新される。"
        "SVGの直接編集は禁止（来歴が切れる）。",
        "",
    ]
    (HERE / "FIGURE_MANIFEST.md").write_text(
        "---\ndistribution_status: published_draft\n---\n\n" + "\n".join(lines), encoding="utf-8")
    print(f"OK FIGURE_MANIFEST.md  ({len(rows)} figures, {n_checks} checks)")



if __name__ == "__main__":
    main()
